### ISSUE TITLE
Leviticus 19:7

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#1002]
Not sure why "defiled" is used here when the Heb is "abominable," which is a tW.

**Comment by TomWarren** [comment]
The word פִּגּ֥וּל means "unclean meat" (not prepared in an appropriate way for the sacrifice. 

The ULB of LEV 19:7 now reads:
\v 5 When you offer a sacrifice of fellowship offerings to Yahweh, you must offer it that you may be accepted.
\v 6 It must be eaten the same day you offer it, or on the next day. If anything remains until the third day, it must be burned up with fire.
\v 7 If it is eaten at all on the third day, it is **unclean meat**; it must not be accepted,
\v 8 and everyone who eats it must carry his own guilt because he has defiled what is holy to Yahweh, and that person must be cut off from his people.

Thanks Henry, 

Tom
