### ISSUE TITLE
REV 2:27-28 ULB vs UDB What did Jesus receive?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#118]
UDB 2:27 They will control them as if they were striking them with an iron rod. They will destroy evildoers just as people shatter clay pots. I will give them the right to do these things, **just as my Father has given me that right.**
ULB  2:28 **Just as I have received from my Father**, I will also give him the morning star.

In Greek, "just as I have received from my father" is in verse 27. 
In the UDB, it is in verse 27 and indicates that Jesus received the right do the things in v27.
In the ULB, it is in verse 28, and it implies that Jesus received the morning star from his Father.

**Comment by TomWarren** [comment]
The Gk at Rev 2:27 has 
καὶ δώσω αὐτῷ τὸν ἀστέρα τὸν πρωϊνόν.
and I give to him the star the first star (morning).
That matches the ULB pretty well. 

The UDB text: (note the shift from "the one who defeats Satan" to "those who defeat Satan" (or similar language, so the UDB has the plural.

\v 27 They will control them as if they were striking them with an iron rod. They will destroy evildoers just as people shatter clay pots. I will give them the right to do these things, just as my Father has given me that right.
**\v 28 I do all of this by the authority that my Father gave to me. Then I will give the morning star to those who rule with me so that we may have great joy in our victory.** 

This may require a note that the morning star (which points to many different ideas, including Christ himself) here probably is referring to the celebration of victory within the Roman world, and giving the morning star is a symbol of their victory over their enemies.

**Comment by SusanQuigley** [comment]
Thanks for the explanation about morning star.

My concern is about this phrase:  hōs kagō eilēpha para tou Patros mou "even as I also received it form my Father."
The ULB has it in verse 28 and modifying what is in 28.
The UDB has it in verse 27 and modifying what is in 27.

**Comment by TomWarren** [comment]
1. There is a textual issue here Some have the phrase in vs 27 and some in 28.
ὡς κἀγὼ εἴληφα παρὰ τοῦ πατρός μου
as I received from my Father

this verse seems to go back to vs 26:
δώσω αὐτῷ ἐξουσίαν ἐπὶ τῶν ἐθνῶν 
Just as I give authority over the nations

Vs 26 sets up Christ receiving authority from the Father, and vs 27 (28 in some versions) giving that authority to those will overcome.

Does that touch on your issue, Susan?

**Comment by aaronfenlason** [comment]
@TomWarren 
I see what Susan is saying, I think. The object of the phrase ὡς κἀγὼ εἴληφα παρὰ τοῦ πατρός μου is a bit ambiguous. Clearly, he is giving to the one who overcomes something that he has received from his father. But he mentions two things that he gives: "authority over the nations" (v. 26) and "the morning star" (v. 28). I see that many modern English translations take the object to be "authority over the nations," but then set off "I will also give him the morning star" with some form of punctuation, such as an em-dash or a period. I think this interpretation is correct, with "the morning star" being an additional and secondary giving. As the ULB reads now, though, the most natural reading suggests that "the morning star" is the primary object of the act of giving. Perhaps a better reading would be:

\v 26 The one who conquers and who does what I have done until the end, to him I will give authority over the nations.
\m
\q
\v 27 'He will rule them with an iron rod, 
\q like clay jars he will break them into pieces,'
\m 
\v 28 just as I have received from my Father. I will also give him the morning star.

Note comma at the end of v. 27 instead of a period, and a period after Father in v. 28 instead of a comma.

**Comment by SusanQuigley** [comment]
Yes, Aaron. That's the issue I was writing about. It's awkward having "just as I received from my Father" so far away from "I will give authority over the nations," but at least the punctuation you suggested could help people see that the two go together and that "just as I received from my father" does not modify "I will also give him the morning star."

**Comment by TomWarren** [comment]
I read what we have in the ULB to reflect the Greek text (however ambiguous) and to go further would be to be writing commentary. Revelation is apocalyptic literature, and the connections are not always that clear.

**Comment by SusanQuigley** [comment]
UDB   **27** I will give them the right to do these things, just as my Father has given me that right. **28** I do all of this with the authority my Father gave me, and I will give the morning star to those who rule with me so that we may have great joy in our victory. 

Tom, thanks for putting  "I do all of this with the authority my Father gave me," in verse 28. 
Did you intended to leave "I will give them the right to do these things, just as my Father has given me that right" in verse 27?

**Comment by TomWarren** [comment]
That phrase was an anticipation of vs 28. 
Vs 27 (UDB) now reads: 
\v 27 They will control them as if they were striking them with an iron rod. They will destroy evildoers just as people shatter clay pots.

**Comment by SusanQuigley** [comment]
Thank you. :)
