### ISSUE TITLE
MRK 9:17, 9:25

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#125]
17 Someone in the crowd answered him, "Teacher, I brought my son to you; he has a spirit that makes him unable to speak, 

25 ...he rebuked the unclean spirit and said, "You mute and deaf spirit, I command you, come out of him, and never enter into him again."

In verse 17 the phrase "mute spirit" is explained and made explicit by being changed into a phrase, whereas when Jesus speaks to the spirit in 25 the phrase "mute..spirit" is retained. I suggest changing 17 to ready "he has a mute spirit."

**Comment by TomWarren** [comment]
I think the difficulty is that the term "mute" may be unknown to some MTTs. It is a medical term. It is a Translation Word and so help is within reach. I noted that many modern translations do the same as we have done, by translating the first mention more expansively and then allowing the reader to be presented with the more opaque medical term "mute" in context.

**Comment by TomWarren** [comment]
Here is the entire section ULB Mark 9:17
**\v 17 Someone in the crowd answered him, "Teacher, I brought my son to you. He has a spirit that makes him unable to speak,
\v 18 and it seizes him, it throws him down and he foams at the mouth, grinds his teeth, and becomes rigid. I asked your disciples to drive it out of him, but they could not."
\v 19 He answered them, "Unbelieving generation, how long will I have to stay with you? How long will I bear with you? Bring him to me."

\s5
\v 20 They brought the boy to him. When the spirit saw Jesus, it immediately threw him into a convulsion. The boy fell on the ground and foamed at the mouth.
\v 21 Jesus asked his father, "How long has he been like this?" The father said, "Since childhood.
\v 22 It has often thrown him into the fire or into the waters and tried to destroy him. If you are able to do anything, have pity on us and help us."

\s5
\v 23 Jesus said to him, "'If you are able'? All things are possible for the one who believes."
\v 24 Immediately the father of the child cried out and said, "I believe! Help my unbelief!"
\v 25 When Jesus saw the crowd running to them, he rebuked the unclean spirit and said, "You mute and deaf spirit, I command you, come out of him, and never enter into him again."**
