### ISSUE TITLE
Rom 4:19 - "dead"

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#132]
The ULB has removed the two references to "dead" but the UDB has retained them. It seems to me that this is the opposite of the norm.

**Comment by TomWarren** [comment]
Romans 4:19 UDB
Here is the fix to the UDB: 

\v 18 He trusted in this promise of God, even though there was no physical reason for him to expect that he would have descendants, because he and his wife were too old to bear children. God had said to Abraham, "You will have so many descendants that they will be as impossible to count as the stars." Abraham believed that, and he believed that he would become the ancestor of many ethnic groups.
\v 19 He did not doubt that God would do what he promised, even though he knew that his body was not able to father a child (he was, after all, about one hundred years old), and he knew that Sarah had never had children, especially now, because she was so old.
