### ISSUE TITLE
Heb 11:37 ULB - footnote mismatch

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#134]
The ULB text was recently changed from "They were killed with the sword" to "They died in murder by the sword". Apart from the awkward new wording, the footnote still retains the old rendering of "They were killed with the sword"."

**Comment by TomWarren** [comment]
Here it is: ULB Heb 11:37. "They were tempted" refers to their being put to a test of faith, rather than temptation as normally understood. 

\v 37 They were stoned. They were sawn in two. They were killed with the sword. They went about in sheepskins and  goatskins. They were destitute, afflicted, and ill-treated.
\f + \ft Some older versions read, \fqa They were stoned. They were sawn in two. They were put to the test. They were killed with the sword. \fqb \f*
