### ISSUE TITLE
Rev 16:21 ULB cursed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#163]
Rev 16:21  **they cursed God** - Some translations use "cursed" and some use "blasphemed." The Greek word is eblasphemesan.  Would you want the word "blasphemed" here? I realize that words have multiple senses and it's not always appropriate to keep strict concordance. I just didn't know about "blaspheme" and "curse", considering the fact that they have two different tW pages.

**Comment by TomWarren** [comment]
The ULB Rev 16:21 now reads: 
\v 21 Huge hailstones, each weighing about thirty-four kilograms, fell from the sky onto the people. Then people blasphemed God because he had punished them in this terrible way, and because the hailstones were very large.

**Comment by pjoakes** [comment]
The ULB should be using biblical measures, and the UDB metric.

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jul 26, 2016, at 2:46 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The ULB Rev 16:21 now reads:
\v 21 Huge hailstones, each weighing about thirty-four kilograms, fell from the sky onto the people. Then people blasphemed God because he had punished them in this terrible way, and because the hailstones were very large.

**Comment by SusanQuigley** [comment]
ULB: Could "cursed" be changed back to "blasphemed"?

**Comment by TomWarren** [comment]
Rev 16:21 now reads (by another hand) "talent" not kilograms.  And cursed was returned to "blasphemed."
