### ISSUE TITLE
Rev 18:1 ULB 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#166]
Rev 18:1 ULB  the wine of the passion of her sexual immorality that brings her wrath.
tou oinou tou thymou tes porneias autes
The ULB seems to have translated tou thymou  twice: "of the passion" and "that brings her wrath"

How about something like this?
the wine of the wrath of her sexual immorality  (meaning, the wine of God's wrath, which is provoked by her sexual immorality)

**Comment by TomWarren** [comment]
Rev 18:3 (ULB) now reads:

\v 3 For all the nations have drunk the wine of her immoral passion. 
\q2 The kings of the earth have committed immorality with her. 
\q The merchants of the earth have become rich from the power of her sensual way of living."

This follows the Gk text more closely, and puts the causal elements in line with the Grk grammar. 
Thanks

**Comment by SusanQuigley** [comment]
OK. Thanks for doing that. I guess now the UDB should match. 
UDB: with whom all the people groups have committed acts of sexual immorality. God is very angry with them.
ULB For all the nations have drunk the wine of her immoral passion. 

The ULB translates _thymou_ as (her) passion, but the UDB translates it as God's anger ("God is very angry with them.)

**Comment by TomWarren** [comment]
The UDB added "God is very angry with them" is more of an editorial remark than following the meaning. It is removed. UDB Rev 18:1-2 now reads:

\p
\v 1 After this I saw another angel, one who had great authority, coming down from heaven. The earth became bright because he was shining so intensely. 
\v 2 He shouted with a very loud voice, "God is about to completely destroy the very evil city of Babylon. As a result, all kinds of evil spirits will live there, and all kinds of foul and detestable birds will live there. Babylon is like a prostitute
\v 3 with whom all the people groups have committed acts of sexual immorality. Yes, and the kings of the earth have done the same things with her. The world's merchants became rich because she wanted to commit so much sexual immorality."

**Comment by aaronfenlason** [comment]
Looks like this has been addressed.
