### ISSUE TITLE
Rev 18:9 Quote differences in ULB and UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#169]
Rev 18:9 ULB - There is an close quote at the end of v8 and no quote at the beginning of 9. This would indicate that the words of 9 and on belong to John.  Then in v 10  John tells what the kings say, and that is in double quotes. All of the speech that John reported is in double quotes. (The kings in v10, the merchants in 16, the sailors in 18 and 19, and apparently in 20.)

Rev 18:9 UDB - This starts with double quotes, which indicates that this is a continuation of Jesus' words, which started in v4. Then in v10 Jesus tells what the kings say, and that is in single quotes. Jesus's words end at the end of v 19. All of the speech that Jesus reported is in single quotes. (The kings in v10, the merchants in 14 and 16-17, the sailors in 18 and 19.)

Should the ULB and UDB be the same on this issue?

**Comment by TomWarren** [comment]
I went through the ULB and UDB in Rev 18 and I think they now have identical quotation marks. 
Give 'em a look.

**Comment by SusanQuigley** [comment]
Thank you. That looks good. 

Now just one more thing dealing with formatting. 
Since we're taking this all as John reporting the speech of the kings, merchants, and sailors, the block indent of 18:11-17 in the ULB should probably be removed. Also, there is no need for a paragraph break or line break in 18:17.

18:11-17.

**Comment by TomWarren** [comment]
The formatting from the USFM is: 

11 The merchants of the earth weep and mourn for her, since no one buys her merchandise anymore— 12 merchandise of gold, silver, precious stone, pearls, fine linen, purple, silk, scarlet, all kinds of scented wood, every vessel of ivory, every vessel made of most precious wood, bronze, iron, marble,  13 cinnamon, spice, incense, myrrh, frankincense, wine, oil, fine flour, wheat, cattle and sheep, horses and chariots, and slaves and human souls.
14 The fruit that you longed for with all your might is gone from you. All your luxury and splendor have vanished, never to be found again.
15 The merchants of these goods who became rich by her will stand away from her at a distance because of the fear of her torment, weeping and loud mourning.
16 They will say,
    "Woe, woe to the great city
    that was dressed in fine linen,
    in purple, and in scarlet,
    and was adorned with gold,
    precious jewels, and pearls!"
17 In a single hour all that wealth has been wasted. Every ship's captain, every seafaring man, sailors, and all whose living is made from the sea, stood off at a distance.

**Comment by SusanQuigley** [comment]
Tom, that looks good, except that in v.16,  it would probably be better not to include "They will say" in the block indent. Could "They will say" be part of the previous paragraph, or simply the beginning of a new paragraph?

**Comment by TomWarren** [comment]
16 seems  right now. Give that a look.

**Comment by SusanQuigley** [comment]
Looks good. Thanks.

**Comment by aaronfenlason** [comment]
Looks like this issue has been concluded.
