### ISSUE TITLE
Rev 18:17 ULB and UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#171]
Rev 18:17 Most versions that use quote marks show that the first sentence of v.17 is part of what the merchants were saying in v. 16. Could the ULB and UDB do the same?  

(Earlier the ULB had that sentence block indented as if it were part of the quote, but the quote mark was at the end of 16. Now I'm asking that the quote mark be moved to the end of 17 and that 17 be part of the block indent.)

The reason for this is that the sentence fits in better with what the merchants were saying than with what John was saying.

**Comment by TomWarren** [comment]
UDB Rev 18 now reads: 
\s5
\v 15 The merchants who sold these things and who had become rich will stand far away because they will be afraid that they will suffer just as the city has. They will weep and mourn, 
\v 16 and they will say, "Terrible things have happened to that great city! That city was like a woman, dressed in clothes made of fine linen cloth and expensive cloth dyed purple and crimson, and adorned with gold, precious stones, and pearls. 
\v 17 But suddenly and swiftly God has destroyed all these expensive things. Every ship's captain, all people who travel by ship, all sailors, and all others who earn their living by traveling on the ocean will stand far away from the city."

ULB Rev 18 now reads: 
\s5
\v 15 The merchants of these goods who became rich by her will stand away from her at a distance because of the fear of her torment, weeping and loud mourning.
\m
\v 16 They will say, 
\q "Woe, woe to the great city
\q2 that was dressed in fine linen, 
\q3 in purple, and in scarlet, 
\q2 and was adorned with gold, 
\q3 precious jewels, and pearls!
\v 17 In a single hour all that wealth has been wasted. 
\q Every ship's captain, every seafaring man, sailors, 
\q and all whose living is made from the sea, 
\q stood off at a distance."

**Comment by SusanQuigley** [comment]
I'm sorry, Tom. I asked for the quote mark to be put at the end of 17. I meant to ask that it be put at the end of the first sentence in 17.

**Comment by TomWarren** [comment]
Moved the " back to the end of 17 and formatted the ULB and the UDB for continuity.
