### ISSUE TITLE
Rev 19:7-8 Is 8 part of the quote?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#172]
Rev 19:8 ULB The quote mark is at the end of v7, but the formatting  makes it look v8  is part of the quote. 

Rev 19:8 UDB The quote mark is at the end of v8.

**Comment by TomWarren** [comment]
Quotation marks go to end of vs 8 in ULB (as in UDB). 
ULB Rev 19:7-8 now reads: 

\q "Hallelujah! 
\q For the Lord 
\q2 our God, the ruler over all, he reigns.

\s5
\q
\v 7 Let us rejoice and be very happy 
\q2 and give him the glory 
\q because the wedding celebration of the Lamb has come, 
\q2 and his bride has made herself ready.
\q
\v 8 She was permitted to be dressed 
\q2 in bright and clean fine linen
\q (for fine linen is the righteous acts of holy people)."
