### ISSUE TITLE
MRK 14:12 capitalize?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#179]
On the first day of unleavened bread, when they sacrificed the Passover lamb, his disciples said to him...

Should "unleavened bread" be capitalized as it is the name of the festival?

**Comment by aaronfenlason** [comment]
@TomWarren 
In light of your comment on the other thread, are there guidelines on when to capitalize and when not to capitalize? I've checked "unleavened bread" in the ULB Synoptics and find that it is capitalized when it is connected with "Festival" and not capitalized when preceded by "day," so "Festival of Unleavened Bread" and "day of unleavened bread." The issue here is, I guess, whether "τὰ ἄζυμα" is an abbreviated form of the longer "ἡ ἑορτὴ τῶν ἀζύμων." This appears to be the way that the ULB has taken it in Mark 14:1, which renders, correctly, I believe, "τὰ ἄζυμα" as "the Festival of Unleavened Bread."

**Comment by TomWarren** [comment]
Generally, we tell all editors now to not change any caps at this point, unless there is a continuity issue. 
At this stage, just leave them and with a script or other manner of coping, they will be handled. Everyone has their own pet rules about caps.  
Just leave them alone.

**Comment by aaronfenlason** [comment]
Sounds good!
