### ISSUE TITLE
EXO 30:17, 30:22 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#189]
Exo 30:17 ULB  Yahweh spoke to Moses, "You must
Exa 30:22 ULB Yahweh spoke to Moses, "Take these

Should the comma after Moses be changed to a period?

**Comment by aaronfenlason** [comment]
@TomWarren 
I've checked how this Hebrew construction is rendered in the ULB throughout Exodus, and the problem is not isolated to this passage. There are 4 basic variations of the Hebrew, and 3 different renderings in the ULB.

וַיְדַבֵּר יהוה אֶל־מֹשֶׁה לֵּאמֹר
Yahweh spoke to Moses and said, - 6:10; 13:1; 16:11
Yahweh spoke to Moses: - 14:1
Yahweh spoke to Moses, - 30:11, 17, 22; 31:1; 40:1

וַיֹּאמֶר יהוה אֶל־מֹשֶׁה לֵּאמֹר
Yahweh spoke to Moses: - 31:12

וַיֹּאמֶר יהוה אֶל־מֹשֶׁה
Then Yahweh spoke to Moses, - 8:1

וַיְדַבֵּר יהוה אֶל־מֹשֶׁה
Then Yahweh spoke to Moses, - 32:7; 33:1

The two issues seem to be 1) whether there should be a comma or a colon, and 2) whether to include "and said" on phrases that include the infinitive construct. I think 1) should include the comma and 2) should include "and said." Give me a thumbs up and I'll make the changes. Or other thoughts...

**Comment by pjoakes** [comment]
What about the traditional rendering of the infinite construct as: “saying,”

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On Aug 12, 2016, at 11:01 AM, aaronfenlason <notifications@github.com<mailto:notifications@github.com>> wrote:


@TomWarren<https://github.com/TomWarren>
I've checked how this Hebrew construction is rendered in the ULB throughout Exodus, and the problem is not isolated to this passage. There are 4 basic variations of the Hebrew, and 3 different renderings in the ULB.

וַיְדַבֵּר יהוה אֶל־מֹשֶׁה לֵּאמֹר
Yahweh spoke to Moses and said, - 6:10; 13:1; 16:11
Yahweh spoke to Moses: - 14:1
Yahweh spoke to Moses, - 30:11, 17, 22; 31:1; 40:1

וַיֹּאמֶר יהוה אֶל־מֹשֶׁה לֵּאמֹר
Yahweh spoke to Moses: - 31:12

וַיֹּאמֶר יהוה אֶל־מֹשֶׁה
Then Yahweh spoke to Moses, - 8:1

וַיְדַבֵּר יהוה אֶל־מֹשֶׁה
Then Yahweh spoke to Moses, - 32:7; 33:1

The two issues seem to be 1) whether there should be a comma or a colon, and 2) whether to include "and said" on phrases that include the infinitive construct. I think 1) should include the comma and 2) should include "and said." Give me a thumbs up and I'll make the changes. Or other thoughts...

**Comment by aaronfenlason** [comment]
@pjoakes ,
I like that better. Thanks.
