### ISSUE TITLE
PSA 9:19 ULB Do not let man prevail

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#220]
ULB Arise, Yahweh; do not let man conquer us;
UDB do not allow them to think that because they are strong, they will never be punished.

The ULB and UDB interpret "Do not let man prevail" differently. 
Some versions have something to the effect of "Do not let man defy you" or "Do not let man triumph."
Could the ULB be changed to something like that?

**Comment by pohlig** [comment]
I've changed the ulb to:

Arise, Yahweh; do not let man win against you

and the udb to

do not allow them to think that because they are strong, you will never punish them.

**Comment by TomWarren** [comment]
The UDB at PSA 9:19 now reads: 
\v 19 Yahweh, do not allow our enemies to conquer us 
\q just because they are strong;
\q You see what the people do and you bring justice to them all. 

The ULB at PSA 9:19 now reads: 
\v 19 Arise, Yahweh! Do not let man conquer us!
\q May the nations be brought to justice in your sight.

**Comment by TomWarren** [comment]
@pohlig 
I also worked on this one. We are falling over each other. 

Tom
