### ISSUE TITLE
PSA 53:3 has gone back

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#223]
ULB 53:3 Everyone of them **has gone back**
UDB and TFT don't have anything like this. Perhaps it was thought to mean the same as the next phrase.

I see that some versions have this, but I don't know what it means. I doubt that it means that people have gone back to their sin; that would imply that they had left it at some point.

Some versions have  "turned back" or  turned away" or "rejects God." I could easily write a note for "turned back" or "turned away"

**has turned back** - Rejecting God and what is right is spoken of as turning back. AT: "has turned away from doing what is right" or "has rejected God" (See Metaphor)

**Comment by TomWarren** [comment]
The ULB PSA 53:3 now reads: 
\v 3 Everyone of them has turned away, they are corrupt.
\q There is not one who does good, not even one.

THe UDB PSA 53:3 now reads: 
\v 3 But everyone had turn away from God; they are all morally corrupt.
\q2 no one does what is good.

This may help. 
Tom

**Comment by SusanQuigley** [comment]
This helps a lot. Thanks.

**Comment by pjoakes** [comment]
The second line of the UDB needs a capital N. It would be good if you could use two different words instead of “corrupt" in both versions. The ULB has “filthy” for the same verb in Ps 14:3 (exact same context), so you could also use that here (or something better in both places,  like “dishonest," "rotten,” or “immoral”), and move “morally corrupt” to the UDB.

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Sep 1, 2016, at 10:25 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The ULB PSA 53:3 now reads:
\v 3 Everyone of them has turned away, they are corrupt.
\q There is not one who does good, not even one.

THe UDB PSA 53:3 now reads:
\v 3 But everyone had turn away from God; they are all morally corrupt.
\q2 no one does what is good.

This may help.
Tom

**Comment by TomWarren** [comment]
That change "N" was made just after posting this. 
Thanks for looking at it. 

Tom

**Comment by SusanQuigley** [comment]
Tom, did you see Perry's comment on "corrupt" in the ULB and UDB of 53:3a?
Perry, the translationWords section has a link to the page for "corrupt."

If "corrupt" is used, I don't think I need to write a note because it seems like the ordinary use of the word--not a metaphor. If a word like "filthy" is used, I'll write a note.

**Comment by TomWarren** [comment]
I have done all to be faithful to the text. 

The Heb אלח , means to be "morally corrupt," and it is the translation used by most modern versions:
ESV, become corrupt; NIV84 become corrupt; NET08 morally corrupt; CEV92 corrupt

RSV52 depraved

ULB PSA 14:3 has been changed: (this follows the preponderance of modern translations)
\v 3 Everyone has turned aside; all have become corrupt.
\q There is no one who does good, no, not one.

UDB PSA 14:3 now reads:
v 3 Everyone turns away from Yahweh and they do disgusting, filthy things. 
q2 No one does what is good.

**Comment by pjoakes** [comment]
Thanks, Tom.

Perry
On Sep 1, 2016, at 1:35 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I have done all to be faithful to the text.

The Heb אלח , means to be "morally corrupt," and it is the translation used by most modern versions:
ESV, become corrupt; NIV84 become corrupt; NET08 morally corrupt; CEV92 corrupt

RSV52 depraved

ULB PSA 14:3 has been changed: (this follows the preponderance of modern translations)
\v 3 Everyone has turned aside; all have become corrupt.
\q There is no one who does good, no, not one.

UDB PSA 14:3 now reads:
v 3 Everyone turns away from Yahweh and they do disgusting, filthy things.
q2 No one does what is good.
