### ISSUE TITLE
PSA 56:1 swallow up or harass

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#229]
Psalm 56 ULB
v. 1 someone wishes to **swallow** me **up**;
v. 2 My enemies wish to **swallow** me **up**

UDB
v. 1 men have **harassed** me
v. 2 My enemies **harass** me

According to UBS-TH, the meaning of the Hebrew word is uncertain. Obviously "swallow up" is a metaphor, but I think it would be a metaphor of "destroy" or "kill,"  not "harass." According to the NET Bible notes, sha'af "trample, crush" has a homonym meaning "pant after." I wonder if the ULB and UDB translations are based on two different Hebrew words, and if one could be changed so that they are based on the same Hebrew word.

**Comment by SusanQuigley** [comment]
I added the following note in case ULB and UDB stay the same.
  * **to swallow me up** - Destroying or killing someone is spoken of as swallowing him up as a wild animals swallows up a smaller animal. AT: "to kill me." Another possible meaning is "harass" or "persecute." (See: [[:en:ta:vol1:translate:figs_metaphor]])

**Comment by TomWarren** [comment]
I am working on this now. Will make a change to the UDB.

**Comment by TomWarren** [comment]
I didn't see "swallow" in the Heb. it is more like "crush" or "trample." The Heb translation was far afield of the ULB. 
There was an optional feel to the translation (they might fight me, they might not), but the Heb was more definitive ("men are attacking me").
This rendering is closer, I hope. I didn't go through the whole PSA just these two vss. 

The ULB PSA 56:1-2 now reads: 
\v 1 Be merciful to me, God, for men are attacking me!
\q All the day long those who fight me, press their assault. 
\q
\v 2 My enemies trample me all day long;
\q for there are many who arrogantly fight against me.

UDB PSA 56:1-2 now reads: 
\v 1 God, act mercifully toward me because men are attacking me!
\q2 All day long an enemy presses closer and closer to me, so they might take my life.
\q1
\v 2 All day long my enemies seek to crush the life from me,
\q2 there are many enemies attacking me!

**Comment by SusanQuigley** [comment]
Thank you for working on this.
I don't think the comma is needed in the following sentence. It's separating the subject (those who fight me) from the predicate (press their assault).
ULB v1 All the day long those who fight me, press their assault. 

Question about UDB:
**so they might take my life** - Is this the enemy's purpose,  or is it something that the psalmist concludes might happen based on the fact that they are pressing closer and closer to him?
If it is meant as the enemy's purpose, could it be changed to "in order to take my life"?

**Comment by TomWarren** [comment]
Yep.  Comma removed: 
ULB now: 
\v 1 Be merciful to me, God, for men are attacking me!
\q All the day long those who fight me press their assault. 
UDB
\v 1 God, act mercifully toward me because men are attacking me!
\q2 All day long an enemy presses closer and closer to me **because they want to take my life.**
\q1
\v 2 All day long my enemies seek to crush the life from me,
\q2 there are many enemies attacking me!
See if that works.

**Comment by SusanQuigley** [comment]
That works. Thanks.
