### ISSUE TITLE
PS 105:24

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#244]
ULB - God increased his people greatly
UDB - Years later Yahweh caused the descendants of Jacob to become very numerous

"God" or "Yahweh"? Check and choose the right one here.

**Comment by TomWarren** [comment]
The subject must be supplied because the last referent is to Jacob. The author did not make the subject  explicit (assuming that it would be obvious), but we add Yahweh (probably not "God" as the ULB had it).
The UDB is very good here. 

The ULB needed some tending: 
\v 24 Yahweh made his people fruitful,
\q and he made them stronger than their enemies. 
NOTE: (**_stronger_** is the Hiph meaning of עצם)
