### ISSUE TITLE
PSA 60:4b ULB vs UDB truth or bow

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#246]
ULB: so that it may be displayed because of the truth. 
UDB: so that they can gather around it and not be killed by the enemies' arrows.

The ULB and UDB come from different understandings of the Hebrew words.
The following favor the ULB: KJV,  AS95,
The following favor the UDB: NIV, ESV, NRSV,NET, TEV, NLT, GWN

I find the UDB easier to understand in the context.

**Comment by TomWarren** [comment]
This seems to align matters. TW

ULB PSA 60:4 NOW READS: 
\v 4 For those who honor you, 
\q you have set up a banner 
\q to be displayed against those who carry the bow. 

UDB PSA 60:4 (no change)
\v 4 But you have raised a battle flag for those who honor you
\q2 so that they can gather around it and not be killed by the enemies' arrows.

ULB PSA 61:4 now reads: 
\v 4 Let me live in your tabernacle forever!
\q Let me take refuge under the shelter of your wings. 

UDB PSA 61:4
\v 4 Allow me to live close to your sacred tent all during my life!
\q1 Allow me to be safe as a little bird is safe under its mother's wings.

**Comment by SusanQuigley** [comment]
Tom,  thanks for fixing 60:4 so that both versions show that the banner has something to do with the battle.
It looks like in the UDB, the banner is set up to call the army together to get away from the danger of the enemy.
In the ULB, it looks like the banner is set up to call the army together to take their stand against the enemy and fight.
Is that right?

As for 61:4, I accidentally gave that for the title of this issue. I haven't looked at it. But what you wrote for it above looks good.

**Comment by TomWarren** [comment]
I think they are fully aligned now. Take a look.
Thanks, TW

**Comment by SusanQuigley** [comment]
Great. Thank you.
