### ISSUE TITLE
NUM 13:4-14  Change periods to semi-colons?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#258]
Num 13:4-15 has a list of the tribal leaders that were sent to spy out Canaan. 
The ASV and ULB use a period at the end of each entry. 
In verses 4-14, could the period be changed to a semi-colon, since it's all one long sentence?
(The period would only come at the ned of v. 15.)

**Comment by TomWarren** [comment]
That is easier to follow. ULB NUM 13:4-15 now reads: 
\s5
\v 3 Moses sent them from the wilderness of Paran, so that they might obey Yahweh's command. All of them were leaders among the people of Israel.
\v 4 These were their names: from the tribe of Reuben, Shammua son of Zaccur;
 
\s5
\v 5 from the tribe of Simeon, Shaphat son of Hori;
\v 6 from the tribe of Judah, Caleb son of Jephunneh;
\v 7 from the tribe of Issachar, Igal son of Joseph;
\v 8 from the tribe of Ephraim, Hoshea son of Nun;
 
\s5
\v 9 from the tribe of Benjamin, Palti son of Raphu;
\v 10 from the tribe of Zebulun, Gaddiel son of Sodi;
\v 11 from Joseph's descendants, namely, from the tribe of Manasseh, Gaddi son of Susi;
\v 12 from the tribe of Dan, Ammiel son of Gemalli;
 
\s5
\v 13 from the tribe of Asher, Sethur son of Michael;
\v 14 from the tribe of Naphtali, Nahbi son of Vophsi;
\v 15 from the tribe of Gad, Geuel son of Machi.
\v 16 These were the names of the men whom Moses sent to examine the land. Moses called Hoshea son of Nun by the name of Joshua.

**Comment by SusanQuigley** [comment]
Thank you.
