### ISSUE TITLE
NUM 14:33 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#262]
UDB And like shepherds wander around in the desert as they take care of their sheep, your children will wander around in this desert for forty years. 
ULB Your children will be wanderers in the wilderness for forty years.

At first I thought that the TFT and UDB had added a simile that was not in the original. 
But now it looks like the ULB is missing a metaphor. 
The Hebrew looks to be: And your children will **go out shepherding** in the wilderness for forty years.

Could one of these happen? Either put the metaphor in the ULB or get rid of the simile in the UDB?

**Comment by pohlig** [comment]
I've altered the note in this way:

Your children will be shepherds in the wilderness - Some modern versions choose to translate, "Your children will wander in the wilderness." This is because in ancient times, shepherds usually wandered from place to place so their flocks and herds could find pasture.

**Comment by SusanQuigley** [comment]
Thanks, Jim. Since your note doesn't call it a metaphor, should I understand that this is not a figure of speech, that they really would be shepherds?
