### ISSUE TITLE
NUM 15:5  ULB vs UDB One or two kinds of offering? Lamb for both?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#266]
ULB Do this with the burnt offering or **with** the sacrifice of each lamb.
This has two kinds of offerings: a burnt offering and a sacrifice. The second **with** gives the impression that "of each lamb" modifies only "the sacrifice" and that the burnt offerings were not necessarily lambs. If "of each lamb" should modify both phrases, it would be good to remove the second "with."
Do this with the burnt offering or the sacrifice of each lamb.

UDB:  When you offer a lamb to be a sacrifice to be completely burned
This indicates that the sacrifice an the burnt offering were the same thing. If this should be understood as two different kinds of offering, it would be good to add the word "or".
When you offer a lamb to be a sacrifice **or** to be completely burned

**Comment by TomWarren** [comment]
ULB of NUM 15:5 now reads: 
\v 5 You must also offer one-fourth of a hin of wine with the burnt offering or with the sacrifice of each lamb.
UDB of NUM 15:5 now reads: 
\v 5 When you offer a young ram or goat for the sacrifice that will be completely burned up, or when you offer as a sacrifice of every young lamb, you should prepare about a liter of wine to be used as a drink offering.

**Comment by pjoakes** [comment]
For the UDB, when God and maybe others are specifying amounts in metric, it sounds better to not say “about.” That makes it sound like God doesn’t really care how much it is. I think it sounds better to just say “you should prepare a liter of wine.” What do you think?


Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Oct 6, 2016, at 12:03 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


ULB of NUM 15:5 now reads:
\v 5 You must also offer one-fourth of a hin of wine with the burnt offering or with the sacrifice of each lamb.
UDB of NUM 15:5 now reads:
\v 5 When you offer a young ram or goat for the sacrifice that will be completely burned up, or when you offer as a sacrifice of every young lamb, you should prepare about a liter of wine to be used as a drink offering.

**Comment by TomWarren** [comment]
There seems to me to be a price to pay in either direction. If you say it is a litre, and the conversion of the liquid volume is discovered to be .75 liter, then the text appears to be inaccurate.
If you say in the text "about a liter" then it can be taken in at least two ways: you know what a liter is and this measure is close to that, or we don't know and are just guessing about the volume of the liquid. 
I don't have the aversion that some have in using "about a liter" it is clear, and it doesn't provide "a liter" as reference and then the volume is found to be imprecise or as some would say, wrong. 

Most weights and measures tables in recent Bibles (some at least) have a line about the difficulty of matching modern measures with ancient terms. 

I think "about a liter" is ok.

**Comment by SusanQuigley** [comment]
The tA pages on measurements deal with the issue of God giving exact measurements, and the difficulty of communicating that when using other units of measure.
The tA page for volume has these points under translation principles.
* If you do not use the Biblical measures, try not to give the readers the idea that the measurements are exact. For example, if you translate one hin as "3.7 liters," readers might think that the measurement is exactly 3.7 liters, not 3.6 or 3.8. It would be better to use "three and a half liters" or "four liters."
* When God tells people how much of something to use, and when people use those amounts in obedience to him, do not say "about" in the translation. Otherwise it will give the impression that God did not care exactly how much they used.

https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bvolume.md
https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bdistance.md
https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bweight.md

**Comment by pjoakes** [comment]
Thanks for looking that up, Susan. I had forgotten where that was. In this case, 1/4 of a hin is a fairly exact measure, so it should be translated in an exact way, if we can. We can put a statement in an intro that the metric measures are only approximates of the biblical ones, but not in the text itself.

Thanks,

Perry

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Oct 11, 2016, at 10:30 AM, SusanQuigley <notifications@github.com<mailto:notifications@github.com>> wrote:


The tA pages on measurements deal with the issue of God giving exact measurements, and the difficulty of communicating that when using other units of measure.
The tA page for volume has these points under translation principles.

  *   If you do not use the Biblical measures, try not to give the readers the idea that the measurements are exact. For example, if you translate one hin as "3.7 liters," readers might think that the measurement is exactly 3.7 liters, not 3.6 or 3.8. It would be better to use "three and a half liters" or "four liters."
  *   When God tells people how much of something to use, and when people use those amounts in obedience to him, do not say "about" in the translation. Otherwise it will give the impression that God did not care exactly how much they used.

https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bvolume.md
https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bdistance.md
https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/translate_bweight.md
