### ISSUE TITLE
NUM 16:45 Delete "they"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#274]
ULB Then Moses and Aaron **they** lay facedown.

Delete "they"?

**Comment by TomWarren** [comment]
Yep. There seemed to be an insertion of subjects for the understanding of the MTT. Yahweh was speaking to Moses (but Aaron was present), and then the Heb says, "They fell on their faces." Possibly confusing the reader, since Moses was directly addressed in the previous sentence. So this was made more clear. 

The ULB now reads: 
\v 45 "Go away from in front of this community so that I may consume them immediately." And Moses and Aaron lay down with their faces to the ground.
