### ISSUE TITLE
JOS 7:1  ULB "Zimri" to "Zabdi"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#317]
Josh 7:1
ULB Achan son of Carmi son of **Zimri**, son of Zerah
UDB Achan. He was a son of Carmi, a grandson of **Zabdi**, and a great-grandson of Zerah

Could Zimri in JOS 7:1  ULB be changed to Zabdi? 

7:1: Hebrew has Zabdi, and LXX has Zambri.
7:17 Hebrew has Zabdi, and LXX has Zambri.  ULB and UDB have Zabdi
7:18 Hebrew has Zabdi, and LXX has Zambri.  ULB has Zabdi.  No name is used in the UDB.

1 Chronicles 2:6  Hebrew has Zimri, and LXX has Zambri.  ULB and UDB have Zimri.

**Comment by TomWarren** [comment]
The ULB of JOS 7:1 now reads: 
\v 1 But the people of Israel acted unfaithfully regarding the things that were set apart for destruction. Achan son of Carmi son of **Zabdi** son of Zerah, from the tribe of Judah, took some things that were set apart for destruction, and Yahweh's anger burned against the people of Israel.
The UDB has "Zabdi".

ULB of JOS 7:16-18 was edited and  now reads: 
\v 16 So, Joshua got up early in the morning and brought Israel near, tribe by tribe, and the tribe of Judah was selected.
\v 17 Joshua brought the clans of Judah near, and the clan of the Zerahites was selected. He brought near the clan of the Zerahites person by person, and Zabdi was selected.
\v 18 He brought Zabdi's household near, person by person, and Achan son of Carmi, son of Zabdi, son of Zerah, from the tribe of Judah, was selected.

The UDB of JOS 7:18 omitted some family connections that the MTT may see in the ULB. 
It now reads: 

\v 18 Then Joshua told the men from that family to present each member of their family, one at a time, so that the guilty person may be selected. And Yahweh indicated that Achan was the guilty man and he was taken out of the people of Judah. Achan was the son of Carmi; Carmi was the son of Zabdi; and Zabdi was the son of Zerah.

The 1CH 2:6 needs no attention.
Thank you. 
TW

**Comment by SusanQuigley** [comment]
Great. Thank you.
