### ISSUE TITLE
2SA 9:9-10

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#321]
ULB "I have given to your **master's son** all the possessions of Saul and his family.
\v 10 You are to plow the land for him, you and your sons and your servants, and you must harvest the crops so that your **master's grandson** may have food to eat. But Mephibosheth your **master's grandson** will always eat at my table." Now Ziba had fifteen sons and twenty servants.

This is not translated consistently. The Hebrew is the same in all three phrases, but one has "master's son" (which would refer to Jonathan) and the others have "master's grandson" (which would refer to Saul). I think in the context all should say "master's grandson."

**Comment by TomWarren** [comment]
ULB of 2SA 9:9-10 now reads: 
\v 9 Then the king called to Ziba, Saul's servant, and said to him, "All that belonged to Saul and his family I have given to your master's grandson.
\v 10 You, your sons, and your servants must till the land for him and you must harvest the crops so that your master's grandson will have food to eat. For Mephibosheth, your master's grandson, must always eat at my table." Now Ziba had fifteen sons and twenty servants.

Thanks. Perhaps a note on "your master's son" where "son" means descendant, and here, "grandson" from the context. 
Thanks,
TW
