### ISSUE TITLE
2SA 17:29 frag

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#327]
honey, butter, sheep, and milk curds. So David and the people with him could eat. These men had said, "The people are hungry, weary, and thirsty in the wilderness."

The following is a fragment: 
So David and the people with him could eat.

**Comment by TomWarren** [comment]
The ULB of 2SA 17:29 now reads: 
\v 27 It came about when David had come to Mahanaim, that Shobi son of Nahash from Rabbah of the Ammonites, and Machir son of Ammiel from Lo Debar, and Barzillai the Gileadite from Rogelim,
\v 28 brought sleeping mats and blankets, bowls and pots, and wheat, barley flour, roasted grain, beans, lentils,
\v 29 honey, butter, sheep, and milk **curds, so that David and the people with him could eat.** These men had said, "The people are hungry, weary, and thirsty in the wilderness."
