### ISSUE TITLE
ISA 14:20 Who will not be mentioned again?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#332]
ULB:  You who have killed your people are the son of evildoers and will never be mentioned again.
UDB: and have caused your own people to be killed. The descendants of wicked people like you will never be honored again.

In the  ULB the king is identified as "the son of evil doers", and **he** will not be mentioned again.
In the UDB the people who will not be mentioned again are the descendants of people who are wicked like the king.

Could both version have the same interpretation? 
**New ULB?**  and killed your people. The son of evildoers will never be mentioned again.  
(This leaves it ambiguous as to whether "the **son** of evil doers" refers to the king, to the descendants of any evil doers, or to the king's descendants. It also leaves it ambiguous as to whether it refers to a literal son or if "son of evildoers" simply means "evil person." )

**New UDB?** and have caused your own people to be killed. You are the son of wicked people, and will never be honored again.
or
**New UDB?** and have caused your own people to be killed. You are  a wicked person, and your descendants will never be honored.

**Comment by TomWarren** [comment]
The ULB  and UDB were re-edited, several issues were redone. TW

ULB ISA 14:18-20 now reads:
\v 18 All the kings of the nations,
\q1 all of them lie down in honor, each one in his own tomb.
\q1
\v 19 But you are cast out of your grave like a branch thrown away.
\q1 The dead cover you like a garment, those pierced by the sword, who go down to the stones of the pit.
\q1
\v 20 You will not join them in burial, because you have destroyed your land 
\q1 and killed your people.
\q1 The offspring of evildoers will never be mentioned again."

The UDB of ISA 14:20 now reads:
\v 18 All the kings of the nations,
\q1 all of them sleep in honor, every one in his own tomb.
\q1
\v 19 But you are cast out of your grave like a branch thrown away.
\q1 The dead cover you like a garment, those pierced by the sword, who go down to be among the stones where the dead rest.
\q1
\v 20 You will not join them in burial, because you have destroyed your land 
\q1 and killed your people.
\q1 The offspring of evildoers will never be mentioned again."

The last phrase in the UDB didn't mean "not honored" but "not spoken of" even worse than "not honored."

**Comment by SusanQuigley** [comment]
Thank you. I've updated the notes.

**Comment by pjoakes** [comment]
I know that it makes the Notes writing easier for the ULB and UDB to be identical, but that is not their purpose. These are so similar that there really is no benefit to having them both. Could you offer some translation alternatives by alternate phrasing or vocabulary? Remember, the UDB can be freer, and shouldn’t have passive voice, as in v. 19.

Thanks! Keep up the good work!

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Nov 18, 2016, at 10:40 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The ULB and UDB were re-edited, several issues were redone. TW

ULB ISA 14:18-20 now reads:
\v 18 All the kings of the nations,
\q1 all of them lie down in honor, each one in his own tomb.
\q1
\v 19 But you are cast out of your grave like a branch thrown away.
\q1 The dead cover you like a garment, those pierced by the sword, who go down to the stones of the pit.
\q1
\v 20 You will not join them in burial, because you have destroyed your land
\q1 and killed your people.
\q1 The offspring of evildoers will never be mentioned again."

The UDB of ISA 14:20 now reads:
\v 18 All the kings of the nations,
\q1 all of them sleep in honor, every one in his own tomb.
\q1
\v 19 But you are cast out of your grave like a branch thrown away.
\q1 The dead cover you like a garment, those pierced by the sword, who go down to be among the stones where the dead rest.
\q1
\v 20 You will not join them in burial, because you have destroyed your land
\q1 and killed your people.
\q1 The offspring of evildoers will never be mentioned again."

The last phrase in the UDB didn't mean "not honored" but "not spoken of" even worse than "not honored."

**Comment by TomWarren** [comment]
UDB at ISA 14:19 now reads:
\v 19 Someone will cast you out of your grave and make you like a branch that they throw away.

**Comment by SusanQuigley** [comment]
According to SIL-TN, Oswalt's Commentary, and Young's commentary, Isa 14:19 probably means that the king's body was not buried in a grave (not that  he was buried and then someone cast him out.) Could the UDB be changed to something like one of these?

But they toss you aside, not in a grave, like a branch that they throw away.
or 
But they toss you aside like a branch; they don't put you in a grave.

**Comment by TomWarren** [comment]
The UDB of ISA 14:19 now reads:

\v 19 Someone will cast you aside, but not into a grave. Like a branch they throw you away. 

Thanks, TW

**Comment by SusanQuigley** [comment]
Thank you.
