### ISSUE TITLE
2CO 13:10 ULB the authority the Lord gave me

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#343]
ULB I do not want to have to use the authority the Lord gave me **so that** I may build you up and not tear you down.

This sounds like Paul doesn't want to want to use the authority that God gave him to build people up.

Greek glosses look to me like "so that I should not treat you harshly according to the authority that the Lord has given me...." So what would you think of something like this?

 \v 10 I write these things while I am away from you, so that when I am with you I do not have to act harshly toward you **with the authority the Lord gave me, because he gave it to me** so that I may build you up and not tear you down.

**Comment by TomWarren** [comment]
I looked through this verse carefully. This is my suggestion. 
The ULB of 2CO 13:10 now reads:

\v 10 I write these things while I am away from you, so that when I am with you I do not have to deal harshly with you in the use of my authority—which the Lord gave to me, so that I may build you up, and not tear you down.

**Comment by SusanQuigley** [comment]
That's beautiful. Thank you.
