### ISSUE TITLE
Isa 28: 15 and Isa 28:18 Covenant with Death

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#347]
Isa 28:15 UDB We have made an alliance with the leaders of Egypt, so we will not be killed in battles;
we will never go to the place where the dead people are.

Isa 28:18 UDB I will cancel the covenant that you made with the place where the spirits of the dead go.
You thought that because of that covenant you would not be killed and you would not go there.

These two verses in the UDB seem to be taking two different interpretive paths for the phrases "covenant with death/agreement with Sheol."

In 28:15 it interprets it as having made a covenant with Egypt to ensure they do not die when the Assyrians attack.

28:18 interprets it more literally as if they made an actual covenant with death/sheol (which some commentators say it is possible they tried to make an agreement with the god of the underworld)

I will change the notes based on if you make any changes.

**Comment by TomWarren** [comment]
The UDB of ISA 28:14-15 was reworked:
\v 14 Listen to the word that Yahweh says, 
\q2 you who rule over the people of Jerusalem,
\q2 you who mock and make fun of me!
\q1
\v 15 You boast and say,
\q1 "We made a bargain with death to ensure that the power of death may not touch us,
\q2 and to be sure of our bargain, we also made an agreement with the spirits that control the place where the dead dwell. 
\q1 When the powerful armies comes to punish us for our sins, 
\q2 they will not touch us, and they will not punish us, 
\q2 because we trust in the lies we have told, and those lies make us safe; 
\q2 and our deceitful words will protect us because we put our trust in them.

UDB of ISA 28:18 now reads:
\v 18 I will cancel the covenant that you made with death,
\q2 and I will bring to an end the covenant you made with the place where the dead dwell. 
\q1 But when the vast army of Assyria comes like a flood, it will pour over you; 
\q2 they will defeat you and crush your army,
\q2 with their great numbers and mighty power they will trample over you and beat you into the dirt.  

ULB of ISA 28:14-25 now reads:
\v 14 So listen to the word of Yahweh, you who mock,
\q1 you who rule over this people who are in Jerusalem.
\q1
\v 15 This will happen because you said, "We have made a covenant with death;
\q1 with Sheol we have reached an agreement. So when the overflowing judgment passes through, it will not reach us,
\q1 for we have made a lie our refuge, and in falsehood we have taken shelter."

Thanks, TW
