### ISSUE TITLE
Isa 29:16 punctuation

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#354]
ULB You turn things upside down! Should the potter be considered like clay,
so that the thing that is made should say about him who made it, "He did not make me,"
or the thing formed say about him who formed it, **"He does not understand?"** 

Should the question mark be outside of the quotations? The person isn't asking if God understands, but this is the end of a long rhetorical question.

**Comment by TomWarren** [comment]
Moving question mark. The ULB of ISA 29:16 now reads:
\v 16 You turn things upside down! Should the potter be considered like clay,
\q1 so that the thing that is made should say about him who made it, "He did not make me,"
\q1 or the thing formed say about him who formed it, "He does not understand"?
