### ISSUE TITLE
Isa 30:18 "exalt" or "rise up"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#356]
ULB Therefore he will be exalted, ready to have mercy on you.

UDB he is great because he desires to act mercifully

I am having trouble with this text. The Hebrew word is "RUM." It can mean "exalt" or "rise up." It seems to me the two possible meanings are 1. Yahweh will exalt himself, that is, show himself to be great and have mercy on the people, or 2. Yahweh is rising up, that is, preparing to have mercy on the people.

But, it seems to me that the ULB and UDB are trying to squeeze in both meanings: he will show himself great and prepare/desire to have mercy on the people.

Does this seem right to you? I just wanted to check before I wrote a note.

**Comment by TomWarren** [comment]
The ULB of ISA 30:18 now reads: 
\v 18 Yet Yahweh is waiting to be gracious to you, therefore he is ready to show you mercy. 
\q1 For he is a God of justice—Yahweh most blessed, for all those who wait for him.
\q1

The UDB of ISA 30:18  now reads: 
\v 18 But Yahweh wants to act kindly toward you;
\q2 he is great because he desires to act mercifully.
\q1 Do not forget he is a God who acts justly;
\q2 Yahweh is pleased with those who patiently trust in him.
Hope that helps. 
TW
