### ISSUE TITLE
Isa 30:28  "lead into exile?"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#358]
UDB it is as though he will put horses' bridles on them and take them away into exile

I'm not sure this metaphor is specifically about leading people into exile. From the commentaries I've read, it means more generally that he leads them to their destruction or that he frustrates their plans.

**Comment by TomWarren** [comment]
The ULB now reads: 

\v 28 His breath is like an overflowing torrent that reaches up to the middle of the neck,
\q1 to sift the nations with the sieve of destruction. His breath is a bridle in the jaws of the peoples that leads them astray.

The UDB now reads::
\v 28 His breath is like a flood that covers his enemies up to their necks.
\q2 He will separate the nations in order to destroy some of them;
\q2 it is as though he will put horses' bridles on them so he can lead them away to destruction.

Hope that helps. 
TW

**Comment by TomWarren** [comment]
Re-saved the change to UDB.... must have not saved it until 12/3/2016
