### ISSUE TITLE
Isa 6:10 minds that are fat

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#367]
ULB Make the heart of this people calloused

UDB What you say will cause these people to become stubborn

I wonder if "stubborn" is the best interpretation of the Hebrew phrase "make their minds fat." I suppose stubbornness would be an effect of having a fat heart but from what I am reading it means more to make the people dull, lazy in their thinking, incapable of being decisive.  

What do you think?

**Comment by TomWarren** [comment]
The ULB of ISA 6:10 now reads:
\v 10 Make the heart of this people insensitive, and their ears dull, and blind their eyes.
\q1 Otherwise they might see with their eyes, hear with their ears, and understand with their heart, and then turn and be healed."

The UDB of ISA 6:10 now reads: 
\v 10 I will cause you people to be unable to care;
\q2 and what I say to you will cause you not to be able to hear me or even see what I have done.
\q1 And because of what I do to you, you will not see what it is that you need from me, because you must see and you must hear if you are to believe in me.
\q2 I have made this hard for you, otherwise you would come to me, and then you would care deeply about others, 
\q2 and you would turn to me so I might save you and not punish you."

Hope that helps, 
TW
