### ISSUE TITLE
Luk 8:13 ULB  translation of eisin

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#371]
Luke 8:13 The ones along the path **are** those who have heard,

Jim and I spoke about this sentence and others like it in Jesus' explanation of the seeds in this parable.
Could "are" be changed to "are connected with" or "are associated with"?
Could this be done throughout Jesus' explanation in Matthew, Mark, and Luke?

Could we talk about it on Skype?

**Comment by TomWarren** [comment]
Should we take a look at the suggestion "what happens to the seed ..." for the UDB?

**Comment by SusanQuigley** [comment]
I think that "What happens to the seed that ..." along with the UDB's "shows what happens when" could work well enough.

**Comment by TomWarren** [comment]
This section in the ULB has been edited to read according to our suggestions.
\v 11 Now, this is what the story means: The seeds represent God's word.
\v 12 The seeds that fell on the pathway show what happens when people hear God's word, but afterwards the devil comes and takes that word away from their minds and hearts. As a result, they do not believe it and are not saved.
\v 13 The seeds that fell on the rocky ground show what happens when people hear God's word and receive it joyfully, but they do not have deep roots. As a result, they only believe for a short time. As soon as difficult things happen to them, they stop believing God's word.

\s5
\v 14 The seeds that fell among the thorny plants show what happens when people hear God's word, but then as they go on in life they allow such things as the worries, riches and pleasures of this life to crowd out God's word from their life. As a result, they do not become spiritually mature.
\v 15 But the seeds that fell on the fertile ground show what happens when people hear God's word and receive it with an honorable and upright heart. They persevere in believing and obeying the word, and so they produce good spiritual fruit.

I say this can stand as written. Any other suggestions??
Thanks,
TW
