### ISSUE TITLE
Isa 6:9-10 quotation mark

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#378]
UDB I will cause you people to be unable to care;
            and what I say to you will cause you not to be able to hear me and even see what I have done.
        And because of what I do to you, you will not see what it is that you need from me, because you must see and you must hear if you are to believe in me.
            I have made this hard for you, otherwise you would come to me, and then you would care deeply about others,
            and you would turn to me so I might save you and not punish you

On a recent text change, you changed the UDB to first person. Is the "I" God speaking? Or, is it Isaiah as part of his message from the previous chunk. If it is still part of Isaiah's message that God wants him to speak, I think you need to move the quotation mark. As of right now the quotation ends in verse 9, making it seem like God is speaking in v. 10.

Personally, I think the quotation should end after verse 9, and keep the wording you have for verse 10 except put in second person like in the TFT.

**Comment by TomWarren** [comment]
Unpacking the passive voice in the UDB of ISA 6:9-10
This may be close. 
Thanks.

\v 9 Then he said,
\q1 "You will go and say to the people of Israel,
\q2 'Listen carefully to what I say, but you will not understand it.
\q1 You will look very carefully,
\q2 but you will not understand.'

\s5
\q1
\v 10 I will cause you people to be unable to care;
\q2 and I will cause you people to not be able to hear,
\q2 and I will cause you people to not be able to see.  
\q1 Otherwise you would see with your eyes and you would recognize what it is you are looking at,
\q2 and you would hear with your ears and be able to understand what you have heard,  
\q2 and you would care deeply and with understanding,
\q2 and you would turn to me so I might save you and not punish you."
