### ISSUE TITLE
Isa 6:9 ULB Quotation mark

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#379]
I think there needs to be single quotation marks around:

listen, but do not understand; see, but do not perceive.

**Comment by TomWarren** [comment]
The ULB of ISA 6:9 now reads:
\v 9 He said, "Go and tell this people,
\q1 'Listen, but do not understand; see, but do not perceive.'

\s5
\q1
\v 10 Make the heart of this people insensitive, and their ears dull, and blind their eyes.
\q1 Otherwise they might see with their eyes, hear with their ears, and understand with their heart, and then turn and be healed."
