### ISSUE TITLE
ISA 37:32

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#380]
Here's a phase 2 notes from Susan:

37:32 UDB Isaiah added, 
37:32 ULB The zeal of Yahweh of hosts will do this. (Outside of the quotes of what Yahweh said.)
Yahweh often speaks about himself in the third person. Could that not be the case here?

(Actually, there are a lot of places in prophecy where it's not clear who was actually speaking. Because we use punctuation, the text team had to make a decision either way. Here it looks like they chose to treat them as Isaiah's words to Hezekiah.)

**Comment by TomWarren** [comment]
The quotation marks have been made a bit more inclusive:
The UDB of ISA 37:31-32 now reads:
\v 31 You people who are still here in Judah,
\q2 will be strong and prosper again.
\q1
\v 32 A small number of my people will survive,
\q2 and they will spread out from Jerusalem.
\p That will happen because Yahweh, commander of the angel armies, is desiring very much to accomplish it."


The ULB of ISA 37:31-32 now reads:
\v 31 The remnant of the house of Judah that survives will again take root and bear fruit.
\q1
\v 32 For from Jerusalem a remnant will come out; from Mount Zion survivors will come.
\q1 The zeal of Yahweh of hosts will do this.'"

We have been including this phrase (and others like it) in most of the OT, where "this is the word of Yahweh" and the like is including in the quote from the mouth of Yahweh, rather than as an addition by the prophet.
