### ISSUE TITLE
LUK 17:21 "within you" vs "among you"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#386]
ULB the kingdom of God is **within you**.
UDB God has already begun to rule **among you**.

Jesus was talking to the hostile Pharisees. The UDB "among you" makes more sense than the ULB "within you." God's kingdom would hardly have been in their hearts and minds.

**Comment by TomWarren** [comment]
It doesn't seem to be about spatially, where the kingdom is, but where the kingdom begins, and so, within those who believe.
Probably, yes it is within them, and yes it is among them. The GRK ἐντὸς, is "inside/ or among", giving no resolution to the options.  The scholars are about equally divided on how to take this, as are the modern translations..
Probably best to keep "within you" and keep "among you" as an AT. 
The UDB now reads: 
\v 21 People will not be able to say, 'Look! He is ruling here!' Or 'He is ruling there!' because, contrary to what you think, God has already begun to rule within you."
