### ISSUE TITLE
LUK 1-5 

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#388]
We received the following from the oral recordings that may be _**confusing to a non-English speaker**._

1:22 But when he came out, he could not speak to them. They realized that he **had had** a vision while he was in the temple. He kept on making signs to them and remained silent. 

1:26 Now in **her (should it be - Elizabeth's)** sixth month, the angel Gabriel was sent from God to a city in Galilee named Nazareth, 

2:38 At that very hour, she came up to them and began **thanking, (missing an object)** and she spoke about the child to everyone who had been waiting for the redemption of Jerusalem. 
The TFT and UDB have 'God' as the object.

4:22 Everyone there witnessed what he said and all of them were amazed at the **gracious**  words which were coming out of his mouth. 
The TFT and UDB mention how well spoken his words were and the note refers to the alternate meaning of gracious as being well spoken.

4:24 But he said, "Truly I say to you, no prophet is **welcomed**  in his own hometown.
There is a question on the use of the past tense of welcome in this verse.

5:25 Immediately **he (who?)** got up in front of them and picked up the mat he was lying on. Then he went back to his house, glorifying God. 
The who is pretty clear to me - but the end-user seems confused.

@Wysackyprof

**Comment by TomWarren** [comment]
Dear Chris,

Here is the other set of suggestions, worked-through.

Thanks,


Tom


On 12/14/2016 10:00 AM, Chris Jarka wrote:
>
> We received the following from the oral recordings that may be 
> /*confusing to a non-English speaker*./
>
> 1:22 But when he came out, he could not speak to them. They realized 
> that he *had had* a vision while he was in the temple. He kept on 
> making signs to them and remained silent.
>
*\v 22 But when he came out, he could not speak to them. They realized 
that he had seen a vision while he was in the temple. He kept on making 
signs to them and remained silent.*
>
> 1:26 Now in *her (should it be - Elizabeth's)* sixth month, the angel 
> Gabriel was sent from God to a city in Galilee named Nazareth,
>
*\v 26 In the sixth month, the angel Gabriel was sent from God to a city 
in Galilee named Nazareth,**
**
**This is not changed because the supplied information is in the notes 
and in the UDB. *
>
> 2:38 At that very hour, she came up to them and began *thanking, 
> (missing an object)* and she spoke about the child to everyone who had 
> been waiting for the redemption of Jerusalem.
> The TFT and UDB have 'God' as the object.
>
*\v 38 At that very hour, she came up to them and began to give thanks 
to God and she spoke about the child to everyone who had been waiting 
for the redemption of Jerusalem.**
**
**This verse has been corrected, (to God was already added) and they 
must be using an older version*
>
> 4:22 Everyone there witnessed what he said and all of them were amazed 
> at the *gracious* words which were coming out of his mouth.
> The TFT and UDB mention how well spoken his words were and the note 
> refers to the alternate meaning of gracious as being well spoken.
>

\v 22 Everyone there witnessed what he said and all of them were amazed 
at the gracious words which were coming out of his mouth. They were 
saying, "This is Joseph's son, is it not?"

The GREEK χάριτος is the same as the word for "grace" χάρις, the meaning 
goes from graciousness, attractiveness, charm, favor, helpful, filled 
with thanks and beauty. So the interpretation is not to be limited to 
what the TFT and the UDB have. There should be an opportunity to use the 
translation Notes (and certainly not the TFT).
>
> 4:24 But he said, "Truly I say to you, no prophet is *welcomed* in his 
> own hometown.
> There is a question on the use of the past tense of welcome in this verse.
>
\v 24 But he said, "Truly I say to you, no prophet is welcome in his own 
hometown.

The GRK has "welcome (a noun) is (the present active verb of 'to be'), 
so "is welcome" is best.

> 5:25 Immediately *he (who?)* got up in front of them and picked up the 
> mat he was lying on. Then he went back to his house, glorifying God.
> The who is pretty clear to me - but the end-user seems confused.
>
The context is clear, it is the man who is picking up his mat. Should be 
clear that this isn't Jesus, but the man who was just healed.
Some training on finding the context would help, and to use. There is a 
tN on this issue.
