### ISSUE TITLE
Isa 52:15 startle or sprinkle

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#393]
At least I have a new verse for you this time :)

ULB  my servant will sprinkle
UDB he will surprise

Looking at the past revisions of this chunk, it looks like the ULB originally said "startle." Then Jim wrote a translation note saying saying "startle" could be translated as "sprinkle." Then, at some later point, the ULB text was changed to "sprinkle" but the UDB was left as "surprise." So, we need to make them agree, but I don't know which option is best.

Most English versions go with "sprinkle," but a few go with "startle." John Oswalt in his commentary argues for "startle" because it parallels with what was stated in the previous verse.

I will write the note based on your decision.

**Comment by TomWarren** [comment]
The preference is for "spatter" or "sprinkle." Following the UBS handbook, the UDB of ISA 52:15 now reads:

\v 15 But he will purify the people of many nations by sprinkling them clean;
\q2 even kings will be silent when they stand in front of him,
\q1 because they will see someone that no one had told them about before,
\q2 and they will understand things that they had not heard about before.

The ULB is unchanged, and it reads:
\v 15 And so, my servant will sprinkle many nations and kings will shut their mouths because of him.
\q1 For that which they had not been told, they will see, and that which they had not heard, they will understand.

Thanks,

TW
