### ISSUE TITLE
REV 3:1 Usage of quotation marks

### ISSUE THREAD

**Issue by eCyclops** [Door43/ulb-en#394]
In John 3, when John is writing the words of Jesus to the churches, quotation marks are used at every conceivable level, resulting in a lot of quotation marks. In comparing two other literal-trending translations (the ESV and NASB) I found that they used quotes in the same places, but each chose two of the quote levels to use — neither used all three.

This is a usage issue, and therefore open to some interpretation, but Help Desk was contacted, so I'm opening the issue.

**Comment by TomWarren** [comment]
This ISSUE seems to be referenced to  REV 3. ...
The system of quotation marks used here is the same system used throughout (most of) the ULB.  This system is not considered by some to be a standard way of forming levels of quotation, but we hope it serves to identify the speaker/writer. 

Our system does not comply with the Chicago Style Manual or other systems for quotations, but it is  simple, and, we hope, consistent.  There are three-level quotations here in Rev 3:  (1) John speaking, (2) what he is writing to the church, and (3) what was said by the "the one who holds the seven stars". 
This system may be a bit complex at first, but it preserves to clearly identify who is speaking/writing.  
Not to say that we always got it right, but here in Rev, and in Jer (among others) this system attempts to identify the speaker or writer in a consistent way, and we believe and do truly hope that this quotation system may be of help to the reader. The point would be that the translator should be consistent when dealing with multilevel quotations.
We do find that many people have other systems of quotation that they were taught, and that, accordingly, they prefer. This system is simple and straightforward, and we hope it helps the reader. 
It could be noted that other modern versions avoid the third level by using the colon as the beginning of an new level of quotation; we used the quote along with the colon (for clarity).  There are cases in the OT that we use the colon alone without the quotation, as a level of quotation.
Thank you for asking. 
Tom Warren
