### ISSUE TITLE
Num 6:9 "his separated person"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#399]
ULB If someone very suddenly dies beside him and **defiles his separated person**

Previously a manager wrote a note expressing how awkward this sentence is, but it was not sent to you. Now a proofreader is sending it back to p2edit for the same reason. Would you take a look at it and see if there is a better way to translate this? Thanks.

Aaron left this note which may be helpful: 

 **defiles his separated person (ULB)**

This phrase needs a note, but I think that the text complicates things. The Hebrew is “defiles his consecrated head” with “head” functioning as metonymy for hair, which, in turn, symbolizes the vow. I'm not sure how to write a note to that effect without complicating things further.

Would it be better for the text to read “head” or “hair” (as UDB), or even “body”?

**Comment by TomWarren** [comment]
The ULB of NUM 6:9 now reads: 
\v 9 If someone very suddenly dies beside him and defiles his consecrated head, then he must shave his head on the day of his purification—on the seventh day he must shave it.
 
This may be a remnant of another project to translate consecrated or set apart. Your suggestion "consecrated body" follows most modern versions, and it can stand. The previous rendering seemed unnatural. Shaving the head was a way of being "set apart" after one had been defiled, but was not the locus of the defilement, which was external to the one who was "consecrated," caused by the unexpected death (that caused uncleanness.

Hope that helps. Thanks.
