### ISSUE TITLE
ISA 51:22 comma

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#402]
Your Lord Yahweh your God,..... (beginning of the verse)

I believe you need a comma here somewhere...

**Comment by TomWarren** [comment]
The UDB of ISA 51:22 now reads:
\v 22 Your Lord Yahweh, who is your God, he is the one who pleads the cause of his people, and he says this,
\q1 "See, I have taken the cup from your hand that caused you to stagger—
\q1 the bowl of the cup of my anger—so that you will not drink it again.

Thanks very much!
TW
