### ISSUE TITLE
Deu  11:16-17 punctuation

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#418]
ULB 16Pay attention to **yourselves, so** that your heart is not deceived, and you turn aside and worship other **gods, and** bow down to them; 17so that the anger of Yahweh is not kindled against **you, and** so that he does not shut up the **heavens, so** that there will be no rain, and the land will not yield its fruit, and so that you perish quickly from off the good land that Yahweh is giving you.

Proofreader's suggested punctuation changes:

Pay attention to **yourselves so that** your heart is not deceived, and you turn aside and worship other **gods and** bow down to them; so that the anger of Yahweh is not kindled against **you; and** so that he does not shut up the **heavens so** that there will be no rain, and the land will not yield its fruit, and so that you perish quickly from off the good land that Yahweh is giving you.

**Comment by TomWarren** [comment]
Good suggestions. Deut has a lot of punctuation carry-overs from the ASV. 

The ULB of DEU 11:17 now reads:
\v 17 so that the anger of Yahweh is not kindled against you; and so that he does not shut up the heavens so that there will be no rain, and the land will not yield its fruit, and so that you perish quickly from off the good land that Yahweh is giving you.
