### ISSUE TITLE
Luke 21:34, 35 ULB extra "like/as a trap"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#430]
ULB:  will close on you suddenly **like a trap. 35as a trap.** For  it will come upon everyone

Suggestions:
will close on you suddenly _like a trap_. **35** For it will come upon everyone
or 
 will _come_ upon you suddenly. **35** For _like a trap_ it will _close_ on everyone

**Comment by TomWarren** [comment]
Most adjust the Greek TXT to keep the phrase "like a trap" ὡς  παγίς· with verse 34. Seems to make the most sense. 

The ULB of LUK 21:34-35 now read: 

\v 34 But pay attention to yourselves, so that your hearts are not burdened with too much drinking, drunkenness, and the worries of life, and then that day will close on you suddenly like a trap. 
\v 35 For it will come upon everyone living on the face of the whole earth.
