### ISSUE TITLE
Jos 11:20 "they cried out for mercy"? and spelling error

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#434]
UDB Yahweh caused the people in all those other groups to be stubborn, with the result that they fought against the Israelite army, and the Israelites killed them all. **They cried out for mercy but were not heard,** so that they might **be complete** destroyed. This is what Yahweh had commanded Moses to do.

A comment was made by a reviewer and a proof reader about "They cried out for mercy but were not heard." I thought you may want to take a look at it. Here are their comments.

> Their pleas for mercy were not heard - this seems to be a bit generous for a literal translation. No version at http://biblehub.com/joshua/11-20.htm gives any hint that the people in fact cried out for mercy, though the implication is that if they had cried out, it would have done no good. The force of the text seems rather to be that the Israelites went into battle fully intending to kill all of the victims no matter what the latter did or said, and they in fact did what they intended to do. 

> P2Review - I am wondering about the issue raised by Henry above. The UDB reads "they cried out for mercy but were not heard" but there is no hint of this in the ULB. Is this going to cause confusion? 

Also, notice that "be complete" should be "be completely"

**Comment by TomWarren** [comment]
I reworked the ULB along with the UDB here. 
The ULB at JOS 11:20 now reads:
\v 20 For it was Yahweh who hardened their hearts so they would wage war against Israel, so that he might completely destroy them without mercy, just as he had instructed Moses.
The UDB at JOS 11:20 now reads: 
\v 20 Yahweh caused the people in all those other groups to be stubborn, with the result that they fought against the Israelite army, and so God used the Israelite army to destroy them all. God did not hold back the Israelite army from totally destroying their enemies. This is what Yahweh had commanded Moses to do.
