### ISSUE TITLE
1Ki 17:2, 5 Cherith or Kerith

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#436]
In 1 Kings 17:2 and 17:5 the ULB has Cherith, but the UDB has Kerith.

**Comment by TomWarren** [comment]
This may be a bit of a carry-over from the ASV, but continuity is now preserved. 

UDB 1KI 17:2 now reads:
\v 3 "Because you have made the king angry with you, escape from the king and, go to the east, to the **Cherith** Brook, east of where it flows into the Jordan River.

17:5 now reads:
\v 5 So Elijah did what Yahweh commanded him to do. He went and camped alongside **Cherith** Brook.
