### ISSUE TITLE
1ki 17:15 add "for"?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#437]
ULB and her boy ate many days

Would it be clearer to say "ate for many days"?

**Comment by TomWarren** [comment]
THe ULB of 1KI 17:15 was worked on. There are some textual issues here that most subsume under the categorical nouns. 
It now reads:
\v 15 So she did as Elijah had told her. And she, the boy, and her household ate for many days.

"the boy" is used to distinguish the "he" from Elijah.

Thanks, 
TW

**Comment by TomWarren** [comment]
וַתֵּ֥לֶךְ וַתַּעֲשֶׂ֖ה כִּדְבַ֣ר אֵלִיָּ֑הוּ וַתֹּ֧אכַל *הוּא־ *וָהִיא **הִֽיא־**וָה֛וּא וּבֵיתָ֖הּ יָמִֽים׃ .

Here is the HEB text.

**Comment by jhutchins25** [comment]
https://door43.org/en/bible/notes/1ki/17/14

I added notes. I tried to cover all the options. Does this look clear to you?

**Comment by TomWarren** [comment]
John, your translationNote is a good statement of the challenges in this verse. The interpretive question revolves around "should Elijah be included or not?" But the weight of the verse seems to be on the miracle of providing food for the woman and her household. Whatever way the verse is rendered (vis a vis Elijah), that seems to be the prominent point.
I have asked Perry Oakes and Jim Pohlig to take a look at this ISSUE and see if they have other suggestions. From where I sit, it looks fine. 
Thanks, 
TW

**Comment by pjoakes** [comment]
Tom,

All of the versions I looked at that specify the “he” take it to be Elijah. That is the nearest antecedent, and the “household” would naturally include the son. So I think the ULB is fine as it is.

Except for starting the sentence with “And.” That is an issue we may need to discuss, since it affects all of the ULB. It isn’t good English, and isn’t necessary.

Could the note indicate that the original reads as stated? Do we refer to Hebrew in the Notes? The reason that many versions use only pronouns is because the original did. Also, it isn’t unclear who ate, it is only unclear to whom the pronouns specifically refer. The Note says:

And she and Elijah, along with her household, ate for many days - Many versions of the Bible translate this as "And she and he and her household ate for many days." It is unclear who all ate for many days. Possible meanings are 1) Elijah, the widow, and her son ate for many days or 2) the widow, her son, and everyone living in her house ate for many days or 3) Elijah, the widow, and everyone living in her house ate for many days.

I would rewrite it as:

She and Elijah, along with her household, ate for many days - The original Hebrew does not use any names here: "And she and he and her household ate for many days." It is unclear exactly who “he and her household” refer to. Possible meanings are 1) Elijah and everyone living in her house (including her son), or 2) her son, and everyone living in her house (including Elijah).

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jan 11, 2017, at 9:24 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


John, your translationNote is a good statement of the challenges in this verse. The interpretive question revolves around "should Elijah be included or not?" But the weight of the verse seems to be on the miracle of providing food for the woman and her household. Whatever way the verse is rendered (vis a vis Elijah), that seems to be the prominent point.
I have asked Perry Oakes and Jim Pohlig to take a look at this ISSUE and see if they have other suggestions. From where I sit, it looks fine.
Thanks,
TW

**Comment by jhutchins25** [comment]
I agree that the question isn't so much who ate, but who "he" is. But, typically in the notes we avoid phrases like "In the original language" or "In the Hebrew." One way to get around this is if we want to change the ULB to "he and she and her household ate for many days." Then I can write in the notes that it is unclear who "he" is.

**Comment by TomWarren** [comment]
The And ... has been removed. The ULB of 1KI 17:15 now reads:
\v 15 So she did as Elijah had told her. She and Elijah, along with her household, ate for many days.

**Comment by TomWarren** [comment]
That sounds good, John. And Thanks Perry,

Will close this out. 
TW
