### ISSUE TITLE
Eph 3:23 the old man?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#440]
ULB **It is your old man that Christ** makes new in the spirit of your mind. 

I don't think this part about the old man being made new is right.
V22 says to put off the old man.
V24 says to put on the new man.

Could this simply say the following?
Be made new in the spirt of your mind
or (if we want to make it explicit that Christ makes us new, the maybe )
Allow Christ to make you new in the spirit of your mind.

**Comment by TomWarren** [comment]
This is EPH 4:23

The shortened sentences make it difficult. Re-connecting 23 and 24 makes it more understandable.

ULB EPH 4:23-24 now reads:
\v 22 You were taught to put off what belongs to your former manner of life, to put off the old man. It is the old man that is corrupt because of its deceitful desires.
\s5
\v 23 You were taught to be renewed in the spirit of your minds, 
\v 24 and to put on the new man that is created in the image of God—in true righteousness and holiness.

Hope that is clearer. 
Thanks,
TW

**Comment by SusanQuigley** [comment]
Tom, this change is not showing up yet in USFM or Door43.

**Comment by TomWarren** [comment]
It was synced about an hour ago,  from GitHub History: 

\v 20 But that is not how you learned about Christ.
\v 21 I assume that you have heard about him, and that you were taught in him, as the truth is in Jesus.
\v 22 You were taught to put off what belongs to your former manner of life, to put off the old man. It is the old man that is corrupt because of its deceitful desires.

**Comment by TomWarren** [comment]
It's in Door43 Wiki ...

**Comment by TomWarren** [comment]
It seems to have something to do when I make 10 or more changes to GitHub at one time.

**Comment by SusanQuigley** [comment]
I see it now. Thank you.
