### ISSUE TITLE
2KI 22:6-7

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#442]
ULB 6Let them give money to the carpenters, the builders, and the masons, and also to buy timber and cut stone to repair the **temple." 7But** no accounting was required for the money that was given to them, because they handled it faithfully.

UDB 6They must give that money to the carpenters, the builders, and the masons, and they should also buy the timber and the stones that they will use to repair the temple. 7But the men who supervise the work will not be required to make a report on the money that is given to them, saying what they spent it for, because those men are completely **honest."**

The ULB and UDB end the quotation in different places.

**Comment by TomWarren** [comment]
In the UDB of 2KI 22:6-7, I moved the quotation mark to the end of vs 6. 
It now reads:
\v 6 They must give that money to the carpenters, the builders, and the masons, and they should also buy the timber and the stones that they will use to repair the temple."
\v 7 But the men who supervise the work will not be required to make a report on the money that is given to them, saying what they spent it for, because those men are completely honest.
