### ISSUE TITLE
DEU 8:12 incomplete sentence

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#447]
ULB 12Be careful that, when you eat and are full, and when you build good houses and live in them.

In the ULB, the sentence in v 12 is an incomplete sentence. Maybe it should either be ended with a comma instead of a period (and v 13 in the next chunk should start with a lower case), or removing "that," in :12.

**Comment by TomWarren** [comment]
The long sentence carries over several chunks in Heb. So some phrases need to be supplied so that there is continuity across the chunk (see "your heart will be lifted up" is supplied in Vs 12). "Do not forget him"  is supplied at the beginning of  Vs 15. 
 
The ULB of DEU 8:11-17 now reads:

\v 11 Be careful that you do not forget Yahweh your God, and that you do not neglect his commandments, his ordinances, and his statutes that I am commanding you today,
\v 12 otherwise, when you eat and are full, and when you build good houses and live in them, your heart will be lifted up.

\s5
\v 13 And be careful when your herds and flocks multiply and when your silver and gold increase, and all that you have is multiplied,
\v 14 then your heart will be lifted up, and you forget Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage.

\s5
\v 15 Do not forget him who led you through the great and terrifying wilderness, with its fiery serpents and scorpions and thirsty ground where there was no water, who brought you water out of the rock of flint.
v 16 He fed you in the wilderness with manna that your ancestors had never known, so that he might humble you and test you, to do you good in the end,
\v 17 but you may say in your heart, 'My power and the might of my hand acquired all this wealth.'
