### ISSUE TITLE
1ki 16:12  Remove extra clause with passive?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#463]
**as was told them** by the word of Yahweh, which he had spoken against Baasha by Jehu the prophet,

This has two speech verbs "was told them" and "he had spoken"?
Hebrew has only one, but the ULB passive and the word "them" seem to complicate things. 
Could it be something like this?
according to the word of Yahweh that he had spoken against Baasha by Jehu the prophet.
OR
according to the word  that Yahweh spoke against Baasha by Jehu the prophet

**Comment by TomWarren** [comment]
The ULB of 1KI 16:12-13 now reads:

\v 12 So Zimri destroyed all the family of Baasha, according to the the word of Yahweh which he spoke against Baasha by Jehu the prophet,
\v 13 for all the sins of Baasha and the sins of Elah his son that they committed, and by which they had led Israel to sin, so that they provoked Yahweh the God of Israel to anger with their idols.

Vs 13 was also reviewed. 

Thanks,

TW
