### ISSUE TITLE
1SA 9:23-24

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#465]
The ULB has: 23 Samuel said to the cook, "Bring the portion which I gave to you, of which I said to you, 'Put it aside.'" 24 So the cook **took the thigh that had been raised in sacrifice and what was with it**, and set it before Saul. Then Samuel said, "See what has been kept for you. Eat it, because it has been kept until the appointed time for you. For now you can say, 'I have invited the people.'" So Saul ate with Samuel that day.

The proofreader has this following statement about 'being raised in sacrifice' 

Why does the UDB say "even though those portions were for only the priest to eat"? This statement does not seem to be in the original text. Why does the ULB say "the thigh that had been raised in sacrifice"? This statement does not seem to be in the original text. Furthermore, if both thighs are raised in sacrifice, shouldn't it be "one of the thighs that had been raised in sacrifice"? If only one thigh (the right one) is raised in sacrifice, why does the ULB think the thigh presented to Saul is not the left one?

**Comment by TomWarren** [comment]
**The ULB of 1SA 9:24 now reads:
\v 24 So the cook took up the thigh and what was on it and set it before Saul. Then Samuel said, "See what has been kept is set before you. Eat it, because it has been kept for you until the appointed time, from the time when I said, 'I have invited the people.'" So Saul ate with Samuel that day.**

**The UDB of 1SA 9:24 now reads:
\v 24 So the cook brought the leg and the meat that was on it; he set it in front of Saul. Samuel said to Saul, "Start eating it. I told the cook to save this for you, so that you could eat it at this time, when all these people whom I invited are here." So Saul and Samuel ate together.**

Why does the UDB say "even though those portions were for only the priest to eat"? This statement does not seem to be in the original text. 

**This section ("even though those portions were for only the priest to eat") was removed from the UDB.** It is, however, true that the meat was set apart only for the priests (this would be a note in the text, and would not be required in the UDB). 

Why does the ULB say "the thigh that had been raised in sacrifice"? This statement does not seem to be in the original text. 
**The text was reviewed and the phrase "the thigh that had been raised in sacrifice" is more accurately translated, 

"the cook took up the thigh and what was on it"  וַיָּ֣רֶם הַ֠טַּבָּח אֶת־הַשּׁ֨וֹק וְהֶעָלֶ֜יהָ** 

Furthermore, if both thighs are raised in sacrifice, shouldn't it be "one of the thighs that had been raised in sacrifice"? If only one thigh (the right one) is raised in sacrifice, why does the ULB think the thigh presented to Saul is not the left one?

**There is mention of only one thigh here, and it would be conjecture to postulate about the other thigh.  It could be (if postulating is permitted) that one thigh would have been sufficient.** 

Thank you.

TW
