### ISSUE TITLE
2ki 15:16 ULB Tiphsah vs UDB Tappuah

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#469]
ULB: Then Menahem attacked **Tiphsah**
UDB: he completely destroyed **the city of Tappuah south of Samaria** 

ULB and UDB have different cities - the ULB from the MT and the UDB from a Greek version.

Do you want them to be the same?
Would you want me to ignore these things since modern translations have these variations and they don't have any theological significance?

**Comment by TomWarren** [comment]
Another case where the MT should be followed where there is a 50/50 split and a "C" ranking from the UBS Text Committee.

The ULB of 2KI 15:16 now reads without change:
\v 16 Then Menahem attacked Tiphsah and all who were there, and the borders around Tirzah, because they did not open up the city to him. So he attacked it, and he ripped open all the pregnant women in that village.

The UDB of 2KI 15:16 has been changed to read:
\v 16 At that time Menahem completely destroyed the city of Tiphsah and killed all the people who lived there and in the surrounding territory from Tirzah on. He did that because the people in the city refused to surrender to him. With his sword he even ripped open the bellies of pregnant women who lived there.

Here is a long text note from UBS Handbook:
“Tiphsah,” and therefore, gives only a {C} rating to the MT. Since Jeroboam II extended the border of Israel to the north (2 Kgs 14.28), it is possible, though not likely, that the city of Tiphsah on the Euphrates River is intended. It is also possible that Tiphsah here refers to a town in Israel whose location is unknown today. The Hebrew words translated and its territory from Tirzah on further complicate the understanding of the geography of the text if “Tiphsah” is adopted and is understood as referring to the town of that name on the Euphrates River. These words are taken by GNT|prj:GNT92.2KI.15.16 and NAB as indicating that Menahem detoured to the south plundering Tappuah on his way to Samaria. This understanding would be highly unlikely if the original text had “Tiphsah.” So the two problems have to be dealt with together. On the other hand, it seems very doubtful that the original writer meant to say “he destroyed it [Tiphsah] and all the surrounding towns as far as Tirzah” (CEV|prj:CEVR06.2KI.15.16), since the two towns are more than 450 kilometers (280 miles) apart. If “Tiphsah” is adopted, then the interpretation of from Tirzah found in NIV|prj:NIV84.2KI.15.16 seems more likely. The first half of the verse in NIV|prj:NIV84.2KI.15.16 reads “At that time Menahem, starting out from Tirzah, attacked Tiphsah and everyone in the city and its vicinity.” The possibility also exists, of course, that there was another place called “Tiphsah,” whose existence and location is unknown today, a place that was much nearer to Tirzah and Samaria. If this position is adopted, translators should probably add a footnote to explain that the better known city of Tiphsah on the Euphrates River is not intended. They did not open it to him is literally “he opened not.” The subject of the third person singular verb in Hebrew here probably refers to Menahem, who did not open the gates of the city, that is, he did not persuade the city's inhabitants to surrender. Others take the third person singular verb to refer to the city itself, saying “it had not opened its gates to him” (REB|prj:REB89.2KI.15.16, NJB, FRCL|prj:FCL97.2KI.15.16, OSTY; similarly NBS|prj:NBS02.2KI.15.16, SEM) or “it did not surrender” (NJPSV|prj:NJPS85.2KI.15.16). The third person singular verb may also be understood as the impersonal plural “they.” NAB offers a possible model with “they did not let him in.” In any case, the meaning seems to be that the people in the city refused to open their gates and allow the conquering army to enter and take complete control. He ripped up all the women in it who were with child: See the comments at 2 Kgs 8.12. The writer continues with an account of the next ruler in the northern kingdom. Menahem took power from Shallum by force in the same way that Shallum had seized control of the kingdom from Zechariah. But the reign of Menahem lasted much longer than that of Shallum. He ruled for ten years during 746–737 B.C. Menahem seized the throne at a time when the northern kingdom was in turmoil and Assyria was again expanding under Tiglath Pileser III (see verse 29). Menahem, as well as his son Pekahiah (verses 23-26), was willing to submit to Assyrian dominance. The suggested heading is “King Menahem of Israel.”
