### ISSUE TITLE
2SA 1:12 missing phrase in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#478]
ULB They mourned, wept, and fasted until evening for Saul, for Jonathan his son, for the people of Yahweh, and for the house of Israel 

The UDB mentions Saul and Jonathan, but does not have anything about people of Yahweh/house of Israel, which in the notes I explain probably refers to the Israelite soldiers.

**Comment by TomWarren** [comment]
The UDB of 2SA 1:11-12 was revised broadly, it now reads:

\v 11 Then David took hold of his clothing and he tore them apart, and all the men who were with him tore their clothes apart as well.
\v 12 They tore their clothing because they were very sad and they refused to eat anything until evening because they remembered that Saul and his son Jonathan had died, and that so many of the people of Yahweh had died, and they were sad because of the great dangers the descendants of Israel had gone through, and because so many of them died in battle.

**Comment by pjoakes** [comment]
It seems to me that “clothing” is a collective singular, so the pronoun should be “it,” not “them.”

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jan 26, 2017, at 9:26 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The UDB of 2SA 1:11-12 was revised broadly, it now reads:

\v 11 Then David took hold of his clothing and he tore them apart, and all the men who were with him tore their clothes apart as well.
\v 12 They tore their clothing because they were very sad and they refused to eat anything until evening because they remembered that Saul and his son Jonathan had died, and that so many of the people of Yahweh had died, and they were sad because of the great dangers the descendants of Israel had gone through, and because so many of them died in battle.

**Comment by TomWarren** [comment]
The UDB of 2SA 1:11-12 now read:
\v 11 Then David took hold of his clothing and he tore it apart, and all the men who were with him tore their clothes apart as well.
\v 12 They tore their clothing because they were very sad and they refused to eat anything until evening because they remembered that Saul and his son Jonathan had died, and that so many of the people of Yahweh had died, and they were sad because of the great dangers the descendants of Israel had gone through, and because so many of them died in battle.
