### ISSUE TITLE
Verses Not Found

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#48]
- [ ] Verse not found, 1 Chron 8:27
- [ ] Invalid verse number, Zechariah 4:15
- [ ] Invalid verse number, Zechariah 4:16

The last two are 'extra' verses not found in some manuscripts. There is no footnote.

**Comment by TomWarren** [comment]
The verses in Zechariah appear to be missing, but they are numbered with an alternative method. All the text is present, but there are more verse breaks (leading up to 16 verses) instead of having only 14 verses (as the ESV and the NIV have).  
I would request that the verses be renumbered to follow the NIV (as we have stated in our guidelines) and this follows more of the modern translations.
If this is approved (by Jim Pohlig and other), the Text Team can effect the changes. This would affect the Notes Pages for this section, not the content, but the verse numbers.
If there is a compelling reason to renumber these verses to the larger number of verses (16 vss), I would go with that, but it would seem to be less confusing to have our Version to be the same as other modern Versions. 
Let me know what the decision is. 
Tom Warren

**Comment by TomWarren** [comment]
1 Chronicles 8:27 was missing the verse marker "\v 27" possibly when the formatting of the chapter took place. 
The verse number is now restored. 
Please do not close until the Zechariah 4 matter has been resolved. 
Thanks, Tom Warren

**Comment by ChrisJarka** [comment]
The extra verses in Zechariah is causing issues with the tS  @program. This needs to be fixed or the 'extra' verses will not show in the program.

**Comment by TomWarren** [comment]
I can change them to the normal rendering found in the NIV and ESV. This would leave the count at 14 verses for this chapter. 
The Notes team might take a look at matches with the notes and the text.

**Comment by TomWarren** [comment]
I have reordered Zech 4:6-14 to follow the NIV.

NOTE: 
The TN  chunk has the last chunk as Zech 4:14-16 (vss 15 and 16 do not exist any more)
There is a figure of speech has been retained "olive trees" and this should be examined in the TN.

The last two chunks need to be changed to: 
A.  The next-to-last to Zech 4:12-13
B.  The last to Zech 4:14.
