### ISSUE TITLE
2KI 10:28 added metonymy

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#485]
"That is how Jehu destroyed Baal and removed its worship from Israel."

Here "Baal" is a metonymy for the worship of Baal, yet in the translation here "the worship of Baal" is made explicit and "Baal" is left as well, which leads us to ask what is Baal also a metonym for? That leads us to his temple. Which is not necessary an incorrect interpretation if "Baal" originally stood for a larger spread of his worship and his temple... but it seems this is not the best interpretation. Perhaps go with either "destroyed Baal" or "destroyed the worship of Baal" --both is probably not the best option as the Hebrew does not have a conj. here and two items.

**Comment by TomWarren** [comment]
The context helps (vss 26 and 27), when taking the previous verses about the eradication of the sites of worship of Baal. Most modern translations have "worship of Baal" in vs 27 and this would be best for the MTT here.  A note about the text that the Hebrew has simply "destroyed Baal", but this account is about destroying the places where Baal was worshipped. In a sense the non-existence of the pagan deities, according to all the prophets, would support the reality that Baal was something that could not be destroyed in the first place because he was not real or living. The worship of Baal could be destroyed, by removing his symbols and places of worship, but because Baal was not a real or true deity, he could not be "destroyed" because he never existed. The Hebrew Lexicon, Brown, Driver and Briggs, has:

On the definition of (destroying) שׁמד:
acc. ‎‏אֶת־הַבַּעַל‎, of extirpating Baal-worship. This would support our rendering as follows.

The ULB of 2KI 10:28 now reads:
\v 28 That is how Jehu destroyed Baal worship in Israel.
