### ISSUE TITLE
Ezr 6:6 ULB  "beyond the River"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#490]
6:6 ULB Now Tattenai, Shethar Bozenai, and your fellow officials who are **beyond the River**
Should "River" be "river"?

Hmmm.
5:3 ULB Then Tattenai the governor of the province **Beyond the River,** 
Is "Beyond the River" the name of the province? 
If so that perhaps 6:6 should be something like this:
 Now Tattenai, Shethar Bozenai, and your fellow officials who are  **in Beyond the River Province**

This phrase occurs 10 times in Ezra.

**Comment by TomWarren** [comment]
Henry and Jim P and I talked about this, with Henry to report.

**Comment by hmw3** [comment]
I think Tom and I agree that the biggest problem will be for gateway languages that do not use capitalization to indicate proper names. We have the common-noun prepositional phrase "beyond the river," the proper name prepositional phrase "beyond the River," meaning specifically land areas west of the Euphrates River as seen from Persia, and the proper name "the Province beyond the River" or "Beyond the River Province" or "Beyond the [Euphrates] River Province."
Unless we can change the decree from Mt. Olympus that the tW situation is henceforth immutable, we need to do whatever we do with tNs, probably a standard note. There are 73 occurrences of the phrase "the [Rr]iver" (singular only), most of which obviously aren't relevant to our discussion. The ones for sure relevant are below. I would suggest that someone write a standard note, check all occurrences of the phrase, and make sure the tNs for the relevant chunk include the idea in the standard note to this effect:
The {speaker / writer } intended the {hearer / reader} to understand the words "the River" to refer to the Euphrates River. Your language may require you to make this explicit. AT: "the Euphrates River."
I don't know if another note for "Province beyond the River" or however it is rendered is required.
I'm happy to do the dog work once a clear policy has been determined.

C:\Users\wthom_000\Desktop\GitHub\ulb-en\15-EZR\05.usfm (1 hit)
 Line 10: \v 3 Then Tattenai the governor of the province Beyond the River, Shethar Bozenai, and their companions came and said to them, "Who gave you a decree to build this house and complete these walls?"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\15-EZR\06.usfm (2 hits)
 Line 16: \v 6 Now Tattenai, Shethar Bozenai, and your fellow officials who are beyond the River, keep away.
 Line 20: \v 8 I am ordering that you must do this for these Jewish elders who build this house of God: Funds from the king's tribute beyond the River will be used to pay these men so they do not have to stop their work.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\15-EZR\07.usfm (2 hits)
 Line 40: \v 21 I, King Artaxerxes, make a decree to all the treasurers beyond the River, that anything that Ezra asks from you should be given in full,
 Line 48: \v 25 Ezra, with the wisdom that God has given you, you must appoint judges and discerning men to serve all the people beyond the River, and to serve anyone who knows the law of your God. You must also teach those who do not know the law.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\15-EZR\08.usfm (1 hit)
 Line 73: \v 36 Then they gave the king's decrees to the king's high officials and the governors beyond the River, and they helped the people and God's house."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\16-NEH\02.usfm (2 hits)
 Line 18: \v 7 Then I said to the king, "If it pleases the king, may letters be given to me for the governors beyond the River, so that they may permit me to pass through their territories on my way to Judah.
 Line 23: \v 9 I came to the governors beyond the River, and gave them the king's letters. Now the king had sent with me officers of the army and horsemen.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\16-NEH\03.usfm (1 hit)
 Line 15: \v 7 Next to them Melatiah the Gibeonite and Jadon the Meronothite, who were men from Gibeon and Mizpah, made repairs on the portion where the governor of the province Beyond the River lived.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\36-ZEP\03.usfm (1 hit)
 Line 49: \v 10 From beyond the river of Ethiopia my worshipers—my scattered people—will bring offerings due me.

**Comment by TomWarren** [comment]
The Province Beyond the River is used in three instances. 
Usually, and we hope in every case, the RIver is used when referring to the Euphrates. Other generic rivers would be LC.

**Comment by TomWarren** [comment]
The governors of the River or the phrase, Beyond the River, would be simply "beyond the River."

**Comment by SusanQuigley** [comment]
How about if I ask Andrew to add links to the page for Euphrates River, and perhaps even add "the River" as part of the title to that page?

**Comment by SusanQuigley** [comment]
Ezra 4:11 This is a copy of the letter that they sent to Artaxerxes: "Your servants, men **across the river,** write this: 

Should this be "beyond the River"?

**Comment by hmw3** [comment]
Whoever asks Andrew to make changes has to be higher up the totem pole than I am. I feel funny sending my sister into battle :-) , but I hereby bless you as you go!

**Comment by SusanQuigley** [comment]
I'll simply ask. He can say yes or no, or he can ask whoever is above him.
Thanks for the blessing.   :)

**Comment by TomWarren** [comment]
The HEB was "region beyond the river, and for consistency, this phrase is now in these ULB verses:
The Changes are in Bold. (with some exceptions)

Tom Warren

Looks like this:
\v 11 This is a copy of the letter that they sent to Artaxerxes: "Your servants, men of the Province Beyond the River, write this:

The rest are (from the ESV) 

EZR 4:10 - and the rest of the nations whom the great and noble Osnappar deported and settled in the cities of Samaria and in the rest of the province Beyond the River. 
**\v 10 and they were joined by the people whom the great and noble Ashurbanipal forced to settle in Samaria, along with the rest who were in the Province Beyond the River.**

EZR 4:11 - (This is a copy of the letter that they sent.) “To Artaxerxes the king: Your servants, the men of the province Beyond the River, send greeting. And now 
**ULB \v 11 This is a copy of the letter that they sent to Artaxerxes: "Your servants, men of the Province Beyond the River, write this:**

EZR 4:16 - We make known to the king that if this city is rebuilt and its walls finished, you will then have no possession in the province Beyond the River.” 
**ULB: \v 16 We are informing the king that if this city and wall are built, then there will be nothing remaining for you in the Province Beyond the River."**

EZR 4:17 - The king sent an answer: “To Rehum the commander and Shimshai the scribe and the rest of their associates who live in Samaria and in the rest of the province Beyond the River, greeting. And now 
**\v 17 So the king sent out a reply to Rehum and Shimshai and their companions in Samaria and the rest who were in the Province Beyond the River: "May peace be yours.**

EZR 4:20 - And mighty kings have been over Jerusalem, who ruled over the whole province Beyond the River, to whom tribute, custom, and toll were paid. 
ULB \v 20 Mighty kings have ruled over Jerusalem and had power over everything in the Province Beyond the River. Tribute and taxes were paid to them.

EZR 5:3 - At the same time Tattenai the governor of the province Beyond the River and Shethar-bozenai and their associates came to them and spoke to them thus, “Who gave you a decree to build this house and to finish this structure?” 
\v 3 Then Tattenai the governor of the Province Beyond the River, Shethar Bozenai, and their companions came and said to them, "Who gave you a decree to build this house and complete these walls?"

EZR 5:6 - This is a copy of the letter that Tattenai the governor of the province Beyond the River and Shethar-bozenai and his associates the governors who were in the province Beyond the River sent to Darius the king. 
**\v 6 This was the letter of Tattenai, governor of the Province Beyond the River, and Shethar Bozenai and his their fellow officials in the Province Beyond the River was sent to Darius the king.** (THIS WAS OMITTING SOME INFO)

EZR 6:6 - “Now therefore, Tattenai, governor of the province Beyond the River, Shethar-bozenai, and your associates the governors who are in the province Beyond the River, keep away. 
**\v 6 This was the letter of Tattenai, governor of the Province Beyond the River, and Shethar Bozenai and his their fellow officials in the Province Beyond the River was sent to Darius the king.**

EZR 6:13 - Then, according to the word sent by Darius the king, Tattenai, the governor of the province Beyond the River, Shethar-bozenai, and their associates did with all diligence what Darius the king had ordered. 
**\v 13 Then because of the decree sent by Darius the king, Tattenai, the governor of the Province Beyond the River, and Shethar Bozenai and his companions did everything that King Darius had ordered.**

EZR 7:21 - “And I, Artaxerxes the king, make a decree to all the treasurers in the province Beyond the River: Whatever Ezra the priest, the scribe of the Law of the God of heaven, requires of you, let it be done with all diligence, 
**ULB \v 21 I, King Artaxerxes, make a decree to all the treasurers in the Province Beyond the River, that anything that Ezra asks from you should be given in full,**

EZR 7:25 - “And you, Ezra, according to the wisdom of your God that is in your hand, appoint magistrates and judges who may judge all the people in the province Beyond the River, all such as know the laws of your God. And those who do not know them, you shall teach. 
**ULV \v 25 Ezra, with the wisdom that God has given you, you must appoint judges and discerning men to serve all the people in the Province Beyond the River, and to serve anyone who knows the law of your God. You must also teach those who do not know the law.**

EZR 8:36 - They also delivered the king's commissions to the king's satraps and to the governors of the province Beyond the River, and they aided the people and the house of God. 
**ULB \v 36 Then they gave the king's decrees to the king's high officials and the governors in the Province Beyond the River, and they helped the people and God's house."**

NEH 2:7 - And I said to the king, “If it pleases the king, let letters be given me to the governors of the province Beyond the River, that they may let me pass through until I come to Judah, 
ULB **\v 7 Then I said to the king, "If it pleases the king, may letters be given to me for the governors in the Province Beyond the River, so that they may permit me to pass through their territories on my way to Judah.**

NEH 2:9 - Then I came to the governors of the province Beyond the River and gave them the king's letters. Now the king had sent with me officers of the army and horsemen. 
**ULB \v 9 I came to the governors in the Province Beyond the River, and gave them the king's letters. Now the king had sent with me officers of the army and horsemen.**

NEH 3:7 - And next to them repaired Melatiah the Gibeonite and Jadon the Meronothite, the men of Gibeon and of Mizpah, the seat of the governor of the province Beyond the River. 
ULB **\v 7 Next to them Melatiah the Gibeonite and Jadon the Meronothite, who were men from Gibeon and Mizpah, made repairs on the portion where the governor of the Province Beyond the River lived.**

**Comment by SusanQuigley** [comment]
Henry, you suggested writing a standard note for "the Province Beyond the River." Here are the two notes I wrote for it.

https://door43.org/en/bible/notes/ezr/04/09
**the Province Beyond the River** - This is the name of the province that was west of the Euphrates River. It was across the river from the city of Susa. (See: How to Translate Names)

The first time it occurs in Ezra 5, 6, 7, and 8:
**the Province Beyond the River** - This is the name of the province that was west of the Euphrates River. It was across the river from the city of Susa. See how you translated it in 4:10. (See: How to Translate Names)

**Comment by hmw3** [comment]
Yup, they'll do the job. Go ahead and plug them in where they belong, and I'll look at my chunks once the issue has been closed. Thanks!

**Comment by SusanQuigley** [comment]
I put them in Ezra 4:9, 5:3, 6:6, 7:21, and 8:35. 
I also put the first in New 2:7 and I wrote to Kim about Nehemiah 3:6.

I guess we can close this?

**Comment by TomWarren** [comment]
What about all those other references that I listed above? 
There were changes from many of the readings, to now read Province Beyond the River. 
Just curious.

**Comment by hmw3** [comment]
I's doin' th' dog work. Woof, woof!

**Comment by SusanQuigley** [comment]
I didn't bother because I thought we only need a note  the first time it comes up in each chapter, and when it hasn't been in any recent chunks.

**Comment by hmw3** [comment]
Dogs aren't quite so sophisticated.

________________________________

**Comment by TomWarren** [comment]
That's fine, I know when I get pulled in five directions, it is easy to miss something that was put on a chat. 
Thanks so much for working through this. I appreciate your good work and in this. 
Tom
