### ISSUE TITLE
1TH 2.11-12 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#492]
11In the same way, you know how with each one of you, as a father with his own children, we exhorted and encouraged you. We testified 12that you should walk in a manner that is worthy of God, who calls you into his own kingdom and glory.

Is the verse marker for verse 12 in the correct spot? 

ESV -  11For you know how, like a father with his children, 12we exhorted each one of you and encouraged you and charged you to walk in a manner worthy of God, who calls you into his own kingdom and glory.

NIV - 11For you know that we dealt with each of you as a father deals with his own children, 12encouraging, comforting and urging you to live lives worthy of God, who calls you into his kingdom and glory.

ASV -  10Ye are witnesses, and God also , how holily and righteously and unblameably we behaved ourselves toward you that believe: 11as ye know how we dealt with each one of you, as a father with his own children, exhorting you, and encouraging you , and testifying, 12to the end that ye should walk worthily of God, who calleth you into his own kingdom and glory.

**Comment by TomWarren** [comment]
Restored the longer sentence for more logical connection and easier on the verse numbers. There was an additional phrase that was not in the GK in vs 11 that had been moved to vs 12, that was restored to its proper place in the ULB:

The ULB of 1TH 2:11-12 now reads:

\v 11 For you know that we dealt with each one of you as a father deals with his own children, 
\v 12  encouraging and comforting you so that you should walk in a manner that is worthy of God, who calls you into his own kingdom and glory.

Thanks, 
Tom Warren
