### ISSUE TITLE
Ezra 8:2-14  List format?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#520]
In both the ULB and UDB this list shows up in the USFM file as one big paragraph, except that the USFM file has lines separating the chunks. It also shows up on each chunk as a paragraph. 

Could it be formatted so that it looks like a list?

**Comment by TomWarren** [comment]
Jim Pohlig and I talked about this. We removed the \li formatting from the ULB some time back (last year) because the formatting was inconsistent throughout, and it was simpler to keep with the paragraph. The UDB often (not always) using \li formatting for lists, but not in this instance. 

So keep the list as paragraphs, for now. 

Thanks,

Tom (for Jim, too).

**Comment by SusanQuigley** [comment]
Thanks for checking into it.
