### ISSUE TITLE
NEH 5:18 typo

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#522]
"Now what was prepared each day was one ox, six choice sheep, and also birds, and every ten days all kind of wine in abundance...."

*all kinds

**Comment by TomWarren** [comment]
The ULB NEH of 5:18, 

\v 18 Now what was prepared each day was one ox, six choice sheep, and also birds, and every ten days all kinds of wine in abundance. And yet for all this I did not demand the food allowance of the governor, because the demands were too heavy on the people.

Thanks, Kim. Good eye!

Tom
