### ISSUE TITLE
Isa 28:9 Who is being ridiculed?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#523]
ULB To whom will he teach knowledge

UDB They ridicule Yahweh and say

Most commentaries that I have read say they are ridiculing Isaiah and not Yahweh. But, several English versions translate "he" as the Lord.

Do you think the UDB text should be changed to match the commentaries, or should we leave as is and I can put in a "Possible Meaning" notes?

Thanks.

**Comment by TomWarren** [comment]
The plan, generally, is that the meaning of the two versions are close, but the way in which they express the meaning may differ. 

The UDB of ISA 28:9 now reads:
\v 9 Who will he teach so that they can learn about knowledge?
\q2 Who will listen to him so that he can teach lessons to them so they can learn?
\q1 Does he think that we are like little children who no longer drink milk,
\q2 and that we are like babies who, not long ago, were weaned?


Thanks,

Tom
