### ISSUE TITLE
Isa 28:15, 17 UDB does not agree with itself

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#525]
ULB 28:15 We have made a covenant with death; with Sheol we have reached an agreement.

There is debate about the meaning of this. Some say the leaders literally tried to make a covenant with god of death and Sheol through sorcery. Some say this is a metaphor for making an alliance with Egypt. The UDB offers different interpretation on different chunks. 

UDB v15 -We made a bargain with death to ensure that the power of death may not touch us,
and to be sure of our bargain, we also made an agreement with the powers that control the place where the spirits of the dead dwell.

UDB v17  But because your agreement with Egypt to protect you was made by leaders lying to each other and deceiving each other,

I have not looked through the whole chapter to see what the other chunks have, but I think we should make them all agree on the interpretation. 

Thanks.

**Comment by jhutchins25** [comment]
I just noticed this in 28:18 UDB

I will cancel the covenant that you made with death, and I will bring to an end the covenant you made with the place where the dead dwell.

So this agrees with v 15 but not v 17.

**Comment by TomWarren** [comment]
It may not always be clear what a metaphor is pointing to. Sometimes, like here, it may be required only to translate the metaphor as clearly as we can. 
The attempt of the UDB supplies far too much conjecture to be helpful. Also metaphors are everywhere in this section .

The ULB of ISA 28:15 now reads:
\v 15 This will happen because you said, "We have made a covenant with death,
\q1 and with Sheol we have reached an agreement. So when the overwhelming whip passes through, it will not reach us.
\q1 For we have made a lie our refuge, and taken shelter in falsehood."

The UDB of ISA 28:15 now reads:
\v 15 You boast and say,
\q1 "We made a promise with death to make ourselves safe from the power of death, when it passes over us, so that it cannot get to us.
\q2 We tried to turn our lying words into a shelter in which we could hide. 

UDB ISA 28: 17 now reads:
\v 17 I will test you people of Jerusalem to find out if you will act justly and righteously,
\q2 I will measure your character like a carpenter uses a plumb line to determine if a wall is straight and level.
\q1 And then the hail will fall! And it will destroy everything you have.   
\q2 Your shelter will be destroyed because it is built on a foundation of lies,
\q2 and the water from the storm will wash your shelter away.

UDB ISA 28:18-19
\v 18 I will cancel the covenant that you made with death,
\q2 and I will bring to an end the covenant you made with the place where the dead dwell. 
\q1 But when the huge flood comes, it will pour over you; 
\q2 and day after day it will pass over you, destroying everything.

\q1
\v 19 When the flood comes, it will pass through and over you like the river when it overflows its banks and causes flooding everywhere. 
\q1 When you finally understand the message of Yahweh, it will cause you to be terrified, and not comforted.


Look this over. I did this rather quickly, so errors wouldn't surprise. 
Thanks,

Tom
