### ISSUE TITLE
Isa 38:10 Rhetorical question in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#528]
ULB "I said that halfway through my life
I will go through the gates of Sheol; I am sent there for the rest of my years. 

UDB I said to myself, "Is it necessary for me to die and go to the place where the dead people are
    during this time of my life when I am still strong?
    Is Yahweh going to rob me of the remaining years that I should live?"

I don't think I have seen this situation before where the ULB has a statement and the UDB has a question.

It seems most commentaries and English Bibles go with a statement. My question is whether the question in the UDB is rhetorical or not.

If it is, then normally the rhetorical question is in the ULB and the statement is in the UDB.

If it is a true question, should both UDB and ULB have a question so that they agree?

Thanks

**Comment by TomWarren** [comment]
THere are times when the UDB will pose a statement in the form of a rhetorical question.  Here, it seems more of a linguistic exercise than a quest for clarity. It would require that the ULB be rephrased to match the ULB. The direction should be what is in the ULB is reflected, more simply or with the metaphors and figures explained, rather than forming the rhetorical question from the statement. Just seems too complex for the MTT to follow what is going on. There is certainly no need for the RQ in the UDB. 
It is interesting to note that the NIV has the RQ:
NIV84  (ALONE)   I said, “In the prime of my life must I go through the gates of death and be robbed of the rest of my years?” Perhaps that is the genesis of the UDB?

The statement seems much clearer:

The UDB of ISA 38:9-11 now reads:
\v 9 When King Hezekiah was almost well again, he wrote this:
\q1
\v 10 I said to myself, "In the middle of my life I am about to walk through the gates of death, and Yahweh is taking from me the rest of my years. 
\q1
\v 11 I said, "I will not see Yahweh again
\q2 in this world where people are alive.
\q1 I will not see my friends again,
\q2 or be with others who now are alive in this world.

Hope that helps, 
Tom
