### ISSUE TITLE
isa 28:27 "Cumin" or "Caraway"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#530]
ULB Moreover, the cumin is not threshed

According to the Hebrew here "cumin" should be "caraway" as in the UDB.

**Comment by TomWarren** [comment]
The ULB is wrestling with the two words that represent nearly the same spice, קֶצַח caraway seed, and כַּמֹּן  which is transliterated into cumin. The ULB now has caraway ... cumin consistently through this section. and that can stand. And, it would seem that the terms were confused. Here they are straightened out

UDB will be changed (making the renderings made consistent) to:

\v 25 No, he makes the ground very level,
\q2 and then he plants seeds—
\q2 caraway seed and cumin and wheat and barley.
\q1 He plants each kind of seed in the correct manner. He does not plant one kind of seed in the way that is not right for it.
\q1
\v 26 He does that because God has taught him the correct way to do it.

\s5
\q1
\v 27 Also, farmers never thresh caraway seed with a heavy sledge;
\q2 instead, they beat it only with a stick.
\q1 Farmers never thresh cumin by driving a cart over it;
\q2 instead, they only hit it with a rod.

The ULB of ISA 28:25-27 now reads:

\v 25 When he has prepared the ground, does he not scatter caraway seed, sow the cumin,
\q1 put in the wheat in rows and the barley in the right place, and the spelt at its edges?
\f + \ft The identification of some of these spices is in doubt, so versions have a variety of translations. In addition, some versions give different interpretations to the expressions translated here as \fqa in rows \fqb and \fqa in the right place \fqb , because these expressions are uncertain in Hebrew. \f*
\q1
\v 26 His God instructs him; he teaches him wisely.

\s5
\q1
\v 27 Moreover, the caraway seed is not threshed with a sledge, 
\q1 nor is a cartwheel rolled over the cumin;
\q1 but caraway is beaten with a stick, and cumin with a rod.
\q1

Thanks, 

Tom
