### ISSUE TITLE
Isa 51:21 change tense?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#533]
UDB But in truth, it is not because you have drunk out of a cup filled with wine, but because of something else **that Yahweh will do.** 

This is tricky because God is talking about something that will happen in the future as if it were in the past. 

Everything in the UDB is in the past tense except the phrase "that Yahweh will do." Should it be "that Yahweh did" or the future perfect "that Yahweh will have done"?

**Comment by TomWarren** [comment]
The UDB has been edited down quite a bit. The UDB of ISA 51:21 now reads:

\v 22 Yahweh, your Lord and your God,
\q2 the one who argues your case to defend you, he says this:
\q1 "I have away taken that cup that holds my anger toward you, 
\q1 and I made you experience my anger when I made you drink from that cup. 
\q1 But now I have taken it from you so that you will never drink of it again.
