### ISSUE TITLE
Isa 51:22 "bowl of the cup" ?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#534]
ULB the bowl of the cup of my anger

I think this is a little awkward. Hebrew has the same word for "cup" as used in in "cup of staggering" but it adds another word (qubbaat). I suppose that is where "bowl" is coming from, but most English versions combine into one word like "cup" or "goblet."

What do you think?

**Comment by TomWarren** [comment]
I think this Hebraism can stand. It is a way of keeping the Heb sense of "the cup of the cup" better to say the bowl of the cup. I made it a bit less awkward while trying to preserve both terms:
The ULB of ISA 51:22 now reads:

\v 22 Your Lord Yahweh, your God, who pleads the cause of his people, says this,
\q1 "See, I have taken the cup of staggering from your hand—
\q1 the bowl, which is the cup of my anger—so that you will not drink it again.
