### ISSUE TITLE
LUK 12:35, 37 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#537]
\v 35 Let your long **_clothing be tucked in at your belt, and_** let your lamps be kept burning,

\v 37 Blessed are those servants, whom the master will find watching when he comes. Truly I say to you, **_he will dress himself for work,_** and have them sit down at the table, and he will come and serve them.

The reader thinks there should be some consistency.  They wrote: _Let your long clothing be tucked in at your belt is changed in verse 37 to dress himself for work while the same phrase in verse 35 is not changed. There is need for consistency._

**Comment by TomWarren** [comment]
The ULB of LUK 12:35-37 now reads: 
\v 35 Let **your long clothing be tucked in at your belt**, and let your lamps be kept burning,
\v 36 and be like people looking for their master when he returns from the marriage feast, so that when he comes and knocks, they may immediately open the door for him.

\s5
\v 37 Blessed are those servants, whom the master will find watching when he comes. Truly I say to you, h**e will tuck in his long clothing at his belt**, and have them sit down at the table, and he will come and serve them.

Thanks,

Tom
