### ISSUE TITLE
Heb 11:11 ULB & UDB Abraham or Sarah?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#542]
ULB: It was by faith, even though Sarah herself was barren, that **Abraham received power to conceive**. This happened even though **he was too old**, since **they considered** as faithful the one who had given them a promise.

UDB: Because **Abraham trusted** God to **give him strength, he was able to produce** a son. Even though his wife Sarah was beyond the time when women bear children, God promised he would give her a son, and **Abraham believed** that God would do what he promised to do. 

Most versions have Sarah as the subject of _katabolen_, _elaben_, and _hegesato_. 
NIV and NRSV are the exceptions.
If most people will have access to versions that have Sarah as the subject, would it be good for the ULB and UDB to do the same? Or would it be good to have a footnote? Or should we handle this in the notes?  (I realize that katabolen usually has a man as the subject.)

Also ULB and UDB differ as to who was too old.

**Comment by TomWarren** [comment]
There is a difficult textual issue here. If we follow the "C" reading in the recent Greek text, it would suggest that we add a footnote about the difficulties of this verse. 
The ULB with Footnote, of HEB 11:11 now reads: 
\v 11 It was by faith, even though Sarah herself was barren, that Abraham received ability to father a child. This happened even though he was too old, since he considered as faithful the one who had given the promise.
\f + \ft There is some question about whether it was Abraham's faith or Sarah's faith that was in view. \fqa By faith Sarah, though she was old, received the power to have a child, even though she was too old to bear a child, since she considered the one who gave the promise to be faithful. \f*

Look that over. 

Tom

**Comment by SusanQuigley** [comment]
This looks good, except that the UDB does not match the ULB. Instead it matches the footnote.

Also typo in UDB: 
she received the ability to **conceive,ecause** she considered Yahweh to be faithful

**Comment by TomWarren** [comment]
The UDB now matches the ULB. Sorry for the delay...

The UDB of HEB 11:11 now reads:
\v 11 And even though Sarah was unable to have children because of her old-age, Abraham received the ability to father a child, because he considered Yahweh to be faithful because he had made the promise to him that he would have a son.

Hope that cleans it up. Thanks
Tom

**Comment by SusanQuigley** [comment]
Looks good. Thank you.
