### ISSUE TITLE
MAT 12:27

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#555]
\v 26 If Satan drives out Satan, he is divided against himself. How will his kingdom stand?
\v 27 And if I drive out demons by Beelzebul,  _by **whom do your followers drive** them out?_  Because of this, they will be your judges.

From the field:
Here in Brazília, we have a group doing Level 2 checking. It was brought to my attention in Matthew 12:27 that the ULB in Eng translated this way 27 And if I drive out demons by Beelzebul, by whom do your followers drive them out?

The question is with the word “**followers**.” In the Greek, the word is “**sons**” and in most Bible versions. I believe it should be translated “sons.” Would you please check on this for me.

**Comment by TomWarren** [comment]
The Greek has "your sons" and it is a Semitism for those who follow a teacher. Here, the followers of the Pharisees. I added a Note about the expression. The UDB would have "disciples". Followers would work, but the Greek is "your sons" - the Greek is  οἱ  υἱοὶ  ὑμῶν - "the sons of yours."

The ULB of MAT 12:27 now reads: 
\v 27 And if I drive out demons by Beelzebul, by whom do your sons drive them out? Because of this? For this reason they will be your judges. 

This points not to the disciples of Jesus, but the sons of the Pharisees, and not the disciples of Jesus. 
The Note Reads:
  * **your sons** "Your sons" refers to the followers of the Pharisees, see MAT 12:24. The phrase "your sons" is a typical way of referring those in a group who follow teachers or leaders.
