### ISSUE TITLE
Heb 8:3 ULB  Missing "a"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#563]
They serve as *  copy and shadow of the heavenly things.

Should the word "a" be where I put the asterisk?

**Comment by TomWarren** [comment]
For clarity most versions supply the implied words "the tabernacle" or "the sanctuary", and so that has been added:
The ULB of HEB 8:3 now reads:
\v 5 They serve in a tabernacle that is a copy and shadow of the heavenly things. It is just as Moses was warned by God when he was about to construct the tabernacle: God said, "See that you make everything according to the pattern that was shown to you on the mountain."

Thanks, 
TW
