### ISSUE TITLE
Act 28:27  Delete "not"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#564]
Otherwise they might **not** see with their eyes,

Should "not" be deleted?

**Comment by TomWarren** [comment]
The entirety of ULB 28:27 was checked, and several changes were made:

\v 27 For the heart of this people has become dull,
\q and with their ears they hardly hear,
\q and they have shut their eyes.
\q Otherwise they might see with their eyes,
\q and hear with their ears,
\q and understand with their heart and turn again,
\q and I would heal them."' 

Thanks,
TW
