### ISSUE TITLE
Pro 25:7 "him" or "them"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#571]
UDB It is better if **someone** tells you to sit closer to the king, than **for them** to tell you

The UDB translates the ambiguous "him" in the ULB as "someone," but it switches to the plural "than for them."

Do you think this would be confusing?

**Comment by TomWarren** [comment]
The UDB of PRO 25;7 now reads:
\v 7 It is better if someone important invites you, saying, "Come up and sit closer to the king,"
\q2 than to embarrass you in front of an important nobleman by making you move so that you now sit far away from the king. 

The ULB of PRO 25:7 now (with some edits) reads:
\v 7 It is better for him to say to you, "Come up here,"
\q than for him to humiliate you before a nobleman.

Hope that pulls them to the same point. 
Thanks, 
Tom
