### ISSUE TITLE
2 Ki 21:12 Different speaker

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#578]
ULB sin with his idols," 12therefore Yahweh, the God of Israel, says, "Look, I am about to bring

UDB by worshiping idols. 12Therefore, this is what I, Yahweh, the God whom you Israelite people worship, say: 'I will cause disaster

The ULB has "therefore Yahweh, the God of Israel, says" spoken by the prophet. The UDB has is as a part of God's speech.

**Comment by TomWarren** [comment]
The UDB and ULB are on the same page, I think. If you see something that needs tending, send it over. 
Thanks, John,

Tom 

The ULB of 2KI 21:10-15 now reads: 
\v 10 So Yahweh spoke by his servants the prophets, saying,
\v 11 "Because Manasseh king of Judah has done these disgusting things, and has acted wickedly more than all that the Amorites who were before him did, and has also made Judah sin with his idols,
\v 12 therefore Yahweh, the God of Israel, says this: Look, I am about to bring such evil on Jerusalem and Judah that whoever hears of it, both his ears will tingle.

\s5
\v 13 I will stretch over Jerusalem the measuring line used against Samaria, and the plumb line used against the house of Ahab; I will wipe Jerusalem clean, as a man wipes a dish, wiping it and turning it upside down.
\v 14 I will throw off the remnant of my inheritance and give them into the hand of their enemies. They will become victims and plunder for all their enemies,
\v 15 because they have done what is evil in my sight, and have provoked me to anger, since the day their ancestors came out of Egypt, to this day."

The UDB of 2KI 21:10-15 now reads: 
\v 10 These are some of the things that Yahweh said through his prophets. Many times Yahweh had given them these messages:
\v 11 "Manasseh, the king of Judah, has done these abominable things, things that are much worse than the things that the Amor people group did in this land long ago. He has lead the people of Judah to sin against Yahweh by worshiping the idols that he worshiped.
\v 12 Therefore, this is what I, Yahweh, the God whom you Israelite people worship, says to you: I am about to cause disaster to come to Jerusalem and the rest of Judah. It will be terrible, with the result that everyone who hears about it will be stunned.

\s5
\v 13 I will judge and punish the people of Jerusalem as I punished the family of King Ahab of Israel. I will remove the people of Jerusalem as people wipe a plate clean and then turn it upside down to show that they are now satisfied.
\v 14 And I will abandon the people who remain alive, and I will allow their enemies to conquer them and steal everything valuable from their land.
\v 15 I will do this because my people have done things that I say are very evil, things which have caused me to become very angry. They have caused me to become angry continually, ever since the time that their ancestors left Egypt."

Hope that helps.
