### ISSUE TITLE
Exo 2:9  Dittography in ULB?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#606]
**9**So the land of Egypt will become desolate and a ruin. Then they will know that I am Yahweh, because the sea monster had said, "The river is mine, for I have made it." **9**So the land of Egypt will become desolate and a ruin. Then they will know that I am Yahweh, because the sea monster had said, "The river is mine, for I have made it." 

Verse 9 shows up twice.

**Comment by TomWarren** [comment]
The ULB of EXO 2:8-10 now reads:
\v 8 Therefore the Lord Yahweh says this: Behold! I will bring a sword against you. I will cut off both man and beast from you.
\v 9 So the land of Egypt will become desolate and a ruin. Then they will know that I am Yahweh, because the sea monster had said, "The river is mine, for I have made it."
\v 10 Therefore, behold! I am against you and against your river, so I will give the land of Egypt over to desolation and waste, and you will become a wasteland from the Migdol to Syene and the borders of Cush.
