### ISSUE TITLE
Ezk 31:14 clouds or foliage

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#607]
ULB so that they would not raise their tree tops above the foliage

UDB or lift its top above the branches of other trees

This same phrase occurs in 31:3 and 31:10. But in those verses the Hebrew word "abot" is translated as "clouds" rather than  "foliage."

It looks like most modern versions except NIV translates it as "clouds." Do you want change 31:14 so it is consistent?

**Comment by TomWarren** [comment]
The UDB of EZK 31:3 now reads: 

\v 3 You think that your country is as great as Assyria was.
\q2 Well, Assyria was like a tall cedar tree in Lebanon;
\q1 it had big beautiful branches
\q2 that provided shade for other trees in the forest.
\q1 It was very tall;
\q2 and the branches of the tallest trees made a treetop that was a roof over the forest.

The ULB of EZK 31:3 now reads: 

\v 3 Behold! Assyria was a cedar in Lebanon with beautiful branches, giving shade to the forest, 
\q and the tallest in height, and the branches formed its treetop. 

The HEB is אֶת־צַמַּרְתָּם֙, tree-top (esp of cedar, of tall trees generally (BDB). Other renderings seem very conjectural. 
The ULB of EZK 31:13-14 now reads:
 
\v 13 All the birds of the sky rested on the trunk of the fallen tree,
\q and every animal of the field came to its branches.
\p
\v 14 This happened so that no other trees that grow by the waters will lift up their foliage to the height of the tallest trees, and that no other trees that grow beside the waters will reach up to that height. All of them have been assigned to death, to the earth below, among the children of humanity, with those that go down to the pit.

Some of the extraneous material in the UDB was removed.
The UDB of EZK 31:13-14 now reads: 
\v 13 Birds of the sky settled on the fallen tree, and wild animals lived among its branches. 
\v 14 As a result, no other tree, even if the tree has plenty of water, will ever grow to such great height, or lift its top above the branches higher than other trees. They will all certainly die and decay, they will go to the place of the dead, and they will go to the grave.'"

Thanks,

Tom

**Comment by jhutchins25** [comment]
Do you want to change Ezk 31:10 as well which says "and set its top among
the clouds" (ULB)

John

**Comment by pjoakes** [comment]
It seems that the last sentence of UDB Ez 31:14 should have two semi-colons (deleting the “and”) like this:

They will all certainly die and decay; they will go to the place of the dead; and they will go to the grave.'"

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>





On Mar 1, 2017, at 7:45 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The UDB of EZK 31:3 now reads:

\v 3 You think that your country is as great as Assyria was.
\q2 Well, Assyria was like a tall cedar tree in Lebanon;
\q1 it had big beautiful branches
\q2 that provided shade for other trees in the forest.
\q1 It was very tall;
\q2 and the branches of the tallest trees made a treetop that was a roof over the forest.

The ULB of EZK 31:3 now reads:

\v 3 Behold! Assyria was a cedar in Lebanon with beautiful branches, giving shade to the forest,
\q and the tallest in height, and the branches formed its treetop.

The HEB is אֶת־צַמַּרְתָּם֙, tree-top (esp of cedar, of tall trees generally (BDB). Other renderings seem very conjectural.
The ULB of EZK 31:13-14 now reads:

\v 13 All the birds of the sky rested on the trunk of the fallen tree,
\q and every animal of the field came to its branches.
\p
\v 14 This happened so that no other trees that grow by the waters will lift up their foliage to the height of the tallest trees, and that no other trees that grow beside the waters will reach up to that height. All of them have been assigned to death, to the earth below, among the children of humanity, with those that go down to the pit.

Some of the extraneous material in the UDB was removed.
The UDB of EZK 31:13-14 now reads:
\v 13 Birds of the sky settled on the fallen tree, and wild animals lived among its branches.
\v 14 As a result, no other tree, even if the tree has plenty of water, will ever grow to such great height, or lift its top above the branches higher than other trees. They will all certainly die and decay, they will go to the place of the dead, and they will go to the grave.'"

Thanks,

Tom

**Comment by TomWarren** [comment]
Yep, just keep popping up ... 
The ULB of EZK 31:10 now reads: 
\v 10 Therefore the Lord Yahweh says this: Because it was tall in height, and it set its treetop between its branches, it lifted up its heart because of its height.

Note that I changed the him to "it" (as before). Note about "lifted up its heart" = pride. 


Thanks,
Tom

**Comment by TomWarren** [comment]
Perry's read is right:
Here is the UDB of EZK 31:14: 
\v 14 As a result, no other tree, even if the tree has plenty of water, will ever grow to such great height, or lift its top above the branches higher than other trees. They will all certainly die and decay; they will go to the place of the dead, and they will go to the grave.'"

**Comment by TomWarren** [comment]
We had tried to remove most of the semicolons in the UDB, but they are needed at times.

**Comment by pjoakes** [comment]
I’m reading that last sentence as 3 independent clauses, so 2 semi-colons without the “and.” The “and” implies that the place of the dead and the grave are two different places, but I don’t think that was the idea.

They will all certainly die and decay; they will go to the place of the dead; and they will go to the grave.’"

If you don’t want semi-colons in the UDB, they could be short sentences.

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>





On Mar 1, 2017, at 8:39 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Perry's read is right:
Here is the UDB of EZK 31:14:
\v 14 As a result, no other tree, even if the tree has plenty of water, will ever grow to such great height, or lift its top above the branches higher than other trees. They will all certainly die and decay; they will go to the place of the dead, and they will go to the grave.'"

**Comment by TomWarren** [comment]
I think it is is ok. There is a stacking of the kinds of judgment, one upon another, that seems to be better with the serial statements, still linked within the sentence by the semicolons. 
It can stand.
Thanks, 
Tom
