### ISSUE TITLE
Act 15:24 ULB  Leftover "Since"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#612]
Acts 15:24 ULB: **Since** we have heard that certain men have gone out from us, with no orders from us, and disturbed you with teachings that upset your souls. **25**So it seemed good to all of us

I think the word "Since" should be deleted.

**Comment by TomWarren** [comment]
The Greek text begins with Ἐπειδὴ, which is "Since." 
The culprit was the beginning of Vs 25. There is a price for cutting these long sentences down. Sometimes they don't make sense. I think it makes sense now. 

Try this:
The ULB of ACT 15:24-26 now reads: 
\v 24 Since we have heard that certain men have gone out from us, with no orders from us, and disturbed you with teachings that upset your souls,
\v 25 so all of us agreed to choose men and send them to you along with our beloved Barnabas and Paul,
\v 26 men who have risked their lives for the name of our Lord Jesus Christ.

Test that one. 

Thanks,

Tom

**Comment by SusanQuigley** [comment]
We don't normally use both "Since" and "so" in one sentence in English. Could one of them be deleted?
If "Since" is deleted, we could have two shorter sentences. (We have heard .... So all of us agreed ...)
If "so" is deleted, we would have one long sentence. (Since we have heard ..., all of us agreed ...)

I'm assuming that "Since" here is primarily marking a reason, not a time.
If the word "Since" is used, could the word "have" be deleted. "Since we heard ..."

**Comment by TomWarren** [comment]
Still think Since is a nice word. 
The ULB of ACT 15;24-2 now reads: 
\v 24 We have heard that certain men have gone out from us, with no orders from us, and have disturbed you with teachings that upset your souls.
\v 25 This being so, all of us have agreed to choose men and to send them to you along with our beloved Barnabas and Paul,
\v 26 men who have risked their lives for the name of our Lord Jesus Christ.

\s5
\v 27 Therefore we are sending Judas and Silas, who will tell you the same thing themselves in their own words.

That should be close. 

Thanks, 
Tom
