### ISSUE TITLE
EZK 23:44-45 typos

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#613]
Got your revisions, found a couple typos...

"went in to her" should be "went into her" 

"blood in on their hands" should be "blood on their hands"

**Comment by TomWarren** [comment]
That "in to" was problematic. I reworded it to avoid the suggestive part ... In to her, was וַיָּב֣וֹא   אֵלֶ֔יהָ "and they went in to her" that is what I was trying to preserve. Note the ESV has it just like that  "in to her" (but your eye is correct, how I'd phrased it was a bit off). 

Give a look at this:

The ULB of EZK 23:44-45 now reads:
\v 44 They went to her and slept with her as men go to be with a prostitute. In this way they slept with Oholah and Oholibah, who were immoral women.
\v 45 But righteous men will pass judgment and punish them as adulteresses, and they will punish them with the sentence for those who shed blood, because they are adulteresses and blood is on their hands.

Thanks for your good insights. Keep after me, especially when you see a mistake. Thanks Kim!

Tom
