### ISSUE TITLE
Ezk 30:21 ULB receive medicine?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#623]
ULB: "Son of man, I have broken the arm of Pharaoh, the king of Egypt. Behold! It is not bound up and **able to receive medicine**; no one can put a bandage on it, so it will not be strong enough to grasp a sword.
UDB: "Son of man, I have enabled the army of Nebuchadnezzar to defeat the army of the king of Egypt. It is as though I have broken one of the arms of the king of Egypt, and it has not been bandaged **in order that it could be healed,** and it has not been put in splints in order that after it heals the arm will be strong enough to hold a sword.

Could "receive medicine" be changed to something like "to receive healing" or "to be healed"? This is a broken arm, not simply a wound.

**Comment by TomWarren** [comment]
The ULB of EZK 30:21 now reads:
\v 21 "Son of man, I have broken the arm of Pharaoh, the king of Egypt. Behold! It is not been bound up, to heal it by setting it with a bandage, so that it will become strong enough to hold a sword.

Thanks,

Tom

**Comment by pjoakes** [comment]
Some fixing is needed in the phrase below:

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>





On Mar 7, 2017, at 9:28 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The ULB of EZK 30:21 now reads:
\v 21 "Son of man, I have broken the arm of Pharaoh, the king of Egypt. Behold! It is not been bound up, to heal it by setting it with a bandage, so that it will become strong enough to hold a sword.

Thanks,

Tom

**Comment by TomWarren** [comment]
The ULB of EZK 30:21 now reads:
\v 21 "Son of man, I have broken the arm of Pharaoh, the king of Egypt. Behold! It has not been bound up, or set to heal with a bandage, so that it will become strong enough to grasp a sword.

There it is.

**Comment by TomWarren** [comment]
Best to make specific suggestions, or it may be difficult to discern what needs attention. 
Thanks
