### ISSUE TITLE
Jer 2:24  longing for life and panting after the useless wind!

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#638]
ULB: You are a wild donkey, accustomed to the wilderness, **longing for life and panting after the useless wind!**
UDB: You are like wild female donkeys in the desert. They sniff the air to find where the male donkeys are,

The ULB's  **longing for life and panting after the useless wind!** doesn't seem to fit with the Hebrew, other versions, or UDB.

**Comment by TomWarren** [comment]
The ULB was reworked. 
The ULB of JER 2:24 now reads:
\v 23 How can you say, 'I am not defiled! I have not walked after the Baals'?
\q Look at what you did in the valleys! Consider what you have done—you are a swift female camel running here and there,
\q
\v 24 a wild donkey accustomed to the wilderness, in her heat sniffing the wind!
\q Who can restrain her lust? None of the males need wear themselves out pursuing her; at mating time they will find her. 

The UDB of JER 2:23-24 now reads:
\v 23 You say that you have not sinned.
\q1 You claim to be acceptable to God
\q2 and that you have not worshiped the images of Baal.
\q1 But think about the disgusting things that you do very eagerly in Hinnom Valley outside Jerusalem.
\q2 You are like desperate female camels running here and there to find male camels to mate with.
\q1
\v 24 You are like wild female donkeys that live in the desert.
\q2 They sniff the air to find where the male donkeys are,
\q2 and there is no one who can restrain their lust.
\q1 The male donkeys that want to mate with them only wear themselves out chasing after them; 
\q2 because at mating time they find them easily.

Thanks Susan, 

Tom
