### ISSUE TITLE
John 2:23; 13:29

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#639]
From Allen Pierce:
The tW entry for festival points out that "feast" is used in some English translations because of the 'eating' associated with festivals. But, I note that the ULB uses "feast" two times that are derived from the same Greek word that is translated "festival" everywhere else.  my 'logical reasoning' tells me the ULB should be changed to 'festival' for the sake of consistency (John 2:23; 13:29).

**Comment by TomWarren** [comment]
Is this a request for a change in the ULB?  Let me know. 
Tom  Warren

**Comment by pjoakes** [comment]
Yes, please change the ULB at John 2:23 and 13:29 from "feast" to "festival." That will make the translation consistent and lessen the confusion for translators, since you have translated _heortan_ as "festival" in all other places in John (13x).

**Comment by TomWarren** [comment]
For continuity issues, there are 101 uses of "feast " in the ULB.
"Feast"  is found in the Gospels:
MAT 25:10; 26:5; MRK 12:39;  14:2; 15:6; LUK 2:42, 43; 12:36; 14:8; 15:23, 32; 20:46. It occurs 7x in the rest of the NT.

The ULB of JHN 2:23 now reads:
\v 23 Now when he was in Jerusalem at the Passover, during the **festival**, many believed in his name when they saw the signs that he did.

THe ULB of JHN 13:29 now reads: 
\v 29 Some thought that, since Judas had the moneybag, Jesus said to him, "Buy what we need to have for the **festival**," or that he should give something to the poor.

Thanks,

Tom
