### ISSUE TITLE
Jer 4:5, 6 ULB formatting

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#654]
The formatting of Jer 4:4-6 looks odd.

Should the first lines of 4:5 and 4:6 be all the way to left?

**Comment by TomWarren** [comment]
Yep. The ULB of JER 4:5-6 now reads: 
\v 4 Circumcise yourselves to Yahweh, 
\q and remove the foreskins of your heart,
\q men of Judah and inhabitants of Jerusalem, or else my fury will break out like fire, \q and burn with no one to quench it,
\q because of the wickedness of your deeds.
\q
\v 5 Report in Judah and let it be heard in Jerusalem.
\q Say, "Blow the trumpet in the land."
\q Proclaim, "Gather together. Let us go to the fortified cities."
\q
\v 6 Lift up the signal flag and point it toward Zion, 
\q and run for safety!
\q Do not stay, for I am bringing disaster 
\q from the north and a great collapse.

Thanks, 

TW
