### ISSUE TITLE
Jer 4:7-10 ULB Formatting

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#655]
The formatting for Jer 4:7-10 in the ULB looks odd - especially v8.

**Comment by TomWarren** [comment]
The ULB of JER 4:7-8 now reads: 

\v 7 A lion is coming out from his thicket 
\q and someone who will destroy nations is setting out.
\q He is leaving his place to bring horror to your land,
\q to turn your cities into ruins, where no one will live.
\q
\v 8 Because of this, wrap yourself in sackcloth, lament and wail. 
\q For the force of Yahweh's anger has not turned away from us.
\q
