### ISSUE TITLE
Job 19:27 missing period

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#662]
ULB My kidneys fail within me 

Need a period at the end of this sentence.

**Comment by TomWarren** [comment]
The two uses of "kidneys" in Job seems to need the same note in two places: for 
JOB 16:12 and 19:27, and the rendering of כִּלְיָה. 
Kidneys would seem to be a reference for the seat of emotion, much the same as heart. 
Almost all modern versions translate it as "heart." But, of course, that confuses the 12 occurrences to heart
I am sure you know this. 

Noting that JOB 23:12 added "my heart" wrongly, 
The ULB of JOB 23:12 now reads: 
\v 12 I have not gone back from the commandment of his lips;
\q I have treasured the words of his mouth **more than my portion of food**.
The bold was not in the text, and "my heart" was added. Here it was removed. 

JOB 16:13 changed "heart" back to "kidneys" following the HEB (the only other place where "kidneys" is found.
The ULB of JOB 16:13 now reads: 

\v 13 His archers surround me all around;
\q God pierces my kidneys and does not spare me;
\q he pours out my bile on the ground.

The ULB of JOB 17:11 now reads, after editing, 
\v 11 My days are past; my plans are shattered,
\q and so are the desires of my heart. 

The ULB of JOB 31:7 now reads: 
\v 7 If my step has turned out of the right way,
\q if my heart has gone after my eyes,
\q if any spot has defiled my hands,

The ULB of JOB 31:9-10 now reads, after editing, 
\v 9 If my heart has been deceived by a woman,
\q if I have lain in wait at my neighbor's door,
\q
\v 10 then let my wife grind grain for another,
\q and let others bow down on her.
(the last phrase is problematic, and we are avoiding speculation in the ULB)

The ULB of JER 33:3 now reads: 
\v 3 My words come from the uprightness of my heart;
\q my lips speak pure knowledge.

That is a lot more than you asked for. Hope this is helpful, 

TW
