### ISSUE TITLE
Jer 46:14 punctuation and quotation marks

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#670]
ULB 14"Announce in Egypt, and proclaim it in Migdol, Memphis, **and Tahpanhes.**
**"Take your station** and prepare yourself, for the sword will devour those around you. 

"and Tahpanhes." Would it be better to have a colon or comma here instead of a full stop?

Also, I believe "Take your station..." should open with a single quotation mark.

But, I don't know for sure, where the quotation ends. I suppose both the single and double quotation marks could close at the end of 46:24.

If you do this, you will need to remove the opening double quotation mark at the beginning of verse 18.

**Comment by TomWarren** [comment]
The ULB of JER 46:14-24 has bee edited for punctuation (quotation marks), and it now reads: 

\v 13 This is the word that Yahweh told Jeremiah the prophet when Nebuchadnezzar king of Babylon came and attacked the land of Egypt:
\q
\v 14 "Announce in Egypt, and proclaim it in Migdol, Memphis, and Tahpanhes. 
\q 'Take your station and prepare yourself, for the sword will devour those around you.'

\s5
\q
\v 15 Why are your mighty ones face-down on the ground? They will not stand, because I, Yahweh, have pushed them to the ground.
\q
\v 16 He increases the numbers of those who stumble. Each soldiers falls against the next one. They are saying, 'Get up. Let us go home.
\q Let us go back to our own people, to our native land. Let us leave this sword that is beating us down.'
\q
\v 17 They proclaimed there, 'Pharaoh the king of Egypt is only a noise, one who has let his opportunity slip away.'

\s5
\q
\v 18 "As I live—this is the king's declaration—Yahweh of hosts by name,
\q someone will come who is like Mount Tabor and Mount Carmel by the sea.
\q
\v 19 Pack for yourselves bags to carry into exile, you daughters who live in Egypt.
\q For Memphis will become a waste, a ruin. No one will live there.

\s5
\q
\v 20 Egypt is a very beautiful young cow, but a stinging insect is coming from the north. It is coming.
\q
\v 21 The hired soldiers in her midst are like a fattened bull, but they will also turn away and run away.
\q They will not stand together, for the day of their disaster is coming against them, the time of their punishment.
\q
\v 22 Egypt hisses like a snake and crawls away, for her enemies are marching against her.
\q They are going toward her like woodcutters with axes.

\s5
\q
\v 23 They will cut down the forests—this is Yahweh's declaration—although it is very dense.
\q For the enemies will be more numerous than locusts, unable to be counted.
\q
\v 24 The daughter of Egypt will be made ashamed. She will be given into the hand of people from the north."
\m
