### ISSUE TITLE
Jer 48:27 rhetorical question

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#675]
ULB Was he found among thieves, that you shook your head at him as often as you spoke about him?

UDB Although they were thieves, they were never caught

Is the UDB correct? If I am understanding the question correctly, the implied answer is no.

"Although he was not a thief, you still shook your head at him as often as you spoke about him"

**Comment by TomWarren** [comment]
There are two ways to translate this section: as messianic and as historical. And the additional problem of the antecedent for the pronoun "he": it could be Moab or Israel. 
Israel probably should be preferred. 

The UDB of JER 48:28 now reads: 
\v 27 Did you not ridicule the people of Israel? 
\q1 Did you think they were nothing but thieves, 
\q2 so that you shook your head at them with scorn, 
\q1 and despised them every time you spoke about them?

Thanks John,

Tom
