### ISSUE TITLE
Job 22:30 innocent man?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#676]
ULB He will rescue a man who is innocent

UDB God rescues those who are innocent

I was about to write a note, but thought you may want to look at it, since most other English versions say the opposite of the ULB/UDB. Most say "He will rescue a man who is **not** innocent.

Let me know what you want to do with this, and I will write the note accordingly.

**Comment by TomWarren** [comment]
The ULB of JOB 22:30 now reads:
\v 30 He will rescue even the man who is not innocent;
\q who will be rescued through the cleanness of your hands."

The UDB of JOB 22:30 now reads:
\v 30 God rescues those who are not innocent;
\q2 they will be rescued because you do what is right."

Thanks John, 

Tom
