### ISSUE TITLE
Rom 2:19 ULB  If-clause without a "then-clause

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#685]
_17_ Suppose that you call yourself a Jew, rest upon the law, rejoice proudly in God, _18_ know his will, and test the things that differ from it, having been instructed by the law. _19_ **If** you are convinced that you yourself are a guide to the blind, a light to those who are in darkness, _20_ a corrector of the foolish, a teacher of babies, and that you have in the law the form of knowledge and of the truth.

Sentence 19 starts with "If," but the then-clause doesn't come until v21 in the next chunk,
so I would expect v20 to end with a comma and v21 to start with a lowercase letter.
But if you don't want a sentence to cross over chunks, either the "If" could be replaced with "Suppose" or "Suppose that," or the "if" could be simply deleted.

**Comment by TomWarren** [comment]
The chunk problem. 
This is they way we normally carry the verse across the chunk: 
\v 17 But if you call yourself a Jew and rest upon the law and boast in God,
\v 18 and know his will and approve of what is excellent because you have been instructed from the law;
\v 19 and if you are convinced that you yourself are a guide to the blind, a light to those who are in darkness,
\v 20 a corrector of the foolish, a teacher of babies, and that you have in the law the form of knowledge and of the truth, **then how does this affect the way you live your life?**

\s5
\v 21 You who teach others, do you not teach yourself? You who preach against stealing, do you steal?
\v 22 You who say that one must not commit adultery, do you commit adultery? You who hate idols, do you rob temples?


_**The Bold is an added phrase to conclude the first sentence (question) and to bridge it to the next verse across the chunk. It is a bit of an addition, but there is no other way to bridge the chunk but by concluding one sentence and starting another.**_ 

Thanks 

Tom

**Comment by SusanQuigley** [comment]
That rhetorical question deals with the chunk problem and it fits the context well.  But if we have a figure of speech in the ULB, we should have a note for it. It seems odd to write a note for a figure of speech that is not in the original. I'm not sure how to handle it.

Does the ULB ever have footnotes explaining that a phrase was added to the ULB in order to avoid very long sentences (as Romans 2:17-21 would be)?

**Comment by TomWarren** [comment]
The rhetorical question becomes part of the verse, as a solution to the chunk problem. I do not think that it should be addressed. But a note could be added about the addition. 

The rhetorical question in the text could be cited using the solution that we put into the text; nothing is lost. 

If rhetorical questions or other figures cross chunks, there may be some that are lost, using our system. 

Footnotes are only for textual issues, as I understand it.
