### ISSUE TITLE
Jhn 10:34 ULB - missing quote mark

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#69]
The verse is missing the double-quote mark to close the final "You are gods" quotation. There should be three marks at the end, and there are only two.

"Is it not written in your law, 'I said, "You are gods'"?

Should be:

"Is it not written in your law, 'I said, "You are gods"'"?

**Comment by hharrissWA** [comment]
I edited it this way:
Jesus answered them, "Is it not written in your law, 'I said, "You are gods" '?" 
The question mark should appear after the question closes and before the final quotation mark that ends the quotation. Also are we placing spaces between multiple levels of quotation marks, like: " ' " -- instead of like: "'" ?  I was under the impression we were?

**Comment by lrsallee** [comment]
Harry,

Yes, that looks right.

Larry

**Comment by hharrissWA** [comment]
Thanks!

H


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home


________________________________
