### ISSUE TITLE
Jer 49:29 Different speakers

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#697]
ULB They will take their camels from the people of Kedar and call out to them, 'Terror is all around!"

UDB Everywhere men will shout, 'We are terrified because terrible things are happening all around us!'

ULB has the attacking soldiers shouting. The UDB has the people in the city shouting.

The NIV is more vague: People will shout to them, 'Terror on every side!'

If you want to make the ULB more vague, I can write a note saying either is possible.

(Waiting on your decision to finish the chunk. Thanks)

**Comment by TomWarren** [comment]
The ULB of JER 49:29 with editing, now reads: 
\v 29 Their tents and their flocks will be taken, 
\q along with their tent curtains and all of their equipment; 
\q their camels will be led away from them, 
\q and men will shout to them, "Terror is on every side!" 


The UDB of JER 49:29 was not edited:
\v 29 Their tents and their flocks of sheep will be captured.
\q2 The curtains in their tents and their camels and their other possessions will be taken away.
\q1 Everywhere men will shout,
\q2 'We are terrified because terrible things are happening all around us!' 

Clarity is a quest. 

Thanks John, 

Tom

**Comment by pjoakes** [comment]
To avoid the passive voice in the UDB, how about:
 
\v 29 Enemies will capture their tents and their flocks of sheep.
\q2 They will take away the curtains of their tents, their camels, and all of their other possessions.

**Comment by TomWarren** [comment]
Agree. 
The UDB of JER 49:29 now reads:
\v 29 Enemies will capture their tents and their flocks of sheep.
\q2 They will take away the curtains of their tents, their camels, and all of their other possessions.
\q1 Everywhere men will shout,
\q2 'We are terrified because terrible things are happening all around us!'

Thanks Perry, 

Tom
