### ISSUE TITLE
Jer 5:14-31 ULB  Quote marks

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#712]
14 So Yahweh, the God of hosts says this, **"Because** you have said this, see,
I am about to place my word in your mouth. It will be like a fire, and this people will be like wood! For it will consume them. ... 

31 The prophets prophesy with deceit, and the priests rule with their own power.
My people love it this way, but what will happen in the **end?**

It looks like 31 should end with double quote marks.
My people love it this way, but what will happen in the **end?"**

**Comment by SusanQuigley** [comment]
I was wrong. It looks like the double quote begun in 5:14 ends at 6:8.

And the single quote begun in 5:21 ends at 6:8.

**Comment by TomWarren** [comment]
Quotations:
vs 1 level1 "
vs 2 level2 ' , close ' close level1"
vs 3 level0 (no quote)
vs 4 level1 "
vs5 level1" closed;
vs5b level0 But they all broke their yoke ...
vs12 level1 "He will do 
vs 13 close level1 ... to them." 
vs 14 level0 (no quote)
vs 14 level1, "Because you have ...
vs 19 level2, single quote ... say, 'Why has Yahweh ...
vs 19 level2, close  single quote  ... not your own.'
vs 20 level1, double quote mark continued
vs 21 level2, single quote
vs 24 level3, double quote , "Let us fear Yahweh ...
vs 24 level3, closed
vs 25 level2, continued single quote
vs 31 continued to next chapt at level2, single quote
6:1 begins level2, single quote
6:4 is level3, double quote
6:4 end closes double quote level3.
6:5 returns to level2 single quote
6:8 close level2, single quote
6:8 close level1, double quote.

They are confusing.
