### ISSUE TITLE
Mic 1:6-7

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#734]
\v 6 "I will make Samaria a heap of ruins in the field,
\q **like** a place for planting vineyards.
----- "Like" is not there in Heb. and shouldn't be here.
\q I will pull her building stones into the valley;
\q I will uncover her foundations.
\q
\v 7 All her carved figures will be crushed to pieces;
\q and all the **gifts** to her will be burned up.
\q All her idols I will make a ruin.
\q For from the **gifts** to her prostitution she gathered them,
\q and as a prostitute's **pay** they will return."
----- All three instances of אֶתְנַ֥ן should be rendered alike, as money used to hire a prostitute.

**Comment by TomWarren** [comment]
The ULB of MIC 1:6-7 has been edited and now reads:
\v 6 "I will make Samaria a heap of ruins in the field,
\q a place for planting vineyards,
\q and I will pour her stones down into the valley
\q and I will uncover her foundations.
\q
\v 7 All her carved figures will be broken to pieces,
\q and all her gifts that she received will burned with fire,
\q and I will destroy all her idols.
\q Since she gathered her gifts from the wages of prostitutes,
\q they will become the wages of prostitutes again."

Thanks,

Tom

**Comment by hmw3** [comment]
\v 7 All her carved figures will be broken to pieces,
\q and all her gifts that she received **will burned** with fire,

should be

\v 7 All her carved figures will be broken to pieces,
\q and all her gifts that she received **will be burned** with fire,

**Comment by TomWarren** [comment]
Yep. The ULB of MIC 1:7 has been corrected:
\v 7 All her carved figures will be broken to pieces,
\q and all her gifts that she received **will be burned** with fire,
\q and I will destroy all her idols.
\q Since she gathered her gifts from the wages of prostitutes,
\q they will become the wages of prostitutes again."

Thanks Henry,

Tom
