### ISSUE TITLE
Some footnotes contain both the fqa tag and double quote marks in the text

### ISSUE THREAD

**Issue by cckozie** [Door43/ulb-en#739]
Footnotes in the following chunks have both the fqa tag and double quote marks in the text, so they get rendered in translationStudio with two sets of double quotes.

Source	Chapter	Chunk
en_1co_ulb	14	37
en_1sa_ulb	27	08
en_act_udb	24	04
en_act_udb	24	07
en_act_udb	24	07 (This is a second footnote in the same chunk as the one above)
en_act_ulb	24	04  
en_heb_udb	02	07
en_heb_ulb	12	18
en_mat_ulb	05	43
en_mat_ulb	06	11
en_mat_ulb	20	15
en_mrk_udb	09	42
en_mrk_ulb	09	42
en_rev_ulb	01	07

**Comment by TomWarren** [comment]
To be clear: a section in question:
 \fqa "But if anyone is ignorant of this, let him be ignorant." \f*
would need NO quotation marks. 
Correct?
If so, I can quickly remove the extra quotes. If something else, let me know.

Tom Warren

**Comment by TomWarren** [comment]
I will get to this after the Easter holiday.
Thanks,

Tom

**Comment by TomWarren** [comment]
en_1co_ulb	14	37 quotes removed
en_1sa_ulb	27	08 quotes removed
en_act_udb	24	04 quotes removed
en_act_udb	24	07 quotes removed
en_act_udb	24	07 (This is a second footnote in the same chunk as the one above) quotes removed
en_act_ulb	24	04 NO FOOTNOTE For ULB ACT 24:4
en_heb_udb	02	07 NO FOOTNOTE For UDB HEB 2:7
en_heb_ulb	12	18 quotes removed
en_mat_ulb	05	43 quotes removed 
en_mat_ulb	06	11 quotes removed
en_mat_ulb	20	15 quotes removed
en_mrk_udb	09	42 quotes removed 
en_mrk_ulb	09	44 and 9:46, quotes removed (two footnotes)
en_rev_ulb	01	07 quotes removed

Example: 1SA 27:8
\f + \ft Instead of "the Girzites," \fqa* found in the Hebrew text, some modern versions have \fqa "the Gizrites," \fqa* which is found in the margin of the Hebrew text. \f*

The USFM reader makes this:
[1] Instead of "the Girzites," found in the Hebrew text, some modern versions have "the Gizrites," which is found in the margin of the Hebrew text.

I noted that the \fqa ... \fqa* changes the text to Italic in the USFM.
There are no quotation marks on the \fqa ... \fqa* in the footnotes.
