### ISSUE TITLE
ECC 9:12 evil times

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#741]
...Like animals, human beings are imprisoned in evil times
that suddenly fall on them.

According to the handbook, the phrase above "evil times" refers to the event of people dying not that they are in a environment of evil when they die. This emphasis here is that people die unexpectedly, as if they were trapped.

**Comment by TomWarren** [comment]
The ULB of ECC 9:12 now reads:
\v 12 And furthermore, no one knows when his time will come,
\q2 just as fish are caught in a deadly net,
\q2 or birds are caught in a snare,
\q1 the children of human beings are ensnared by evil times
\q2 that suddenly fall upon them.

I don't think the Handbook is correct at this point. Following the MT, the phrase **evil times** is the agency of the ensnarement of the people.  So that part should stand. 
A note could be written about "evil times" possibly being rendered as "unfortunate times" or "disaster", perhaps.

Thanks,

Tom
