### ISSUE TITLE
Amo 8:14 problem with footnote (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#754]
Footnote: [1]Instead of the sin of Samaria , some versions have Ashimah of Samaria . Ashimah was the name of a pagan goddess worshiped in some parts of Syria. **and say, 'As your god lives, Dan' and, 'As the way to Beersheba exists'—** 

I think the part in bold was not intended to be in the footnote.

**Comment by TomWarren** [comment]
The footnote was edited to include all the sections as part of the footnote, and not as part of the text.
The ULB of AMO 8:14 now reads:
\v 14 Those who swear by the sin of Samaria
\f + \ft Instead of \fqa the sin of Samaria \fqa* , some versions have \fqa Ashimah of Samaria. Ashimah was the name of a pagan goddess worshiped in some parts of Syria. \fqa* . 
\q and say, 'As your god lives, Dan'
\q and, 'As the way to Beersheba exists'—
\f + \ft The Hebrew text has \fqa As the way to Beersheba exists \fqa* , where this might refer to what people going to worship Beersheba's idols might have said. However, some versions want to change the Hebrew text to read \fqa As the loved one of Beersheba lives \fqa* . Here "loved one" stands for an idol worshiped in Beersheba. \fq* .
\q they will fall and never rise again."

That appears to be correct in the USFM. Let me know if not.

Thanks,

Tom
