### ISSUE TITLE
Jer 13:21 change "taught" to "thought" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#758]
ULB those whom you had **taught** to be your friends

Should be "thought"

**Comment by TomWarren** [comment]
The HEB is "taught" לִמַּ֨דְתְּ, but here it means to "cultivate" to "train" so that they would be your "special allies".
It is an unusual construction, so, with the MTT in mind, 
The ULB of JER 13:21 now reads:

\v 21 What will you say when God sets over you those you had trained to be your special allies?
\q Are these not the beginnings of the labor pains that will seize you just like a woman in childbirth?

Thanks John, and hope that helps, 

Tom
