### ISSUE TITLE
AMO 4:3 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#76]
AMO 4:3 ULB and UDB look very different from each other and from the Hebrew text on Bible Hub.
ULB: "every one of you women straight before herself" - This phrase in the ULB is hard to understand. The UDB doesn't have anything like it.

**Comment by TomWarren** [comment]
Amos 4:3 UDB now reads: 
\v 3 Your enemies will drag you out and you will go through breaks in your city walls,
\q2 and they will drive toward Harmon.
\q1 That will surely happen because I, Yahweh, have said it!

ULB now reads: 
\v 3 You will go out through the breaks in the city wall,
\q each one of you going straight through it,
\q and you will be driven out toward Harmon
\q —this is the declaration of Yahweh."

Note on Harmon. 
Harmon is an unknown place: הַרְמוֹן Some think it is Mt Hermon, most agree it is unknown. All major modern versions have "Harmon."

**Comment by SusanQuigley** [comment]
Thanks, for fixing it, Tom. I'll write that translation note and fix the others.

UDB: and they will drive toward Harmon. 
Should this be "and they will drive **you** toward Harmon"?
Could it be changed to "and they will force you to go toward Harmon"?
People who speak English as a second language will probably think it refers to driving a vehicle.

**Comment by TomWarren** [comment]
Yes, "you" I did catch that and repaired it in an edit here, and in the UDB text. 
They sneak up on you. You are quite right, "force you to go" is better. Will effect change.
Thanks. 
Here is the revision: Amos 4:3, UDB
\v 3 Your enemies will drag you out 
\q2 and you will go through breaks in your city walls,
\q2 and they will force you to go toward Harmon.
\q1 That will surely happen because I, Yahweh, have said it!

**Comment by TomWarren** [comment]
Probably need a note on Harmon.

**Comment by SusanQuigley** [comment]
Beautiful. Thank  you, Tom.
