### ISSUE TITLE
2Pe 2:7 ULB - mid sentence chunk start

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#77]
I am hoping we can end the sentence in verse 6 and start a new one in verse 7. Maybe something like, "He also rescued Lot..."

**Comment by lrsallee** [comment]
I believe it was a new sentence until someone recently changed it to span the chunks.

**Comment by TomWarren** [comment]
This is the current state of 2 Pet 2:7 ULB. Seems like all is well. 

\s5
\v 4 For if God did not spare the angels who sinned, but instead handed them down to Tartarus, to be kept in chains in deep darkness until the judgment.
\v 5 For if he did not spare the ancient world, but did preserve Noah, who was a herald of righteousness, along with seven others, but brought a flood upon the world of the ungodly, 
\v 6 and reduced the cities of Sodom and Gomorrah to ashes and condemned them to destruction as an example of what is to come to the ungodly.

\s5
\v 7 And he rescued righteous Lot, who was greatly distressed by the filthy behavior of lawless men. 
\v 8 For that righteous man, living among them day after day, was tormenting his righteous soul because of what he saw and heard.
\v 9 The Lord knows how to rescue godly men out of trials, and how to hold unrighteous men for punishment at the day of judgment.

**Comment by lrsallee** [comment]
Tom,

What you have below does not match what is in the GitHub or D43 version. See here: https://github.com/Door43/ulb-en/blob/master/62-2PE/02.usfm

Larry

**Comment by TomWarren** [comment]
That is weird, because I am using the Github desktop, as always, and it 
is fine.

What should we do?


Tom

**Comment by lrsallee** [comment]
My guess is you have a branching or sync issue that is over my head. I suggest you elevate this to Chris or the IT guys on Slack. Beyond my knowledge.

**Comment by pjoakes** [comment]
I prefer Larry’s rendering below, rather than starting a sentence with “And…”

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jun 3, 2016, at 8:26 AM, lrsallee <notifications@github.com<mailto:notifications@github.com>> wrote:


I am hoping we can end the sentence in verse 6 and start a new one in verse 7. Maybe something like, "He also rescued Lot..."

**Comment by TomWarren** [comment]
I resolved the conflict and it should be right now. Someone make a branch. 
Not me!

**Comment by lrsallee** [comment]
Looking at https://github.com/Door43/ulb-en/blob/master/62-2PE/02.usfm, the top of the page says Harry Harriss edited a long sentence. Probably where it happened.

**Comment by TomWarren** [comment]
The AND was removed.

All is well.

Tom

**Comment by TomWarren** [comment]
Susan and I did a bit of a redo on this section. It seems to fit better

Chiefly, this is hers: 2 Pet 2:4-11

\s5
\v 4 For God did not spare the angels who sinned. Instead he handed them 
down to Tartarus to be kept in chains in deep darkness until the judgment.
\v 5 And he did not spare the ancient world. Instead, he preserved Noah, 
who was a herald of righteousness, along with seven others, when he 
brought a flood upon the world of the ungodly.
\v 6 And God reduced the cities of Sodom and Gomorrah to ashes and 
condemned them to destruction, as an example of what is to come to the 
ungodly.

\s5
\v 7 But when he did that, he rescued righteous Lot, who was greatly 
distressed by the filthy behavior of lawless men.
\v 8 For that righteous man, living among them day after day, was 
tormenting his righteous soul because of what he saw and heard.
\v 9 Therefore the Lord knows how to rescue godly men out of trials, and 
how to hold unrighteous men for punishment at the day of judgment.

\s5
\v 10 This is especially true for those who continue in the corrupt 
desires of the flesh and despise authority. They are bold and 
self-willed. They are not afraid to blaspheme the glorious ones.
\v 11 Angels have greater strength and ability than all men, but they do 
not bring insulting judgments against them to the Lord.

**Comment by lrsallee** [comment]
I like it.
