### ISSUE TITLE
Jer 44:14 awkward wording (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#779]
UDB You people who did not die in Judah **fled here to Egypt to stay here until you could some day you would return to Judah**

Needs rewording

**Comment by TomWarren** [comment]
The ULB also was reworded:
The ULB of JER 44:13-14 now read:
\v 13 For I will punish the people inhabiting the land of Egypt just as I punished Jerusalem with sword, famine, and plague,
\v 14 so that none of the remnant of Judah who have go to live in the land of Egypt will escape or survive or return to the land of Judah, to which they desire to return and live; and none of them will return except a few who escaped from there." 

The UDB of JER 14:14 now reads:
\v 14 None of you people who came from Judah and now live in Egypt, none of you will be successful in any attempt to escape from Egypt, you will not grow in numbers while you live in Egypt, and you will not be able to return to Judah, even though you desire to return to Judah, you will not be able to go back there to live and make your homes. None of you will be able to return to Judah, except only a very small number of you who will be able able to escape from Egypt and return to Judah and live there."

Thanks John,

Tom

**Comment by jhutchins25** [comment]
ULB so that none of the remnant of Judah **who have go** to live in the land of Egypt

I think that should be "who have gone"

**Comment by TomWarren** [comment]
The ULB of JER 44:14 now reads:
\v 14 so that none of the remnant of Judah who have gone to live in the land of Egypt will escape or survive or return to the land of Judah, to which they desire to return and live; and none of them will return except a few who escaped from there."

**Comment by TomWarren** [comment]
Thanks John, 

Tom
