### ISSUE TITLE
Zec 13:4 remove extra "that" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#788]
ULB On that day **that** each prophet will be ashamed of his vision when he is about to prophesy.

Remove "that" after "day."

**Comment by TomWarren** [comment]
The ULB of ZEC 13:4 reads:

**\v 4 **On that day** each prophet will be ashamed of his vision when he is about to prophesy. These prophets will no longer wear a hairy cloak, in order to deceive the people.**

Thanks John, 

Tom 
PS just had the exact fix in Jer from Larry Sallee. Lots of "thats" going round.
