### ISSUE TITLE
Zec 14:10 locations in the UDB (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#793]
UDB The city will extend northeast from the Benjamin Gate and the Corner Gate, which was the first gate, to the Tower of Hananel, and to the king's winepresses to the southwest.

The UBS handbook says Benjamin Gate was northeast, Corner Gate was northwest, the Tower of Hananel was north near Benjamin Gate, and the winepress was in the south.

Would you double check these locations and change UDB if necessary?

**Comment by TomWarren** [comment]
The UDB of ZEC 14:10 (following the UBS notes in ParaTExt) now reads:
\v 10 At that time, all the land in Judah will be flat, like the plain along the Jordan, from the town of Geba in the north to the town of Rimmon far to the south of Jerusalem. Jerusalem will remain high up, as it has always been. The city will extend northeast from the Benjamin Gate and the Corner Gate, which was the old gate, and to the Tower of Hananel, and then extending to the king's winepresses to the southwest.
--------------------------------------
A NOTE could be written about the possibility there there were two "Corner gates" a newer and an older, making two references, or that they were two slightly different descriptions for the same Corner Gate. The matter is not resolved. 

Geba is on the north border of Judah (before the exile). About 6 miles to the south is Jerusalem. 
Rimmon is not known (but to the south).
Benjamin gate is the northeastern extremity of the city wall.
There are two possible candidates for the "Corner Gate" and its identity is not certain.
The other gate may be the old gate, but there is some uncertainty. This UDB is close to the ParaTExt note (see below). 

Whether the reference to the dimensions of the city are four or five points, remains in question. Most think it is four points (as our compass). 

The location of the Winepresses is not known.

The ULB does not attempt to chart a map. 


The UBS notes in ParaTExt say: 
The Gate of Benjamin (mentioned for instance also in Jer 37.13; Jer 38.7) was more or less at the **_northeastern_** extremity of the city wall. Some translators have taken the expression that RSV|prj:RSV52.ZEC.14.10 renders the former gate as a proper name: “the First Gate” (JB, NIV|prj:NIV84.ZEC.14.10) or “Old Gate Place” (CEV|prj:CEVR06.ZEC.14.10). Either way, it is not certain whether the place of the former gate is related to the Corner Gate so that both phrases refer to a single place, or whether they describe two separate places. TEV|prj:GNT92.ZEC.14.10 takes the first view, and restructures to express it unambiguously: “from the Benjamin Gate to the Corner Gate, where there had been an earlier gate” (also JB, FRCL|prj:FCL97.ZEC.14.10,
