### ISSUE TITLE
Ecc 12:3 change to plural (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#805]
ULB That will be the time when the palace **guard** tremble,

Should "guard" be plural?

**Comment by TomWarren** [comment]
The word for guard, means "keeps of the guard" and so is plural.
The ULB of ECC 12:3 now reads:
\v 3 That will be the time when the palace guards will tremble,
\q2 and strong men are bent over,
\q1 and the women who grind cease because they are few,
\q1 and those who look out of windows no longer see clearly.

Thanks,

Tom
