### ISSUE TITLE
ULB Acts 2:30 "one of his descendants"

### ISSUE THREAD

**Issue by TomWarren** [Door43/ulb-en#81]
There had been a lot of conversation on Acts 2:30. I wanted to open an issue on it. 
**\v 30 Therefore, he was a prophet and knew that God had sworn with an oath to him, that he would set one of his descendants upon his throne.**

I have returned the rendering to "one of his descendants" which follows almost all modern translations.

Avoiding the difficult "one of the fruit of his loins" or the indiscrete "one of the fruit of his genitals" (which we all agree is objectionable). 
Loins is a euphemism, or it is inaccurate. 
Genitals is offensive or at least unexpected.
Descendants points to the genetic aspect ("genitals") and the offspring of David.But moves away from the figure of speech "fruit of his loins/genitals".

This is the only "fruit of his loins" that had occurred in the ULB.

Is there a better rendering than "one of his descendants"?

The more opaque the figure, the more difficult to present it.

**Comment by TomWarren** [comment]
I had this on the UDB side. This is a ULB issue.

**Comment by lrsallee** [comment]
I personally do no like the use of the archaic "fruit of his loins" and much, much prefer "one of his descendants."

My (minimal) understanding of this current issue is that Perry would like as many figures as possible to remain in the ULB so they can reference them in the checking/core tool the are developing. It seems to me that using the original FOS here would sacrifice understanding in favor of having fuller tool results. But we will develop a TN to work around whatever the text team decides.

**Comment by TomWarren** [comment]
I have been developing a measurement for the complexity of figures, and the more opaque the figure, the more difficult it is to preserve it. Simpler figures "good shepherd" "sheep" "light of life" can be explained or restated, but complex ones like Acts 2:30 defy explanation and require restatement.

**Comment by TomWarren** [comment]
Uses of  ὀσφῦς (loins/ genitals)
Matt 3:4 leather belt around his **waist**
Mark 1:6 leather belt around his "waist"
Luke 12:35 gird your "waist"
Acts 2:30 one of the fruit of his **loins/genitals**
Eph 6:14 the **belt** of truth
Heb 7:5 ἐκ  τῆς  ὀσφύος  Ἀβραάμ· from the **descendants** of Abraham (a Hebraism)
Heb 7:10 in the **loins** of his ancestor
1 Pet 1:13 **gird** your minds for action

**Comment by richmahn** [comment]
Why is everyone being "assigned" this issue? We are already "Watch"ing this repository (if one chose to), so don't need to be assigned this. Assigning means who will take the next action on it, usually one or maybe two people. Just FYI.

**Comment by SusanQuigley** [comment]
Tom,

If a particular figure of speech is complex (often because it involves more than one figure of speech), I wonder if it would work well to keep part of it as a figure and translate part of it without the figure.  For example, for ”fruit of his loins,” keep the fruit metaphor, but ignore the ”loins” metonym.  The OT-ULB often uses ”fruitful” to talk about having many descendants.

Acts 2:30 could have one of these:
that he would set one of his fruits upon his throne.
that he would set one of the fruits of his body upon his throne.

And depending on which is used, one of these notes could be added.
his fruits - In this metaphor his descendants are spoken of as his fruit. AT: ”his descendants” (See: metaphor)
one of the fruits of his body - In this metaphor, his descendants are spoken of as the fruit of his body.  AT: ”his descendants” (See: metaphor)

I’m not asking you to change the ULB - ”descendants” is fine too.

I’m just presenting the idea of keeping part of the figure.

On Jun 7, 2016, at 9:35 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I have been developing a measurement for the complexity of figures, and the more opaque the figure, the more difficult it is to preserve it. Simpler figures "good shepherd" "sheep" "light of life" can be explained or restated, but complex ones like Acts 2:30 defy explanation and require restatement.

**Comment by TomWarren** [comment]
The idea of separating out the more opaque aspects of the figure seems good. That way the figure is held, but there is room to explain the points of complexity that would be difficult for the MTT.

**Comment by pjoakes** [comment]
I like the second of Susan’s options below.

Perry
Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jun 7, 2016, at 11:33 AM, SusanQuigley <notifications@github.com<mailto:notifications@github.com>> wrote:

Tom,

If a particular figure of speech is complex (often because it involves more than one figure of speech), I wonder if it would work well to keep part of it as a figure and translate part of it without the figure. For example, for ”fruit of his loins,” keep the fruit metaphor, but ignore the ”loins” metonym. The OT-ULB often uses ”fruitful” to talk about having many descendants.

Acts 2:30 could have one of these:
that he would set one of his fruits upon his throne.
that he would set one of the fruits of his body upon his throne.

And depending on which is used, one of these notes could be added.
his fruits - In this metaphor his descendants are spoken of as his fruit. AT: ”his descendants” (See: metaphor)
one of the fruits of his body - In this metaphor, his descendants are spoken of as the fruit of his body. AT: ”his descendants” (See: metaphor)

I’m not asking you to change the ULB - ”descendants” is fine too.

I’m just presenting the idea of keeping part of the figure.

On Jun 7, 2016, at 9:35 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I have been developing a measurement for the complexity of figures, and the more opaque the figure, the more difficult it is to preserve it. Simpler figures "good shepherd" "sheep" "light of life" can be explained or restated, but complex ones like Acts 2:30 defy explanation and require restatement.

**Comment by TomWarren** [comment]
Been thinking about this. If "the fruit of his loins(body)" is a Hebraism would it not be good to "translate" the Hebraism into English? "His descendants". We have a two language bridge to cross, from Hebrew into Greek, and from Greek into English. If we carry the Hebraism into English, could it be that we are not translating, but interlinearizing? That is, I think, why most of the translations do the work for the reader of translating the Hebraic figure into the common phrase, "his descendants."  
Should we consider Hebraisms differently from other figures?  I am thinking so. But open to reasons to jump two languages into not translating the idiom, or translating only part of it. If we use "the fruit" that is carrying half of the figure into English (and requires explanation), but simply taking the Hebraism, and translating it into English, makes it clear.
To the principle: 
I am trying to see how any Hebraism should be treated in the ULB and UDB. Do we transliteralize it or do we translate it into meaningful English?

**Comment by SusanQuigley** [comment]
I don't have a problem with the "fruit" figure. We kept it in the OT for many uses: fruit of my/our/your/his/her/their/the body, womb, beasts, cattle, land, ground, mouth, lips, words, deeds, labor, practices, hands, and righteousness. 

The NT-ULB has fruit of your womb, the Spirit, righteousness, the light, and our lips.

But in Acts 2:30  there's also the  "set [him] on his throne" metonym. Removing the 'fruit of his body" metaphor makes the whole phrase simpler.



I don't have a pr

**Comment by TomWarren** [comment]
Here it is: 
\v 30 Therefore, he was a prophet and knew that God had sworn with an oath to him, that he would set one of the fruit of his body upon his throne.
