### ISSUE TITLE
Act 7:19

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#820]
ULB - \v 19 This same king deceived our people and treated our fathers so badly, they had forced our _fathers to expose their infants to danger,_ so they would not be kept alive.

UDB - \v 19 That king cruelly tried to get rid of our ancestors. He oppressed them and caused them to suffer greatly. He even commanded them to _throw their newborn babies outside their homes_ so that they would die.

This is from a MAST Regional Coordinator:
Would you submit the following verse for review. I believe it is a poor translation:

Acts 7:19 (ULB)

Proposed change:

This same king deceived our people and treated our forefathers so badly, _they were forced to abandon their infants_ so they would die.

**Comment by TomWarren** [comment]
The ULB of ACT 7:19 now reads:
\v 19 This same king deceived our people and treated our fathers so badly, they had forced our fathers to leave their newborn children outside so they would die.

The UDB of ACT 7:19 reads without changes: 
\v 19 That king cruelly tried to get rid of our ancestors. He oppressed them and caused them to suffer greatly. He even commanded them to throw their newborn babies outside their homes so that they would die.

Thanks, 

Tom
