### ISSUE TITLE
lam 1:12 typo (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#826]
UDB because he **was** punished me

Should be "has"

**Comment by TomWarren** [comment]
The UDB of LAM 1:12 now reads:
\v 12 You people who pass by,
\q2 you do not seem to care at all about what has happened to me.
\q1 Look around and see that there are no other people who are suffering as I do.
\q1 Yahweh has caused me to suffer
\q2 because **he has punished me** on the day he was angry with us, his people.

Thanks John, 

Tom
