### ISSUE TITLE
Mrk 9:23 ULB - space between quotation marks

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#83]
This extra space causes a ULB snippet mismatch. Why is it present?

*said to him, " 'If you are able

**Comment by hharrissWA** [comment]
Larry, it is my understanding that a space is needed between quotation marks like this because without the space the reader may not be able to tell what the resulting mark is. It looks like three lines (which it is): "' or '" 
Of course, those familiar with English punctuation can figure this out, but MTTs could likely have a difficult time deciphering such a mark (though it is two marks). 
I believe there are many such marks throughout the ULB and UDB. Again, it is my understanding that this is how we were to be doing such marks, with a space in between. If we need to remove those spaces, we need to know, and likely a search should be done to make corrections according to whatever standard is decided upon.
Thanks,
Harry

**Comment by TomWarren** [comment]
We have not been using the space in the complex three and four level quotations we used e.g. in Jeremiah. 
This will be ok. The extra space may be the way others have treated these complex quotations, but the way they have been used through out is the simpler way, which avoids the extra space. When the scripts are run, these extra spaces are considered as mistakes, and they cause a lot of time. 
We can leave these out. 
Thanks.

**Comment by hharrissWA** [comment]
Ok. I will leave the space out going forward, but I have been putting a space there up until now, so there does need to be a search and "rescue" (correction) done. :)
Thanks!
Harry

**Comment by TomWarren** [comment]
What I do is do a search for the form I have a question about, and that usually tells me what has been normative. That saves time and usually keeps my edits consistent with what has been done. 
All is well.

Tom

**Comment by hharrissWA** [comment]
Ok, thanks much!
Harry
