### ISSUE TITLE
Lam 2:8 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#830]
UDB 2:8 that our enemies **whould** tear down

Should be "would"

(Sorry, I should have put all these typos in one email)

**Comment by TomWarren** [comment]
The UDB had already been corrected at this point.
The ULB of LAM 2:8 reads:
\v 8 Yahweh was determined
\q2 that our enemies would tear down our city wall.
\q1 It was as though he had first measured the walls
\q2 and then completely destroyed them.
\q1 It was as though he caused the towers and walls to lament
\q2 because they were now ruins.

Humm. 
Tom
