### ISSUE TITLE
2ch 9:16 ULB  Palace/House

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#836]
2ch 9:16 ULB  the king put them into the **Palace** of the Forest of Lebanon.

Could the word "Palace" be changed to "House" as in 2ch 9:20?

**Comment by TomWarren** [comment]
The ULB of 2CH 9:16 now reads:
\v 16 He also made three hundred shields of beaten gold. Three minas of gold went into each shield; the king put them into the House of the Forest of Lebanon.

The ULB of 2CH 9:20 reads:
\v 20 All King Solomon's drinking cups were gold, and all the drinking cups in the House of the Forest of Lebanon were of pure gold. None were silver because silver was not considered valuable in Solomon's days.

The UDB of 2CH 9:16 now reads:
\v 16 His workers made three hundred smaller shields. They covered each of them with one and three-quarters kilograms of gold. Then the king put those shields in the House of the Forest of Lebanon.

The UDB of 2CH 9:20 now reads: 
\v 20 All of Solomon's cups were made of gold, and all the various dishes in the House of the Forest of Lebanon were made of gold. They did not make things from silver, because during the years that Solomon ruled, silver was not considered to be valuable.

Hope that helps. 

Tom
