### ISSUE TITLE
2ch 9:29 ULB Capital letters needed in title

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#839]
As for the other matters concerning Solomon, first and last, are they not written in The History of Nathan the Prophet, in The Prophecy of Ahijah the Shilonite, and in **The Visions of Iddo the Seer concerning Jeroboam son of Nebat**?

If "concerning Jeroboam son of Nebat" is part of the title of Iddo's book, then I think "concerning" and "son" should also be capitalized.

**Comment by TomWarren** [comment]
The names of the books appear to be of similar length (as would be the case where similar books were dealing with similar subjects). The last book in the list (The Visions of Iddo the Seer) seems to one of three books dealing with Solomon, but in the case of the last, it also had information about Jeroboanm son of Nebat. For clarity, that additional information about Jeroboam was put into parenthesis, so that the reader would not think that all the books (including Nathan's  and Ahijah's) also had information about Jeroboam son of Nebat. 

The ULB of 2CH 9:29 now reads:
\v 29 As for the other matters concerning Solomon, first and last, are they not written in The History of Nathan the Prophet, in The Prophecy of Ahijah the Shilonite, and in The Visions of Iddo the Seer (which also pertained to Jeroboam son of Nebat)?

The UBS notes in ParaTExt has this:
Concerning Jeroboam the son of Nebat: These words are difficult to understand in this context. They seem to indicate that the third source, the visions of Iddo the seer, deals with the reigns of both Jeroboam and Solomon. Since it is Solomon who is in focus in this verse, it is probably best to translate these words as “who also wrote about Jeroboam, son of Nebat.” FRCL has a separate sentence here, saying “This last book deals [also] with the history of Jeroboam, son of Nebat” (similarly PV). Jeroboam the son of Nebat was the first king of the northern kingdom of Israel after it broke away from Judah (see 1 Kgs 11.16–12.20). He ruled 931–910 B.C. The negative rhetorical question in this verse is a way of strongly affirming that the things about Solomon were certainly written in the sources cited. In some languages the whole verse will have to be restructured as a statement. A possible model is: • A person can find out about everything that Solomon did while he was king, from start to finish, in The Record of Nathan the Prophet and in The Prophecy of Ahijah from Shiloh, and also in The Visions of Iddo the Seer, which also describes the reign of Jeroboam son of Nebat. 

More than is necessary and still ...

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
That makes sense. Thanks for the explanation.

**Comment by TomWarren** [comment]
I fiddled with the UDB a bit, but the effect is the same. 

Tom

**Comment by SusanQuigley** [comment]
Thanks for putting the info about Jeroboam in parentheses. 

UDB: Lists of all the other things that Solomon did are written in the scrolls written by the prophet Nathan, and by the prophet Ahijah from the city of Shiloh, and in the scroll in which **was written** the visions of the prophet Iddo (a scroll in which visions of Iddo **were also written** about Jeroboam son of Nebat). 

I find what's in the parenthesis a bit difficult to understand. How would this be?
(a scroll in which Iddo's visions about Jeroboam son of Nebat were also written).

**Comment by TomWarren** [comment]
That is better. 
The UDB of 2CH 9:29 now reads:
\v 29 Lists of all the other things that Solomon did are written in the scrolls written by the prophet Nathan, and by the prophet Ahijah from the city of Shiloh, and in the scroll in which was written the visions of the prophet Iddo (a scroll in which Iddo's visions about Jeroboam son of Nebat were also written).

Thanks, 

Tom
