### ISSUE TITLE
Php 3:8 ULB Punctuation

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#852]
In fact, now I count all things to be loss because of the surpassing value of the knowledge of Christ Jesus my Lord, **for him I have given up all things— and I consider them rubbish—so that I may gain Christ 9and be found in him.**

It looks like there should be a semi-colon or period following "Christ Jesus my Lord."
What follows it is a full sentence.

**Comment by TomWarren** [comment]
The ULB of PHP 3:8-9 now reads (with minor changes):
\v 8 In fact, now I count all things to be loss because of the surpassing value of the knowledge of Christ Jesus my Lord. For him I have given up all things—and I consider them rubbish—so that I may gain Christ
\v 9 and be found in him. I do not have a righteousness of my own from the law. Instead, I have the righteousness that is through faith in Christ, the righteousness that is from God based on faith.

Thanks, 
Tom
