### ISSUE TITLE
2 Ch 32:31 ambiguous phrase

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#853]
UDB God allowed Hezekiah to say what he himself wanted to say

This statement may not be clear. The phrase "he himself" could refer to Hezekiah or to God. Maybe "God allowed Hezekiah to say whatever he wanted to say" is clearer.

**Comment by TomWarren** [comment]
The UDB of 2CH 32:31 with some editing, now reads:
\v 31 But when messengers who were sent by the rulers of Babylon came and asked about the miracle that God had performed in the land, it was then that God left Hezekiah alone in order to test him. God tested him so that he would know everything that was in Hezekiah's heart.
