### ISSUE TITLE
1Ch 11:18 Typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#856]
ULB far be it far from me

Remove second "far."

**Comment by TomWarren** [comment]
This was taken care of in another edit.
The ULB of 1CH 11:18 now reads:
\v 19 Then he said, "**May it be that I should never do this!** Should I drink the blood of these men who have risked their lives?" Because they had put their lives at risk, David refused to drink it. These were the deeds of the three mighty men.

Thanks,

Tom
