### ISSUE TITLE
GEN 3:14-20 Problem with indents

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#87]
In Gen 3:14-20 more is showing up indented than probably should be.
https://door43.org/en/ulb/ep/ot shows the following as indented.
'
3:16 To the woman he said,  (The actual quote is indented, but this phrase should not be.)
3:17 To Adam he said,
3:20 The man called his wife's name Eve ...

**Comment by TomWarren** [comment]
Brought the margins over in the changing quotations. The USFM has the changes displayed, but here they are:
14Yahweh God said to the serpent,
"Because you have done this, cursed are you alone among all the livestock and all the beasts of the field.
It is on your belly that you will go, and it is dust that you will eat all the days of your life.
15I will put hostility between you and the woman, and between your seed and her seed.
He will bruise your head, and you will bruise his heel."
16To the woman he said,
"I will greatly multiply your pain in having children; it is in pain that you will give birth to children.
Your desire will be for your husband, but he will rule over you."
17To Adam he said, "Because you have listened to the voice of your wife, and have eaten from the tree, concerning which I commanded you, saying, 'You may not eat from it.'
Cursed is the ground because of you;
in painful toil you will eat from it all the days of your life.
18It will produce thorns and thistles for you, and you will eat the plants of the field.
19By the sweat of your face you will eat bread,
until you return to the ground, for out of it you were taken.
For dust you are, and to dust you will return."
20The man called his wife's name Eve because she was the mother of all living things. 21Yahweh God made for Adam and for his wife garments of skins and clothed them.
