### ISSUE TITLE
2ch 22:10-12 Missing verse and formatting problem in ULB (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#884]
Most of verse 11 is missing in ULB, and the footnote appears in the text.

**Comment by TomWarren** [comment]
The footnote was missing a "\" it had "\f + ft" and it should have had "\f + \ft" and all is well. 
The ULB of 2CH 22:10-12 now reads:
\v 11 But Jehosheba, \f + \ft \fqa Jehosheba \fqa* may be spelled \fqa Jehoshaba \fqa* in some versions. \f* a daughter of the king, secretly took Joash son of Ahaziah away from the king's sons who were about to be killed. She put him and his nurse into a bedroom. So Jehosheba, a daughter of King Jehoram, the wife of Jehoiada the priest (for she was the sister of Ahaziah), hid him from Athaliah, so that Athaliah did not kill him.

Thanks John,

Tom

**Comment by TomWarren** [comment]
The USFM has it: 

10 Now when Athaliah, the mother of Ahaziah, saw that her son was dead, she arose and killed all the royal children in the house of Judah. 11 But Jehosheba,[1] a daughter of the king, secretly took Joash son of Ahaziah away from the king's sons who were about to be killed. She put him and his nurse into a bedroom. So Jehosheba, a daughter of King Jehoram, the wife of Jehoiada the priest (for she was the sister of Ahaziah), hid him from Athaliah, so that Athaliah did not kill him. 12 He was with them, hidden in the house of God for six years, while Athaliah reigned over the land.
