### ISSUE TITLE
2 Ch several verses. Capitalization of "Spirit"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#891]
ULB 15:1 The spirit of God

ULB 18:23 the Spirit of Yahweh

ULB 20:14 the spirit of Yahweh

ULB 24:20 he Spirit of God

The capitalization of "spirit" is not consistent, but I'm not sure if they should up upper case or lower case.

**Comment by TomWarren** [comment]
The ULB of 2CH 15:1 now reads:
\v 1 **The Spirit of God** came on Azariah son of Oded.
The ULB of 2CH 18:23 is unchanged:
\v 23 Then Zedekiah son of Kenaanah, came up, slapped Micaiah on the cheek, and said, "Which way did **the Spirit of Yahweh** take to go from me to speak to you?"
The ULB of 2CH 20:14 now reads:
\v 14 Then in the middle of the assembly, **the Spirit of Yahweh** came on Jahaziel, son of Zechariah, son of Benaiah, son of Jeiel, son of Mattaniah, the Levite, one of the sons of Asaph.
The ULB of 2CH 24:20 is not changed:
\v 20 The **Spirit of God** came on Zechariah son of Jehoiada, the priest; Zechariah stood above the people and said to them, "God says this: Why do you transgress the commandments of Yahweh, so that you cannot prosper? Since you have forsaken Yahweh, he has also forsaken you."


I did a survey (quickly) on all of these "spirit of God" "spirit of Yahweh" and fixed a few. 

Thanks John, 

Tom
