### ISSUE TITLE
1jn 2:1, 24 and 5:1, 4 ULB Capitalization not needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#899]
Since the phrases after the colons are not sentences, they do not need to be capitalized.

1jn 2:1
By this we know that we know him: **If** we keep his commandments.

1jn 2:24
This is the promise he gave to us: **Eternal** life.

1jn 5:1
Because of this we know that we love God's children: **When** we love God and do his commandments.
For this is love for God: **That** we keep his commandments.

1jn 5:4
And this is the victory that has overcome the world: **Our** faith.

**Comment by TomWarren** [comment]
I follow your lead here. I reviewed some work  I did last week and here are the results.
The ULB of 1JN 2:1 now reads:
\v 3 We know that we have come to know him, if we keep his commandments.
1JN 2:24 now reads:
\v 25 This is the promise he gave to us—eternal life.
1JN 5:2 now reads:
\v 2 Because of this we know that we love God's children, when we love God and do his commandments.
1JN 5:4 now reads:
\v 4 For everyone who is born from God overcomes the world. And this is the victory that has overcome the world, even our faith.

Thanks Susan, 

Tom
