### ISSUE TITLE
Rom 8:15 ULB and UDB  "the Spirit of bondage"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#902]
ULB: For you did not receive **the Spirit of bondage** again so as to fear. Instead, you received the Spirit of adoption, by which we cry, "Abba, Father!"

UDB: This is because you have received from God **a Spirit who does not make you fear God again**. You are not like slaves who fear their masters. On the contrary, this Spirit has made us God's children. The Spirit now enables us to cry out to God, "You are my Father!"

The ULB's "the Spirit of bondage" implies that there is a divine Spirit of bondage.  The UDB's "a Spirit" implies that there may be more than one divine Spirit.  Other versions do not capitalize "spirit." (TEV is the exception. It restructures it to talk about what the Spirit does not do: "For the Spirit that God has given you does not make you slaves and cause you to be afraid")

Could the ULB "the Spirit of bondage" be changed to "the spirit of bondage" or "a spirit of bondage"?
Could the UDB be changed to something like this? "This is because the Spirit you received from God does not make you afraid of God again like slaves who are afraid of their masters."

**Comment by TomWarren** [comment]
The ULB of ROM 8:14-15 now reads:
\v 14 For as many as are led by the Spirit of God, these are sons of God.
\v 15 You did not receive a spirit of that makes you slaves, so that you live in fear again; but you received the Spirit of adoption, by which we cry, "Abba, Father!"

The UDB of ROM 8:15 now reads:
\v 15 This is because you have not received a spirit who makes you live in fear. You are not like slaves who fear their masters. On the contrary, God has give you his Spirit, and his Spirit has made us God's children. The Spirit now enables us to cry out to God, "You are my Father!"

Thanks,

Tom

**Comment by SusanQuigley** [comment]
ULB You did not receive a spirit **of** that makes you slaves, so that you live in fear again; but you received the Spirit of adoption, by which we cry, "Abba, Father!"

Thanks for the changes. This is clearer. The word "of" in the first sentence just needs to be deleted.

**Comment by TomWarren** [comment]
Awgh. Thanks so much, 

The ULB of Rom 8:15 now reads:
\v 15 You did not receive a spirit that makes you slaves, so that you live in fear again; but you received the Spirit of adoption, by which we cry, "Abba, Father!"

Double thanks,

Tom
