### ISSUE TITLE
Tit 2:9, 10 ULB mismatching verb forms

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#904]
Slaves are to obey their masters in all things. They are to please them and not argue with them. 10 They **should not steal** from them, **but demonstrating** all good faith, so that in every way they may bring credit to the teaching about God our Savior.

Could the verb forms on either side of "but" match? (What I wrote in the first suggestion below appears not to match, but in English, "should" has scope over both verbs.)

Slaves are to obey their masters in all things. They are to please them and not argue with them. 10 
They **should not steal** from them **but demonstrate** all good faith, so that in every way they may bring credit to the teaching about God our Savior.
or 
Slaves are to obey their masters in all things. They are to please them and not argue with them 10 **or steal** from them. **Rather they should demonstrate** all good faith, so that in every way they may bring credit to the teaching about God our Savior.

**Comment by TomWarren** [comment]
The participles were inconsistently rendered. 
The ULB of TIT 2:9-10 now reads, with reconnecting the sentence, to preserve the argument:
\v 9 Slaves are to obey their masters in all things. They are to please them and not argue with them,
\v 10 they are not to steal from them, but they are to demonstrate all good faith, so that in every way they may bring credit to the teaching about God our Savior.

I think this reads better.
Thanks Susan, 

Tom
