### ISSUE TITLE
Gen 33:10, 15

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#913]
מָצָ֤אתִי חֵן֙ בְּעֵינֶ֔יךָ
is translated "I have found favor in your sight" in v. 10, but
אֶמְצָא־חֵ֖ן בְּעֵינֵ֥י אֲדֹנִֽי
is translated "My master has already been kind enough to me" in v. 15.

The latter is UDB-ish. Consider using "favor" in both places. This might be a good item to concord throughout the ULB, e.g., Jdg 6:17.

**Comment by TomWarren** [comment]
The ULB of GEN 33:15 now reads:
\v 15 Esau said, "Let me leave with you some of my men who are with me." But Jacob said, "Why do that? Let me find favor in the eyes of my lord."

I have reviewed the occurrences of "if I have found favor" from the ESV in the ULB:
GEN 18:3 “O Lord, if I have found \\favor in your \\sight, do not pass by your
GEN 19:19 your servant has found \\favor in your \\sight, and you have shown me
GEN 30:27 to him, “If I have found \\favor in your \\sight, I have learned by
GEN 32:5 in order that I may find \\favor in your \\sight.’”
GEN 33:10 “No, please, if I have found \\favor in your \\sight, then accept my present
GEN 34:11 her brothers, “Let me find \\favor in your \\eyes, and whatever you say to
GEN 47:29 to him, “If now I have found \\favor in your \\sight, put your hand under my
GEN 50:4 saying, “If now I have found \\favor in your \\eyes, please speak in the ears
EXO 33:13 therefore, if I have found \\favor in your \\sight, please show me now your
EXO 33:13 know you in order to find \\favor in your \\sight. Consider too that this
EXO 33:16 be known that I have found \\favor in your \\sight, I and your people? Is
EXO 34:9 said, “If now I have found \\favor in your \\sight, O Lord, please let the
NUM 11:11 And why have I not found \\favor in your \\sight, that you lay the burden
NUM 11:15 kill me at once, if I find \\favor in your \\sight, that I may not see my
NUM 32:5 they said, “If we have found \\favor in your \\sight, let this land be given
JDG 6:17 to him, “If now I have found \\favor in your \\eyes, then show me a sign that
RUT 2:10 to him, “Why have I found \\favor in your \\eyes, that you should take
RUT 2:13 Then she said, “I have found \\favor in your \\eyes, my lord, for you have
1SA 1:18 said, “Let your servant find \\favor in your \\eyes.” Then the woman went her
1SA 20:3 knows well that I have found \\favor in your \\eyes, and he thinks, ‘Do not
1SA 20:29 So now, if I have found \\favor in your \\eyes, let me get away and see
1SA 25:8 let my young men find \\favor in your \\eyes, for we come on a feast
1SA 27:5 to Achish, “If I have found \\favor in your \\eyes, let a place be given me
2SA 14:22 knows that I have found \\favor in your \\sight, my lord the king, in
2SA 16:4 pay homage; let me ever find \\favor in your \\sight, my lord the king.”
NEH 2:5 if your servant has found \\favor in your \\sight, that you send me to
EST 7:3 answered, “If I have found \\favor in your \\sight, O king, and if it

And the ESV for "favor in my " 
EXO 33:12 and you have also found \\favor in my \\sight.’
EXO 33:17 will do, for you have found \\favor in my \\sight, and I know you by
1SA 16:22 my service, for he has found \\favor in my \\sight.”
All have been rendered as: **favor in your eyes,** 
or **favor in my eyes.**


Thanks Henry, 

Tom
