### ISSUE TITLE
GEN 3:17 ULB Change period to comma

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#93]
"Because you have listened to the voice of your wife, and have eaten from the tree, concerning which I commanded you, saying, 'You may not eat from it.'

This is just the beginning of a sentence. It should end in a comma.

"Because you have listened to the voice of your wife, and have eaten from the tree, concerning which I commanded you, saying, 'You may not eat from it,'

**Comment by TomWarren** [comment]
The whole section needed to be formatted consistently. Hope this is better. 

\v 16 To the woman he said, 
\q "I will greatly multiply your pain in having children; 
\q it is in pain that you will give birth to children.
\q Your desire will be for your husband, but he will rule over you."
\m

\s5
\v 17 To Adam he said, 
\q "Because you have listened to the voice of your wife, 
\q and have eaten from the tree, concerning which I commanded you, 
\q saying, 'You may not eat from it,' 
\q cursed is the ground because of you; 
\q in painful toil you will eat from it all the days of your life. 
\q
\v 18 It will produce thorns and thistles for you, 
\q and you will eat the plants of the field.
\q
\v 19 By the sweat of your face you will eat bread,
\q 
until you return to the ground, for out of it you were taken. 
\q For dust you are, and to dust you will return."
\m

**Comment by SusanQuigley** [comment]
I think that's good. I'm not convinced that the first three lines are really poetry, but treating them as poetry makes the whole sentence and the whole poem run smoothly. (It looks nicer than having a sentence be part prose and part poetry.)
