### ISSUE TITLE
Luk 19:21 ULB "exacting standards"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#934]
for I was afraid of you, because you are **a man of exacting standards**. You take up what you did not put in, and you reap what you did not sow.'

I would expect **a man of exacting standards** to take exactly what was due him. I would not expect him to take more or to be dishonest. What would you think of changing this to something like one of these?

a demanding/strict/harsh/austere man

**Comment by TomWarren** [comment]
Tried to work it out, but "demanding man" didn't seem to sound right. Try this:
The ULB of LUK 19:20-21 now reads:
\v 20 Another came, saying, 'Lord, here is your mina, which I kept safely in a cloth,
\v 21 for I was afraid of you, because you are a demanding person. You take up what you did not put in, and you reap what you did not sow.'

Thanks,

Tom

**Comment by SusanQuigley** [comment]
That works. Thank you.

**Comment by SusanQuigley** [comment]
Could you also change this to "a demanding person" in Luke 19:22?

**Comment by TomWarren** [comment]
Yep. 
The ULB of LUK 19:22 now reads:
\v 22 The nobleman said to him, 'By your own words I will judge you, you wicked servant. You knew that I am a demanding person, that I take up what I did not put in, and that I reaped what I did not sow.

Thanks,

Tom
