### ISSUE TITLE
Hab 2:15

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#943]
Because the versions are divided pretty much down the middle as regards the second clause

you express your anger and you make them drunk 

consider a footnote alerting the reader to the alternative

pouring it from the wineskin till they are drunk (The Holy Bible: New International Version. (1984). (Hab 2:15). Grand Rapids, MI: Zondervan.)

**Comment by TomWarren** [comment]
The ULB of HAB 2:15 now reads:
\v 15 'Woe to the one who forces his neighbors to drink—
\q you express your anger \f + \ft There is some question about whether the Hebrew should be translated as \fqa anger \fqa* or as \fqa wineskin.\f* over and you make them drunk 
\q in order to look at their nakedness.'

The USFM looks like this (to some degree):
15 'Woe to the one who forces his neighbors to drink—
you express your anger [1] over and you make them drunk
so you can look at their nakedness.'
16 You will be filled with shame instead of glory.
Now it is your turn! Drink, and you will expose your uncircumcised foreskin!
The cup in Yahweh's right hand is coming around to you,
and disgrace will cover your glory.
----------------------------------------------------------------------------------------------------------
[1] There is some question about whether the Hebrew should be translated as _anger_ or as _wineskin_.
