### ISSUE TITLE
Acts 25:21, 25  ULB the emperor versus Emperor

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#952]
25:21 ULB:  But when Paul appealed to be kept in custody while awaiting the decision of **the emperor**, I ordered him to be held in custody until I could send him to Caesar."

25:25 ULB I learned that he had done nothing worthy of death; but because he appealed to **Emperor**, I decided to send him. 

Could _tou sebastou_ and _ton sebaston_ be translated the same way -- ether both as "the emperor" or both as "Emperor"?

**Comment by TomWarren** [comment]
The guideline was that the title of "king" or "emperor" would be LC except when in the title of a specific leader, "King David" or "Emperor Nero." Here "emperor" is LC.

**The UDB are listed first, and then the ULB (which this Issue addresses) is listed last.** 
Also changed the UDB: 
UDB Act 17:7:
\v 7 and this fellow Jason has asked them to stay at his house. They are acting against the **emperor**. They say that another person, whose name is Jesus, is the real king!"
UDB Act 18:2:
\v 2 There he met a Jew whose name was Aquila, who was from the region of Pontus. Aquila and his wife Priscilla had come a short time previously from the city of Rome, in Italy. They left Rome because Claudius, the Roman **emperor**, had ordered that all the Jews must leave Rome.
UDB Act 25:10:
\v 8 Then Paul spoke for himself. He said, "I have done nothing against the law of the Jews, nor against the temple, nor against the **emperor**."
UDB Act 25:26:
\v 26 But I do not know what exactly I should write to the emperor about him. That is why I have brought him here to speak to you all, and especially to you, King Agrippa! I have done this so that you may question him. Then I may know what to write to the **emperor**.
UDB Act 25:27:
\v 27 I think that it would be unreasonable to send a prisoner to the **emperor** in Rome without telling exactly what were the wrong things people say that he has done."
UDB Act 27:1:
\v 1 When the Governor decided that we should sail for Italy, he put Paul and some other prisoners into the control of an army captain whose name was Julius. He held the rank of centurion and was part of a large number of soldiers who were under the direct command of the **emperor**.
UDB Act 27:24:
\v 24 The angel said to me, 'Paul, do not be afraid.S You must go to Rome and stand before the **emperor** there so that he can judge you. I want you to know that God has granted to you that all those who are traveling by ship with you will also survive.'
UB Act 28:19:
\v 19 But when the Jewish leaders there spoke against the desire of the Romans to set me free, I had to request that the **emperor** judge me here in Rome. But my reason for doing that was not that I wanted to accuse our leaders about anything.

**I have checked the entire ULB for consistency.** 
The ULB of ACT 25:21 now reads:
\v 21 But when Paul appealed to be kept in custody while awaiting the decision of the **emperor**, I ordered him to be held in custody until I could send him to Caesar."

Thanks Susan, 

Tom
