### ISSUE TITLE
1 Co 5:3-5 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#958]
For, although I am absent in body but still present in spirit, I have already judged the one who did this, just as though I were there. 4When you gather together in the name of our Lord Jesus, and my spirit is there as well in the power of our Lord Jesus, **I have already judged this person.** 5I have done this to hand this man over to Satan for the destruction of the flesh, so that his spirit may be saved on the day of the Lord.

This **I have already judged this person.** at the end of v. 4 seems strange. (The UDB also has this issue.)
1) Since the firsts two clauses of v. 4 seem to refer to some future time, it seems odd to have the last clause be past tense. 
2) UDB and other versions make "you" the subject of "hand over" in v5.

Could 4 and 5 be changed to something like this?
When you gather together in the name of our Lord Jesus, and my spirit is there as well in the power of our Lord Jesus, 5hand this man over to Satan for the destruction of the flesh, so that his spirit may be saved on the day of the Lord.

Also, I'm not sure how "in the power of our Lord Jesus" is to related to the phrases before it. 
Is it that they gather in the name of our Lord Jesus and in the power of our Lord Jesus?
Or is that both Paul's spirit and the power of the Lord are there?

**Comment by TomWarren** [comment]
This is a case where breaking up the Pauline logic into bits makes the argument very difficult to follow. I have edited the section into more of a whole, and I think it reads much better. 
The ULB of 1CO 5:3-5 now reads:
\v 3 For even though I am absent in body, I am present in spirit. I have already passed judgment on the one who did this, just as though I were there.
\v 4 When you are assembled in the name of our Lord Jesus and I am with you in spirit, and the power of our Lord Jesus is present,
\v 5 hand this man over to Satan for the destruction of the flesh, so that his spirit may be saved on the day of the Lord.

Look this over. 

Thanks Susan, 

Tom

**Comment by TomWarren** [comment]
The UDB of 1CO 5:3-5 now reads:
\v 3 I am not with you physically, but I am very concerned for you all, and I am with you in my spirit. And I have already judged the one who did this, just as if I were with you.
\v 4 When you gather together for worship under the authority of the Lord Jesus—and I am worshiping with you in spirit— 
\v 5 you should turn this man over to Satan out into the world, so that his physical body might be destroyed, so that God may save his spirit on the day of the Lord's return.

There it is. 

Tom

**Comment by SusanQuigley** [comment]
Thanks, Tom. These are clearer.
