### ISSUE TITLE
Gal 3:27  ULB  meaning of "put on Christ"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#959]
ULB For as many of you as were baptized into Christ, **you have received Christ**. 

The UDB and UBS-TH interpret "have put on Christ" as "have become like Christ" or "have taken on Christ's character." This fits with other uses of the clothing metaphor where clothing represents moral qualities: clothed with power, clothed with joy, put on righteousness.

But the context doesn't really seem to fit that. I think "have received Christ" is also a figure of speech, meaning "have become united with Christ" or "belong to Christ"? What do you think?

Could ULB be changed to include the metaphor, and then the tN could explain the two possible meanings?

"you have clothed yourselves with Christ" 
"you are now clothed with Christ" 
"you  are now wearing Christ"

**Comment by TomWarren** [comment]
Yep. The ULB of GAL 3:27 now reads:
\v 27 For all of you  who were baptized into Christ have clothed yourselves with Christ.

The UDB of GAL 3:27 now reads:
\v 27 All of you who trust in Christ and were baptized so that you are joined to him, have taken on the characteristics of Christ's life. 

Hope that helps, 

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
That helps. Thanks.
